### ISSUE TITLE
Subscribing to a non existing topic silently kills the consumer

### ISSUE THREAD

**Issue by Licenser** [fede1024/rust-rdkafka#111]
When subscribing to a topic that doesn't exist will silently kill the consumer.

When calling `subscribe` on a stream consumer with at least one of the topics not existing on kafka the consumer as a whole will not receive messages. The `subscribe` call will not return an error either.

**Comment by benesch** [comment]
Thanks for the report, @Licenser. Unfortunately this is a known bug in librdkafka: https://github.com/edenhill/librdkafka/issues/1201. I'm afraid there's not much we can do on our end in the meantime, so closing this out.
