### ISSUE TITLE
Is new connection created for each producer.send()

### ISSUE THREAD

**Issue by surajpayu** [fede1024/rust-rdkafka#113]
I would like to understand the connection management of rdkafka for FutureProducer. Does it create a new connection every time i call send() ?
Also, can this behavior be tuned?

**Comment by gklijs** [comment]
No, connection will be kept open. Right now you will have an open connection to every known Kafka broker. When this will move to the 1.0.0 of librdkafka it uses sparse connections and only holds connection to the relevant brokers.
When you call send, the record also won't be directly send, it's rather like it's put in the send queue. For example if you set the property 'linger.ms' to 100. It will wait till either 100ms have passed, or when the queue becomes 'full' before the data is actually send from the client to the broker.

**Comment by noderat** [comment]
@gklijs Is this now resolved in the latest release that is using librdkafka 1.0.0?

**Comment by gklijs** [comment]
Not sure about the details, but indeed it should be something like:
- when producer is created topic metadata is fetched from brokers.
- short after calling send a connection will be made with the broker that is leader of that topic partition.
- connection is kept open for possible next sends.

Not sure what the behaviour is in case of rebalance.

**Comment by gklijs** [comment]
Some more details here, https://github.com/edenhill/librdkafka/issues/825, might be improved further, since now there is still a thread for every broker (but idle all time when not needed, andnot connected).

**Comment by benesch** [comment]
Closing, as librdkafka v1.0+ supports sparse connections, and any additional tuning options need to be added upstream anyway.
