### ISSUE TITLE
Missing tag 0.20.0

### ISSUE THREAD

**Issue by gertvdijk** [fede1024/rust-rdkafka#114]
It seems [0.20.0 was released on crates.io](https://crates.io/crates/rdkafka/0.20.0) and the release is mentioned in the changelog with https://github.com/fede1024/rust-rdkafka/commit/53c4dbdbd324f31b99855ce79852fe3ab6a0582b as well, but there's not tag in this repository; latest is `v0.19.0`. Forgot to push tags after release? :smile:

**Comment by flavray** [comment]
Good catch! :) I just pushed a `v0.20.0` tag, should be fixed now
