### ISSUE TITLE
0.21.0 breaks build on Rust Docker image

### ISSUE THREAD

**Issue by austinhartzheim** [fede1024/rust-rdkafka#126]
# Problem
Using the official [Rust docker image](https://hub.docker.com/_/rust), I am unable to build version `0.21.0`, whereas `0.20.0` worked without issue. The error I see is:
```
--- stderr
Building and linking librdkafka statically
Running command: "./configure --disable-sasl --enable-ssl --disable-lz4" in dir: librdkafka
Running command: "make -j 4 libs" in dir: librdkafka
thread 'main' panicked at 'Unable to find libclang: "couldn\'t find any valid shared libraries matching: [\'libclang.so\', \'libclang-*.so\', \'libclang.so.*\'], set the `LIBCLANG_PATH` environment variable to a path where one of these files can be found (invalid: [])"', src/libcore/result.rs:997:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
``` 

# Solution
I am able to build successfully after installing some additional dependencies in the image (copied from the Dockerfile in this repo):
`apt-get install -y llvm-3.9-dev libclang-3.9-dev clang-3.9`

Based on the description in d9321f2b1f132d554d2c5854803fcb2869c6495c, it looks like the new dependencies are intended. Perhaps the new dependencies could be mentioned in the changelog to help anyone with broken builds?

Let me know if there is additional information I can provide.

Thanks!

**Comment by gertvdijk** [comment]
I'm using a custom Docker image and even with the new dependencies it fails to install.

Using Debian Stretch, I can choose to install libclang 5.0 and 6.0 from -backports. Both seem incompatible with the build script supplied.

In my Dockerfile:

```
RUN apt-get update \
    && apt-get -y --no-install-recommends install \
        -t stretch-backports \
        'libclang1-6.0=1:6.0-*' \
        'libclang-common-6.0-dev=1:6.0-*' \
    && rm -rf /var/lib/apt/lists/*

# This prints the file, present in /usr/lib/llvm-6.0/lib/clang/6.0.0/include.
RUN find /usr -name "stddef.h"

# Tried this env var hint for include path, but then other packages fail to install,
# looking in this directory when they should not.
# ENV CPATH=/usr/lib/llvm-6.0/lib/clang/6.0.0/include
```

Snippet from the error with cargo (without CPATH env setting):
```
--- stderr
Building and linking librdkafka statically
Running command: "./configure --disable-sasl --disable-ssl --disable-lz4" in dir: librdkafka
Running command: "make -j 2 libs" in dir: librdkafka
/usr/include/stdio.h:33:11: fatal error: 'stddef.h' file not found
/usr/include/stdio.h:33:11: fatal error: 'stddef.h' file not found, err: true
thread 'main' panicked at 'failed to generate bindings: ()', src/libcore/result.rs:997:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

Anybody got rdkafka 0.21 to install on Debian Stretch?

**Comment by ArtRand** [comment]
I also encountered this, on my Linux machine (macOS was fine). I suspect that anyone using docker to build a project will also see it and scratch their head. A pre-install check or at least a README would be great. Also sounds like other rust projects suffer from this (from googling).

**Comment by gertvdijk** [comment]
* The `configure` script passes without clang installed, but fails on `make`, which is very misleading and I think it the `configure` script of rdkafka is missing some checks.
* [The commit](https://github.com/fede1024/rust-rdkafka/commit/d9321f2b1f132d554d2c5854803fcb2869c6495c) mentions the requirement on `libclang`, but if you install only `libclang` packages, the build of rdkafka still fails on a missing `stddef.h` - you need the `clang` package too.
* The `clang-6.0` package from stretch-backports/buster also works.

**Comment by thijsc** [comment]
I've been spending a bunch of time at getting things to compile because of this today. I see how generating the bindings is easier for the release process, but for users of the crate it's quite a lot of hassle. Think this might even hold back adoption because it's not apparent why you can't build.

I think we should consider rolling this back.

**Comment by thijsc** [comment]
Did anybody get this to work with the CircleCI Rust image? Even after installing the packages I get:

```
Building and linking librdkafka statically
Running command: "./configure --disable-sasl --enable-ssl --disable-lz4" in dir: librdkafka
Running command: "make -j 2 libs" in dir: librdkafka
thread 'main' panicked at 'Unable to find libclang: "couldn\'t find any valid shared libraries matching: [\'libclang.so\', \'libclang-*.so\', \'libclang.so.*\'], set the `LIBCLANG_PATH` environment variable to a path where one of these files can be found (invalid: [])"', src/libcore/result.rs:997:5
stack backtrace:
```

**Comment by thijsc** [comment]
Ping, still don't have a working build on CircleCI. I will open a pull request to revert the bindgen change.

**Comment by bruceg** [comment]
I am also unable to get 0.21.0 to compile on Gentoo Linux with llvm/clang 8 without setting `$LIBCLANG_PATH`. Version 0.20.0 works fine.

**Comment by Roguelazer** [comment]
Note that this completely breaks 0.21 for platforms that have Rust but no Clang, as far as I can tell... It would be nice to continue to support platforms that don't have clang...

**Comment by benesch** [comment]
Hi, sorry for the pain that PR caused. Unfortunately I don't have easy access to a FreeBSD machine, so checking in the bindings meant that I couldn't bump the version of librdkafka, since I couldn't regenerate the bindings on FreeBSD. (And this is a cost that must be paid whenever there's a new librdkafka version, which is often.) One thing we could consider is bundling the bindings on Linux only, I suppose.

Note that there's an upstream issue for bindgen to bundle libclang that may be of interest: https://github.com/rust-lang/rust-bindgen/issues/918

**Comment by Roguelazer** [comment]
Would it be possible to, I dunno, collect money to run an EC2 instance once a quarter when a new release happens? This is a breaking change for me because there's no straightforward way to get an appropriate build of libclang for my platform.

**Comment by benesch** [comment]
What platform do you use, @Roguelazer?

**Comment by Roguelazer** [comment]
RHEL6

-- 
James Brown,
currently mobile

**Comment by benesch** [comment]
I came up with a solution here that I think will satisfy everyone. Bindings are again checked into version control, so bindgen/libclang/clang are no longer build time dependencies. This time, however, the bindings are not platform-specific (they depend on platform-specific types like libc::FILE as necessary), so they don't need to be regenerated once per platform like before.
