### ISSUE TITLE
Is ToBytes meant to be extended?

### ISSUE THREAD

**Issue by edrevo** [fede1024/rust-rdkafka#128]
Sorry if this is a very basic question. I'm still getting the hang of Rust in general.

I want to send some Json messages to a Kafka topic. I have a struct which can be serialized to json:

```rust
#[derive(Serialize)]
struct MyStruct {
  foo: u8
}
```

In an ideal world, I'd like to be able to use that type directly in the payload:

```rust
let v = MyStruct { foo: 8 };
FutureRecord::to("mytopic")
  .payload(v)
  .key(&());
```

However, in order for that to work, I need to implement `ToBytes`, which I can't, since I would need to generate the bytes inside the `to_bytes` function:

```rust 
impl ToBytes for MyStruct {
    fn to_bytes(&self) -> &[u8] {
        serde_json::to_string(self).unwrap().as_bytes() // Doesn't compile, since the function returns a reference
    }
}
```

Is ToBytes supposed to be used this way? If what I'm looking for isn't possible with `ToBytes`, would it be possible to add a more lenient `CopyBytes` that returns a `[u8]` instead of a `&[u8]`?

**Comment by gklijs** [comment]
I started with the example, but use Avro, and ended up using this, https://github.com/openweb-nl/open-bank-mark/blob/ch-rust/command-handler/src/kafka_producer.rs. When you use Kafka from Java you have to supply a key and/or value deserializer. The records themselves are always binary. So it seems to make sense to me to do the serialization part 'yourself' just before creating the record in case of the producer, and just after you got the record in case if the consumer.

**Comment by benesch** [comment]
So it would be perfectly reasonable to implement `ToBytes` for a type of your own, provided there was a cheap way to convert that type to a byte slice. What I mean by "cheap" is what the comment on `ToBytes` mentions:

https://github.com/fede1024/rust-rdkafka/blob/47a5cc7442e4eb8815d6cfda79ae87aa9aaf2fbe/src/message.rs#L551-L552

Basically, there needs to be some way to produce a byte representation that does not involve an allocation and cannot fail. (This is what is implied by a signature of `&self -> &[u8]`.) The function you're after has a signature of `&self -> Vec<u8>`.

We don't want to be in the business of invoking serialization logic, which might be arbitrarily expensive. As @gklijs, the recommended practice is to do the serialization yourself, like so:

```rust
let v = MyStruct { foo: 8 };
let ev = serde_json::to_vec(&v)?;
FutureRecord::to("mytopic")
  .payload(&ev)
  .key(&());
```
