### ISSUE TITLE
Support for key and value serializer on ClientConfig

### ISSUE THREAD

**Issue by jaketarnow** [fede1024/rust-rdkafka#129]
Is there any support to set `io.confluent.kafka.serializers.KafkaAvroSerializer` for key.serializer/value.serializer on ClientConfig? Thanks!

**Comment by gklijs** [comment]
I think the present just returning bytes is fine. You can use (self promotion) https://crates.io/crates/schema_registry_converter to convert them using the confluent schema registry. See https://github.com/gklijs/open-bank-mark/blob/one-broker-ch-rust/command-handler/src/kafka_consumer.rs for an example.

**Comment by jaketarnow** [comment]
Thanks for the response @gklijs. Are you stating that by using the `schema_registry_converter::schema_registry::get_schema_by_id` should help with deserializing on another system via consumer instead of performing a:
```
        .set("key.serializer", "io.confluent.kafka.serializers.KafkaAvroSerializer")
        .set("value.serializer", "io.confluent.kafka.serializers.KafkaAvroSerializer")
```
in Rust? My full workflow is having a producer in Rust that sends an Avro record to a Kafka topic that is picked up on another system that is not Rust and is using Confluent + Kafka. Thanks again.

**Comment by gklijs** [comment]
Kind of, for producing https://github.com/gklijs/open-bank-mark/blob/one-broker-ch-rust/command-handler/src/kafka_producer.rs is a better example. For the same thing you described, putting a message on a topic with rust, using the schema registry, in order for another (could be JVM thing to read it). Kafka always used bytes underneath. So instead of doing it with a serde you can also convert it to bytes just before sending to the producer. This way the logic for the conversion to and from bytes using avro can be in a separate crate, independent of the Kafka client or version.

**Comment by jaketarnow** [comment]
Perfect, thanks!

**Comment by jaketarnow** [comment]
@gklijs No need to re-open this issue, but I have also looked at your schema_registry_converter code that you mentioned last comment. For the value_values that you use in `send` in the impl of `RecordProducer` does this have to match anything in regard to the avro_rs::types::Value payload? for instance the avro namespace or overall record name? Thanks for the help

**Comment by gklijs** [comment]
Could you share the code, and maybe better to make an issue on schema_registry_converter. It's really a seperate step from getting the data to/from kafka. For the producer this means there is a way to use an avro schema to transform a vector of key/value pairs to bytes in the same way it would be done on the jvm. There is a [test](https://github.com/gklijs/schema_registry_converter/blob/master/src/lib.rs#L378) with the same error. It seems the name of the property you use in the vector does not match the schema.
The schema use depends on the Strategy, you can supply the schema, else it will use the latest available.
