### ISSUE TITLE
Error in mac bindings

### ISSUE THREAD

**Issue by thijsc** [fede1024/rust-rdkafka#130]
When installing on Mac you get this error:

```
Checking rdkafka-sys v1.0.0
error: unexpected close delimiter: `]`
   --> /Users/thijs/appsignal/appsignal-processor-rs/target/debug/build/rdkafka-sys-c4f650a1f84b020c/out/bindings.rs:956:40
    |
956 | # [ derive ( Copy , Clone ) ]; 16usize ] , }# [ test ]
    |                                        ^ unexpected close delimiter

error: aborting due to previous error

error: Could not compile `rdkafka-sys`.

To learn more, run the command again with --verbose.
```

Seems like there is a typo in the bindings?

**Comment by gklijs** [comment]
I'm also using a Mac and didn't have the problem. Maybe your using an older version of rust and/or something has gone wrong installing and is now cashed?

**Comment by thijsc** [comment]
Just did a fully clean build on Rust stable 1.35.0, getting the same error. How are you compiling this to work?

**Comment by thijsc** [comment]
Maybe the bindings were generated with nightly?

**Comment by thijsc** [comment]
Did some more digging. I can actually compile the crate by itself. I do get the error when compiling a project where this crate is a dependency. Seems liked a different version of `bindgen` might be the culprit, but tried that and got the same result. So still not sure why this is happening.

**Comment by thijsc** [comment]
Even with fully updated dependencies on 1.35.0 I get the same error when compiling as a dependency. Bit baffled by this.

**Comment by thijsc** [comment]
Not sure why, but #133 fixes this for me.

**Comment by gklijs** [comment]
Nice it's fixed at least. Also compiling as dependency worked in my case, on stable, not sure how up to date I was.
