### ISSUE TITLE
API ergonomics?

### ISSUE THREAD

**Issue by matthias-margush** [fede1024/rust-rdkafka#131]
Hi! 

I recently started looking at this library and going through the examples. I'm new to Rust (but not kafka). One thing that was confusing to me right away was understanding what `message` consists of in the [simple_consumer example](https://github.com/fede1024/rust-rdkafka/blob/master/examples/simple_consumer.rs#L69-L79):

```rust
        match message {
            Err(_) => warn!("Error while reading from stream."),
            Ok(Err(e)) => warn!("Kafka error: {}", e),
            Ok(Ok(m)) => {
                let payload = match m.payload_view::<str>() {
                    None => "",
                    Some(Ok(s)) => s,
                    Some(Err(e)) => {
                        warn!("Error while deserializing message payload: {:?}", e);
                        ""
                    },
                };
                // ...
            },
        };

```

In particular, the level of nesting to unwrap to get to a payload value:: `Ok` -> `Ok` -> `Some` -> `Ok`. I eventually figured it out, but wound up wondering if there was a way to simplify this at the API level. As an experiment, I tried fiddling around with flattening the result of `MessageStream::poll`, and came up with [this](https://github.com/matthias-margush/rust-rdkafka/pull/1/files#diff-370d0daef9d576af78ac8b5e57d8eaa0R87):

```diff
--- a/src/consumer/stream_consumer.rs
+++ b/src/consumer/stream_consumer.rs
@@ -84,17 +84,22 @@ impl<'a, C: ConsumerContext + 'static> MessageStream<'a, C> {
 impl<'a, C: ConsumerContext + 'a> Stream for MessageStream<'a, C> {
-    type Item = KafkaResult<BorrowedMessage<'a>>;
-    type Error = ();
-
-    fn poll(&mut self) -> Poll<Option<Self::Item>, Self::Error> {
-        self.receiver.poll()
-            .map(|ready|
-                ready.map(|option|
-                    option.map(|polled_ptr_opt|
-                        polled_ptr_opt.map_or(
-                            Err(KafkaError::NoMessageReceived),
-                            |polled_ptr| polled_ptr.into_message_of(self.consumer)))))
+    type Item = BorrowedMessage<'a>;
+    type Error = KafkaError;
+
+    fn poll(&mut self) -> Poll<Option<BorrowedMessage<'a>>, KafkaError> {
+        match self.receiver.poll() {
+            Ok(Async::NotReady) => Ok(Async::NotReady),
+            Ok(Async::Ready(Some(Some(v)))) => {
+                match v.into_message_of(self.consumer) {
+                    Ok(message) => Ok(Async::Ready(Some(message))),
+                    Err(e) => Err(e),
+                }
+            },
+            Ok(Async::Ready(None)) => Ok(Async::Ready(None)),
+            Ok(Async::Ready(Some(none))) => Err(KafkaError::NoMessageReceived),
+            Err(e) => Err(KafkaError::MessageConsumption(RDKafkaError::Fail)),
+        }
     }
 }
 ```

Besides reducing the unwrap() nesting, the flatter structure allows the combinators in [futures::stream::Stream](https://docs.rs/futures/0.1.26/futures/stream/trait.Stream.html), such as `map_err()`, `then()`, `for_each()` to work more naturally over the stream messages. You can see how this also [simplifies many of the examples & tests](https://github.com/matthias-margush/rust-rdkafka/pull/1/files). 

- **for_each()**: Already defined to unwrap `Ok`s, so additional unwrapping isn't needed within the callback. In addition, errors don't need to be separately filtered since this already happens (they are routed to `map_err()`.

- **map_err()**: Applies to all errors in the stream, not just the outer level.

- **then()**: Applies to all `Result`s, so this takes the role of `for_each` if needed, in the examples.

To me, this greatly improves the ergonomics of the API. 

As I said, I'm new to Rust and I'm sure there are some considerations I've missed.  I'd be interested in your thoughts!

**Comment by gklijs** [comment]
It would be a breaking change, and it's easy to do for the user. I also don't think it's a good idea to map Ok(Async::Ready(Some(none))) to an error, this could be fine when nothing is available.
I did find this library hard to use compared to other Kafka clients. I'm not sure through if it should be fixed here other whether it should be a separate library.

**Comment by benesch** [comment]
I'm happy to report that this is much cleaner now with `async/await` and the `recv` helper method on `MessageStream`: https://github.com/fede1024/rust-rdkafka/blob/928f6f1da8e7d391bd39014a1f17096c8502c106/examples/simple_consumer.rs#L61-L82
