### ISSUE TITLE
Zstd compressing

### ISSUE THREAD

**Issue by RicoGit** [fede1024/rust-rdkafka#136]
Hi there. Is there some possibility to build `rust-rdkafka` against `librdkafka` with `zstd` codec? Thank you in advance.

**Update:**
I have an issue with compiling librdkafka 1.0.1 + musl + zstd, but librdkafka 1.1.0 is working fine. Could you consider to support librdkafka 1.1.0 soon?

**Comment by benesch** [comment]
zstd support was added in 0efbcf381, and librdkafka was bumped to v1.2.1 in #154.
