### ISSUE TITLE
Is this function safe to use and support futures for async processing ? Need simple Producer usage

### ISSUE THREAD

**Issue by bcashier** [fede1024/rust-rdkafka#141]
Hi,

I need to use simple function to produce Kafka messages with a solid function, that process producing on demand when requested by users:

```rust
//Send messages to Kafka
fn produce(brokers: &str, topic_name: &str, messages: String) {
    let producer: FutureProducer = ClientConfig::new()
        .set("bootstrap.servers", brokers)
        .set("produce.offset.report", "true")
        .set("message.timeout.ms", "5000")
        .create()
        .expect("Producer creation error");


    producer.send(
        FutureRecord::to(topic_name)
            .payload(&format!("Message {}", messages))
            .key(&format!("Key {}", messages))
            .headers(OwnedHeaders::new()
                .add("header_key", "header_value")),
        0
    );
}
```

Do this function is safe and performente ? support futures ?

Thanks in advance.

**Comment by gklijs** [comment]
Safe yes, performant not at all since you create a producer for every message. I use a channel to be able to produce from multiple places to one Producer instance. This way it can send multiple messages over the wire at the same time, depending on you config. https://github.com/gklijs/obm_confluent_blog/blob/rust-rdkafka-async/command-handler/src/kafka_producer.rs

**Comment by bcashier** [comment]
@gklijs Your answer is appreciated !

Lets say that I want use a channel to send the messages to the producer, how can I process please ?

The link here is just the producer function:
https://github.com/gklijs/obm_confluent_blog/blob/rust-rdkafka-async/command-handler/src/kafka_producer.rs

That let us to produce message for the consumers.

Waiting your answer, thank you again :)

**Comment by gklijs** [comment]
The rest of the code is in the same project. In my case they both consume and produce to Kafka. So I have a kind of similar abstraction for the consumer, https://github.com/gklijs/obm_confluent_blog/blob/rust-rdkafka-async/command-handler/src/kafka_consumer.rs. Which basically spawned a new tread and start consuming the topic, executing some function on every item. Let me know if you have more questions.

**Comment by bcashier** [comment]
@gklijs Thank you again.

I mean in your previous message, you said that my function is not performent since I have to produce a new message for each requests.

But I see that It's same thing for the producer function you linked to me.

Since I can't produce messages by using loop or at once, the messages are produced on users requests.

Please correct me if I misunderstood your suggestion, appreciated.

**Comment by gklijs** [comment]
You create the producer in the function to send the message. By wrapping the producer in a 'recordProducer' I reuse the same producer. It's doing a but more through.
What it comes down to use that you only want to create the product once, and then call the send on that producer for everything that's need to go to Kafka. But because it's mutable you need some way to work around it. That part is in https://github.com/gklijs/obm_confluent_blog/blob/rust-rdkafka-async/command-handler/src/main.rs with the send_loop that reuses the same producer.

**Comment by bcashier** [comment]
@gklijs Unfortunatelly I can't do that.

Since the user send a form from HTML page to a destination URL reponsible to fetch the infos submitted and send them back using KAFKA to another server so they can be processed.

In this case, for each request the producer will be reinitiliazed and must be called again for each request :( The loop in this case will not work.

Another solution, is to use GRPC in order to pass data from one server to another where KAFKA used in a LOOP and received GRPC messages there, but it's not good practice ... I have to get additional server + using kafka producer directly instead of GRPC will be same I think.

Thank you again for your time and efforts :)

**Comment by gklijs** [comment]
I don't see why the loop won't work. It loops waiting for a message to be added to the channel. It doesn't matter how the message will be added to the channel.

**Comment by bcashier** [comment]
@gklijs You mean the loop will be used for consumer ? Tes I understand you in this point, I am using loop to listen for new messages produced.

But what about producing message ? I can use loop for this since for each request, the script will be reinitialized and launched again, therefor producer aswell.

By Channel you mean Topic ? or is another way to provide message to be produced ? IF yes, what is the process if possible.

Sorry for my misunderstanding ... I am new in Kafka and know only the concept of Producing/Consuming messages.

**Comment by gklijs** [comment]
Where I said channel a mend a rust specific channel used to share data between threads. 
How do you mean 'the script will be reinitialized again? You want to run it serverless? In my case it runs inside docker, and stays running until turned off. So each time the container is started only one producer is created.

**Comment by bcashier** [comment]
@gklijs Thank you again for your answer and sorry for taking more of your time !

In order to be clear and demonstrate the problem properely, I will post some of my codes:

```rust
extern crate rdkafka;

use actix_web::{web, App, HttpResponse, HttpServer};
use serde::{Deserialize};

use rdkafka::config::ClientConfig;
use rdkafka::producer::{FutureProducer, FutureRecord};
use rdkafka::util::get_rdkafka_version;
use rdkafka::message::OwnedHeaders;

#[derive(Deserialize)]
struct FormData {
    thing_to_send: String,
}

//Send messages to Kafka
fn produce(brokers: &str, topic_name: &str, messages: String) {
    let producer: FutureProducer = ClientConfig::new()
        .set("bootstrap.servers", brokers)
        .set("produce.offset.report", "true")
        .set("message.timeout.ms", "5000")
        .create()
        .expect("Producer creation error");


    producer.send(
        FutureRecord::to(topic_name)
            .payload(&format!("Message {}", messages))
            .key(&format!("Key {}", messages))
            .headers(OwnedHeaders::new()
                .add("header_key", "header_value")),
        0
    );
}

//Get message to send from HTML form and use Kafka to send it and consume it elsewhere
fn sendthis(form_data: web::Form<FormData>) -> String  {
	let brokers = "localhost:9092";
	let topic_name = "testTopic";
	let messages = form_data.thing_to_send.to_string();
	
	//Send using KAFKA
    produce(&brokers, &topic_name, messages);
	
	"it's ok".to_string()
}

fn main() {
    HttpServer::new(|| App::new()
        .route("/sendthis", web::post().to(sendthis)))                                                                
        .bind("0.0.0.0:8080")                                                                                                                        
        .unwrap()                                                                                                                                    
        .run()                                                                                                                                       
        .unwrap();                                                                                                                                   
}

```

I am using actixweb as web server and to receive datas from HTML form:

```html
<form action="http://127.0.0.1:8080/" method="get">
<input type="text" name="thing_to_send" value="Example of value to send">
<input type="submit">
```

In this case, how it is possible to use the example of script you provided please:
https://github.com/gklijs/obm_confluent_blog/blob/rust-rdkafka-async/command-handler/src/kafka_producer.rs

I mean, since the web server already launching, how to send received datas using Channels and share it to another thread that already have the LOOP we are talking for ? (Of course, if I really understood the concept).

Thank you again and waiting your answer :)

**Comment by gklijs** [comment]
I'm afraid I know to little about atix to provide a concrete solution. Basically in your main you also need to create the producer, but the problems is good to access that later on.
Since atix_web is working with workers, each in a separate thread, you either need a producer per worker, or a channel per worker. But I don't know how to do this.

**Comment by bcashier** [comment]
@gklijs I just opened another issue to know more how to solve this integration.

Thank you again :)

**Comment by bcashier** [comment]
@gklijs FInally, I just followed your references and it was easy to integrate with actixweb.

Thanks !
