### ISSUE TITLE
Bump librdkafka to 1.1.0

### ISSUE THREAD

**Issue by bruceg** [fede1024/rust-rdkafka#146]
The 1.1.0 release is out with a couple of new settings that I need to be able to use.
https://github.com/edenhill/librdkafka/releases/tag/v1.1.0

**Comment by benesch** [comment]
Same boat! There's a PR open for this (https://github.com/fede1024/rust-rdkafka/pull/144), although I don't think it's quite right yet. We'll need @flavray or @fede1024 to come by and revise and merge, though sadly I think they've both been quite busy with other things lately.

@fede1024 or @flavray, I'd be happy to help maintain, if that would be helpful.

**Comment by gklijs** [comment]
I'm also swamped for the moment, have some more time from November.

**Comment by benesch** [comment]
rdkafka has been upgraded to v1.2.1 by #154.
