### ISSUE TITLE
Implement `ToOpaque` for `Arc`

### ISSUE THREAD

**Issue by datto-aparrill** [fede1024/rust-rdkafka#147]
`Arc` would be a nice type to have available for `DeliveryOpaque`, and provides `to_ptr` and `from_ptr` which would make implementation straightforward.

**Comment by datto-aparrill** [comment]
Ew, `as_ptr` doesn't consume the object. It just assumes that `Box::as_ref() as *const T` is ok and `mem::forget`s the object, rather than using the `Box::to_ptr` function that is made for this use case. Can the trait be changed to consume the object instead?

**Comment by benesch** [comment]
> `Arc` would be a nice type to have available for `DeliveryOpaque`, and provides `to_ptr` and `from_ptr` which would make implementation straightforward.

Seems reasonable. I've opened #171 to address this.

> Ew, `as_ptr` doesn't consume the object. It just assumes that `Box::as_ref() as *const T` is ok and `mem::forget`s the object, rather than using the `Box::to_ptr` function that is made for this use case. Can the trait be changed to consume the object instead?

There is no `Box::to_ptr` function. I assume you mean `Box::into_raw`? I agree that might be a bit cleaner, but it would require a breaking change to public API (the `IntoOpaque` trait), and the current method works ok.
