### ISSUE TITLE
rdkafka-sys error: the trait `Copy` may not be implemented for this type

### ISSUE THREAD

**Issue by jerry73204** [fede1024/rust-rdkafka#148]
I encountered this error when building the master branch. It seems a [bindgen issue](https://github.com/rust-lang/rust-bindgen/issues/458) is relevant.

```
error[E0204]: the trait `Copy` may not be implemented for this type
    --> /path/to/crate/target/debug/build/rdkafka-sys-7db474a7fb7f90d0/out/bindings.rs:3460:17
     |
3460 | #[derive(Debug, Copy, Clone)]
     |                 ^^^^
...
3465 |     pub __cmsg_data: __IncompleteArrayField<::std::os::raw::c_uchar>,
     |     ---------------------------------------------------------------- this field does not implement `Copy`

```

**Comment by sd2k** [comment]
FYI @jerry73204 I've managed to fix this by bumping bindgen from `0.49.2` to `0.51.1` in rdkafka-sys/Cargo.toml.

**Comment by jerry73204** [comment]
Good work. It fixes this issue. Besides, @sd2k  could you remove the `=` version prefix for futures-review in your `Cargo.toml`? That conflicts with update-to-date tokio.

**Comment by sd2k** [comment]
@jerry73204 I guess you meant in the std-future branch; just pushed an update without the `=` version pin.
