### ISSUE TITLE
Starting consumer at offset given by distance from end

### ISSUE THREAD

**Issue by hlb8122** [fede1024/rust-rdkafka#156]
I want to start a consumer on a partition/topic given by an offset x from the end.

`Offset::Offset(-x)` does not seem to work here.

How is this possible please?

**Comment by benesch** [comment]
There isn't a dedicated API for this, I'm afraid. (It's a rather uncommon operation.) I think you'd want to do the same thing that this StackOverflow post suggests for the Java API: https://github.com/fede1024/rust-rdkafka/issues/156.

Basically, subscribe to a topic, seek to the end, query the [position](https://docs.rs/rdkafka/0.21.0/rdkafka/consumer/trait.Consumer.html?search=#method.position), subtract the desired number of records, and then seek to that offset. Now that I look at it, I think we need to expose the `seek` method that rdkafka provides—unless you're content to manually assign topics/partitions rather than subscribing? Where API are you currently passing `Offset::Offset` to?

**Comment by hlb8122** [comment]
Thanks for the reply.

I think you mis-pasted the StackOverflow URL but I know the one you're on about. I attempted this method and the problem I found was that when I queried the position the offset I receive is `Offset::End` rather than an actual integer I can subtract from. My memory is a little fuzzy though.

> Now that I look at it, I think we need to expose the seek method that rdkafka provides—unless you're content to manually assign topics/partitions rather than subscribing?

So this also something I think would be very nice because at the moment I have to grab the TopicList, edit it and then reassign it which seems heavy-handed.

**Comment by benesch** [comment]
> I think you mis-pasted the StackOverflow URL but I know the one you're on about.

Oops, thanks. I've updated my earlier comment with the correct link.

> I attempted this method and the problem I found was that when I queried the position the offset I receive is `Offset::End` rather than an actual integer I can subtract from. My memory is a little fuzzy though.

Ok, I was able to reproduce this; the position method will return `Offset::Invalid` until you read at least one message from that partition. I think this is just a difference between librdkafka and the Java API.

What you can do instead is use [`Consumer::fetch_watermarks`](https://docs.rs/rdkafka/0.21.0/rdkafka/consumer/trait.Consumer.html#method.fetch_watermarks), which queries the broker for its earliest and latest offsets for a given topic partition. Then you can subtract _n_ from the high watermark and begin consuming from there.

> > Now that I look at it, I think we need to expose the seek method that rdkafka provides—unless you're content to manually assign topics/partitions rather than subscribing?
> 
> So this also something I think would be very nice because at the moment I have to grab the TopicList, edit it and then reassign it which seems heavy-handed.

Ok, let me look into this.

**Comment by benesch** [comment]
I've opened a PR to add `Consumer::seek`: #172. Unfortunately I don't think it's going to be very helpful for you, as librdkafka requires that your consumer is active before you call seek... and there's no good way to determine when your consumer is active besides waiting for a rebalance callback.

So, to summarize, I think your best bet is to use `Consumer::fetch_watermarks` to find the latest offset for every partition that you care about, and then manually call `Consumer::assign` with `high_watermark - n`. Let me know if that doesn't work out for some reason!

**Comment by marccarre** [comment]
@hlb8122, did you manage to make this work? 🤔  If so, mind sharing a short example? 🙇🏻 
@benesch, I tried a few approaches but always ended up with an error, e.g. `Seek error: Local: Erroneous state`. Any further advice?

Given this observation:

> librdkafka requires that your consumer is active before you call seek... and there's no good way to determine when your consumer is active besides waiting for a rebalance callback.

and posts like [this one](https://stackoverflow.com/q/73463623/1328979), I also tried leveraging `ConsumerContext`'s callbacks with something like:

```rust
struct ResettableConsumerContext {
    topic: String,
    offset: i64,
}

impl ClientContext for ResettableConsumerContext {}

impl ConsumerContext for ResettableConsumerContext {
    fn post_rebalance<'a>(&self, rebalance: &Rebalance<'a>) {
        match rebalance {
            Rebalance::Assign(list) => {
                for mut tp in list.elements_for_topic(&self.topic) {
                    info!(
                        topic = tp.topic(),
                        partition = tp.partition(),
                        "Topic-partition at offset: {:?}",
                        tp.offset()
                    );
                    match tp.set_offset(Offset::Offset(self.offset)) {
                        Ok(_) => info!(
                            topic = tp.topic(),
                            partition = tp.partition(),
                            "Successfully set topic-partition to offset: {:?}",
                            self.offset
                        ),
                        Err(e) => error!("Kafka error on post-rebalance: {e}"),
                    }
                }
            }
            Rebalance::Revoke(a) => info!("Rebalance revoke: {:?}", a),
            Rebalance::Error(e) => error!("Rebalance error: {e}"),
        }
    }
}
```

but this did _not_ have the expected effect of rewinding back the consumer at the provided offset.

Disclaimer: still learning Kafka and not deeply familiar with all of Kafka's concepts and internals. Some of the above may be completely off, as it was mostly a shot in the dark.

**Comment by alyahmedaly** [comment]
@marccarre did you manage todo it in the end?

**Comment by marccarre** [comment]
@alyahmedaly, no, I don't think so. I eventually took a different approach for my use case and didn't use Kafka.

**Comment by alyahmedaly** [comment]
after asking you I managed to implement it but I had to use the master branch as in master to have access to the consumer and you can call seek partitions
