### ISSUE TITLE
Any plan to support librdkafka v1.2.1 ?

### ISSUE THREAD

**Issue by Andy320** [fede1024/rust-rdkafka#157]
librdkafka has been moved to v1.2.1, any plan to catch it up?

**Comment by gklijs** [comment]
They move fast. There will be some catch up in time. Anything in particular that's fixed/added?

**Comment by gklijs** [comment]
For the producer it was part of 1.0.0 release, and indeed they where planning to add some stuff for the consumer as well. Main thing of the 1.2.0 was indeed the transaction aware consumers. https://github.com/edenhill/librdkafka/releases. But first https://github.com/fede1024/rust-rdkafka/issues/146 needs to be finished..

**Comment by benesch** [comment]
I have a PR out for this (#154), but we need @flavray or @fede1024 to give their stamp of approval.

**Comment by benesch** [comment]
#154 is in! Closing this out.
