### ISSUE TITLE
Link errors when targeting musl

### ISSUE THREAD

**Issue by sebcrozet** [fede1024/rust-rdkafka#170]
Hi! I'm currently failing to build a fully static binary that depends on `rdkafka` due to some link errors. I'm using the docker container [ekidd/rust-musl-builder](https://hub.docker.com/r/ekidd/rust-musl-builder/) (latest image) as my build environment. Here is a minimal reproducer:

```bash
git clone https://github.com/sebcrozet/librdkafka-test.git
cd librdkafka-test
docker run --rm -it -v `pwd`:/home/rust/src ekidd/rust-musl-builder cargo run
```

The compilation itself succeeds but the link stage fails with several undefined reference errors like:

```
/home/rust/src/target/x86_64-unknown-linux-musl/debug/deps/librdkafka_sys-1a1ad609a66e2d0b.rlib(rdvarint.o): In function `fprintf':
/usr/include/x86_64-linux-gnu/bits/stdio2.h:97: undefined reference to `__fprintf_chk'
/usr/include/x86_64-linux-gnu/bits/stdio2.h:97: undefined reference to `__fprintf_chk'
/usr/include/x86_64-linux-gnu/bits/stdio2.h:97: undefined reference to `__fprintf_chk'
/usr/include/x86_64-linux-gnu/bits/stdio2.h:97: undefined reference to `__fprintf_chk'
/usr/include/x86_64-linux-gnu/bits/stdio2.h:97: undefined reference to `__fprintf_chk'
```
See the full listing [there](https://pastebin.com/tcyyzbEA).

Any help to fix this would be great! Is this an issue with the way `rdkafka-sys` handles its native dependency?

**Comment by sebcrozet** [comment]
It turns out this issue is a duplicate of #88 so I'm closing this.

**Comment by benesch** [comment]
FYI I just verified that the workaround suggested in #88 (using the CMake build) works by running

    docker run --rm -it -v `pwd`:/home/rust/src ekidd/rust-musl-builder cargo run --features=rdkafka/cmake_build

**Comment by sebcrozet** [comment]
@benesch Thank you for the workaround! I confirm enabling the `cmake_build` feature solves the problem in my setting too.

**Comment by andreworg** [comment]
possibly related: https://github.com/fede1024/rust-rdkafka -> https://github.com/fede1024/rust-rdkafka/issues/88
