### ISSUE TITLE
release: 0.22

### ISSUE THREAD

**Issue by igozali** [fede1024/rust-rdkafka#179]
Hi there,

Thanks for maintaining this awesome library. I was just wondering when the next release that supports the `AdminClient` (which I see is already in `master`) is going to happen?

If it's still going to take a while, is there a workaround for using the `AdminClient` in the library? I was planning to just point to some commit in master in my `Cargo.toml`, but I'm quite new to Rust and not sure if that's acceptable.

Thank you and apologies for the basic question!

**Comment by benesch** [comment]
No, it's a totally valid question! We haven't answered the question anywhere else, as far as I can remember.

The short answer is: soon! I don't have the power to release this library (that lies with @fede1024), so it's ultimately up to him. But perhaps we can shoot for this upcoming weekend? There are a few outstanding build system issues I'd like to resolve before pulling the trigger on the next release.

**Comment by benesch** [comment]
> If it's still going to take a while, is there a workaround for using the AdminClient in the library? I was planning to just point to some commit in master in my Cargo.toml, but I'm quite new to Rust and not sure if that's acceptable.

If you're releasing a library to crates.io, it's best practice not to rely on unpublished crates. If it's your own personal project, then you are of course free to do whatever you like!

**Comment by benesch** [comment]
> If it's still going to take a while, is there a workaround for using the AdminClient in the library? I was planning to just point to some commit in master in my Cargo.toml, but I'm quite new to Rust and not sure if that's acceptable.

If you're releasing a library to crates.io, it's best practice not to rely on unpublished crates. If it's your own personal project, then you are of course free to do whatever you like!

**Comment by igozali** [comment]
Thanks for the insight! I'll look forward to the next release, then.

**Comment by fede1024** [comment]
Happy to release a new version next weekend. It has been ages since the last release!

**Comment by gklijs** [comment]
Don't forget to make sure the versions of librdkafka are correct in the readme, they are currently outdated.

**Comment by benesch** [comment]
Ok, @fede1024, things are ready!

**Comment by benesch** [comment]
v0.22 has been released!
