### ISSUE TITLE
no method named `wait` found for type `rdkafka::consumer::stream_consumer::MessageStream<'_, utils::structs::CustomContext>` in the current scope

### ISSUE THREAD

**Issue by dawid-nowak** [fede1024/rust-rdkafka#180]
Hey;
I think the root cause of the problem is similar to "Example doesn't work with futures 0.2.0 #84".
I am using futures 3.1. 
Would you know if/when rdkafka will migrate to new version of futures.
Cheers

**Comment by benesch** [comment]
Soon! See #143. I'd like to get a release out with the old version of futures this weekend, and then hopefully we can upgrade to async/await/std::future in the weeks after that.

**Comment by dawid-nowak** [comment]
Thanks for good news. Really looking forward to it ! If you need any help let me know.
