### ISSUE TITLE
No docs for 0.22

### ISSUE THREAD

**Issue by jasonmartens** [fede1024/rust-rdkafka#185]
Looks like they failed to build? Also, I can't find a simple example of how to use the library, is there one and I'm missing it?

**Comment by benesch** [comment]
Gah, will look into it. Thanks for the note!

There are examples of both a [simple consumer](https://github.com/fede1024/rust-rdkafka/blob/master/examples/simple_consumer.rs) and [simple producer](https://github.com/fede1024/rust-rdkafka/blob/master/examples/simple_producer.rs).

**Comment by kamek-pf** [comment]
Btw, what's described in the `asynchronous_processing` example doesn't work with the currently published version of the lib:
```

55 |         .try_for_each(|message| {
   |          ^^^^^^^^^^^^ method not found in `rdkafka::consumer::stream_consumer::MessageStream<'_, rdkafka::consumer::DefaultConsumerContext>`
   |
   = note: the method `try_for_each` exists but the following trait bounds were not satisfied:
           `&mut rdkafka::consumer::stream_consumer::MessageStream<'_, rdkafka::consumer::DefaultConsumerContext> : futures_util::stream::try_stream::TryStreamExt`
           `&rdkafka::consumer::stream_consumer::MessageStream<'_, rdkafka::consumer::DefaultConsumerContext> : futures_util::stream::try_stream::TryStreamExt`
           `rdkafka::consumer::stream_consumer::MessageStream<'_, rdkafka::consumer::DefaultConsumerContext> : futures_util::stream::try_stream::TryStreamExt`

error: aborting due to previous error
```

Using current master seems to work, but I got confused for a little while

**Comment by benesch** [comment]
> Using current master seems to work, but I got confused for a little while.

Yes, sorry, master is currently upgraded to support async/await, but the latest release is not. I'll add a note to the README about this fact.

**Comment by fusillicode** [comment]
Sorry for bumping in, but even with if I access the doc through the links from the 0.22 READ.me I still get any doc :(

If I use the latest master version, i.e. `rdkafka = { git = "https://github.com/fede1024/rust-rdkafka", rev = "f5664abae3f6e6e82380b95f2bce50b95c52b201" }` the simple consumer example doesn't work (https://github.com/fede1024/rust-rdkafka/blob/master/examples/simple_consumer.rs)

```
error[E0432]: unresolved import `futures`
 --> src/main.rs:7:5
  |
7 | use futures::StreamExt;
  |     ^^^^^^^ use of undeclared type or module `futures`

error[E0433]: failed to resolve: use of undeclared type or module `rdsys`
  --> src/main.rs:32:24
   |
32 |         _offsets: *mut rdsys::RDKafkaTopicPartitionList,
   |                        ^^^^^ use of undeclared type or module `rdsys`

error[E0599]: no method named `next` found for type `rdkafka::consumer::MessageStream<'_, CustomContext>` in the current scope
   --> src/main.rs:103:46
    |
103 |     while let Some(message) = message_stream.next().await {
    |                                              ^^^^ method not found in `rdkafka::consumer::MessageStream<'_, CustomContext>`
    |
    = help: items from traits can only be used if the trait is in scope
help: the following trait is implemented but not in scope; perhaps add a `use` for it:
    |
6   | use futures_util::stream::stream::StreamExt;
    |

error: aborting due to 3 previous errors

Some errors have detailed explanations: E0432, E0433, E0599.
For more information about an error, try `rustc --explain E0432`.
error: could not compile `read-side-producerst`.

To learn more, run the command again with --verbose.
```

**Comment by benesch** [comment]
@fusillicode you'll need to declare a dependency on the `futures` crate in your Cargo.toml:

```toml
[dependencies]
futures = "0.3.0"
```

**Comment by fusillicode** [comment]
@benesch thanks a lot for the quick reply 🙇 

Unfortunately with `futures = "0.3.0"`, ` for message in message_stream.next().await {` breaks with:

```
   Compiling read-side-producerst v0.1.0 (/Users/gianlu/data/dev/credimi/read-side-producerst/read-side-producerst)
error[E0599]: no method named `next` found for type `rdkafka::consumer::MessageStream<'_, CustomContext>` in the current scope
   --> src/main.rs:105:35
    |
105 |     for message in message_stream.next().await {
    |                                   ^^^^ method not found in `rdkafka::consumer::MessageStream<'_, CustomContext>`
    |
    = note: the method `next` exists but the following trait bounds were not satisfied:
            `rdkafka::consumer::MessageStream<'_, CustomContext> : futures::StreamExt`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0599`.
error: could not compile `read-side-producerst`.

To learn more, run the command again with --verbose.
```

However with `futures = "0.1.21"` and `for message in message_stream.wait() {` it compiles.

Unfortunately it seems that I can't get any message from the brokers 🤨

**Comment by benesch** [comment]
You need `futures = "0.3"` with rdkafka's latest master, or `futures = "0.1"` with rdkafka's latest release (v0.22). If compilation is succeeding with futures 0.1, then I assume you're using v0.22, not master, and so it makes sense that you need to call the futures 0.1 `.wait()` API, and not the new native async/await keywords.

**Comment by fusillicode** [comment]
@benesch ok now everything it's clear, thanks really a lot for the support 🙇

**Comment by kamek-pf** [comment]
@benesch how far along are you in the futures 0.3 upgrade ? I think this is the last dependency preventing me from updating one of our projects, maybe I can help ?

**Comment by benesch** [comment]
@kamek-pf thanks for the offer, but the upgrade to async/await/futures 0.3/tokio 0.2 is already complete on master! v0.23 should be released within a few days, but you can depend directly on master in the meantime.

**Comment by benesch** [comment]
The docs issue is finally sorted out with 0.23.1. Thanks for your patience, folks!

**Comment by martinezger** [comment]
I know this could be out of topic, I'm a beginner rust developer and I was stuck with the
```
try_for_each(|borrowed_message| {
    |^^^^^^^^^^^^ method not found in `MessageStream<'_>
```
I solved adding `use futures::TryStreamExt;`  

Just a help to others beginner that could fall in this thread.
