### ISSUE TITLE
`BorrowedMessage` should be `Send`, maybe `Sync`.

### ISSUE THREAD

**Issue by nate-onesignal** [fede1024/rust-rdkafka#189]
A `rdkafka::message::BorrowedMessage` is `!Send` and `!Sync` because it holds a raw pointer to the `rdkafka_sys` structure. I believe that the structure should be `Send`, and possibly `Sync`, because according to the RDKafka docs, the API is completely thread-safe. It is posted in the rdkafka FAQ: https://github.com/edenhill/librdkafka/wiki/FAQ#is-the-library-thread-safe. 

> Yes, librdkafka is completely thread-safe (unless otherwise noted in the API documentation). Any API, short of the destructor functions, may be called at any time from any thread. The common restrictions of object destruction still applies (e.g., you must not call rd_kafka_destroy() while another thread is calling rd_kafka_poll() or similar).

Since rust's static memory guarantees can ensure that the lifetime of the borrowed message will never outlive the consumer that it came from, it should be safe to send it across threads as long as the lifetimes are respected.

This is currently preventing me from using `tokio::spawn` to spawn multiple workers that each consume messages.

**Comment by benesch** [comment]
Hmm, I think you're right. But I'm not sure this would solve your problem! How would you send the reference across a thread boundary? Rust's borrow checker doesn't work across threads, unless you're using something like crossbeam's scoped threads—and it sounds like you're using `tokio::spawn`, which, like `std::thread::spawn`, requires `'static`.

Have you tried just copying the data via `detach`? There's an example here: https://github.com/fede1024/rust-rdkafka/blob/4b51170bdad219c173dc82b75b4b3cefcfe55209/examples/asynchronous_processing.rs#L70

**Comment by nate-onesignal** [comment]
I have not tried detaching the message. I don't want to send the message as a `'static` to a different thread, but losing the `Send` requirement means that if an `async fn/block` holds a message reference across `.await` points, the future it generates will be `!Send`. For example, this fails to compile:

```
use futures::compat::*;
use futures::stream::*;
use rdkafka::config::ClientConfig;
use rdkafka::consumer::StreamConsumer;
use rdkafka::message::Message;

#[tokio::main]
async fn main() {
    tokio::spawn(run_consumer()).await.unwrap();
}

async fn run_consumer() {
    let consumer: StreamConsumer = ClientConfig::new()
        /* setup code */
        .create()
        .unwrap();

    let mut stream = consumer.start().compat();

    while let Some(Ok(Ok(msg))) = stream.next().await {
        let bytes = msg.payload_view::<[u8]>().unwrap().unwrap().to_vec();

        do_something_with_bytes(&bytes).await;
    }
}

async fn do_something_with_bytes(bytes: &[u8]) {
    println!("{:?}", bytes);
}
```

With the following dependency versions:

```
tokio = {version="0.2", features=["full"]}
rdkafka = "0.17"
futures = {version = "0.3", features = ["compat"]}
```

Because the future generated by `run_consumer` is `!Send`. I solved this with a wrapper around the Stream:

```
use futures::stream::*;
use futures::task::*;
use rdkafka::error::KafkaResult;
use rdkafka::message::{BorrowedMessage, Message, Timestamp};
use std::marker::Unpin;
use std::pin::Pin;

type Value<'a> = Result<KafkaResult<BorrowedMessage<'a>>, ()>;

pub struct SendMessage<'a>(BorrowedMessage<'a>);

unsafe impl<'a> Send for SendMessage<'a> {}

pub struct KafkaSendStream<'a, S>
where
    S: Stream<Item = Value<'a>>,
{
    stream: S,
}

impl<'a, S> KafkaSendStream<'a, S>
where
    S: Stream<Item = Value<'a>>,
{
    pub fn new(stream: S) -> Self {
        Self { stream }
    }
}

impl<'a, S> Stream for KafkaSendStream<'a, S>
where
    S: Stream<Item = Value<'a>> + Unpin,
{
    type Item = KafkaResult<SendMessage<'a>>;

    fn poll_next(mut self: Pin<&mut Self>, ctx: &mut Context) -> Poll<Option<Self::Item>> {
        match self.stream.poll_next_unpin(ctx) {
            Poll::Ready(Some(value)) => Poll::Ready(Some(value.unwrap().map(|v| SendMessage(v)))),
            Poll::Ready(None) => Poll::Ready(None),
            Poll::Pending => Poll::Pending,
        }
    }
}

impl<'a> Message for SendMessage<'a> {
    type Headers = <BorrowedMessage<'a> as Message>::Headers;

    fn key(&self) -> Option<&[u8]> {
        self.0.key()
    }

    fn payload(&self) -> Option<&[u8]> {
        self.0.payload()
    }

    fn topic(&self) -> &str {
        self.0.topic()
    }

    fn partition(&self) -> i32 {
        self.0.partition()
    }

    fn offset(&self) -> i64 {
        self.0.offset()
    }

    fn timestamp(&self) -> Timestamp {
        self.0.timestamp()
    }

    fn headers(&self) -> Option<&Self::Headers> {
        self.0.headers()
    }
}
```

and using it to wrap my stream:

```
use futures::compat::*;
use futures::stream::*;
use rdkafka::config::ClientConfig;
use rdkafka::consumer::StreamConsumer;
use rdkafka::message::Message;

mod stream;

#[tokio::main]
async fn main() {
    tokio::spawn(run_consumer()).await.unwrap();
}

async fn run_consumer() {
    let consumer: StreamConsumer = ClientConfig::new()
        /* setup code */
        .create()
        .unwrap();

    let mut stream = stream::KafkaSendStream::new(consumer.start().compat());

    while let Some(Ok(msg)) = stream.next().await {
        let bytes = msg.payload_view::<[u8]>().unwrap().unwrap().to_vec();

        do_something_with_bytes(&bytes).await;
    }
}

async fn do_something_with_bytes(bytes: &[u8]) {
    println!("{:?}", bytes);
}
```

But it would be nice if I did not have to do this wrapping myself.

**Comment by benesch** [comment]
Oh, I see! This is an exciting new possibility from async/await. I've opened #190 with the change, and and adjustment to one of the examples that requires the change. Thanks for posting the code sample—that helps a lot!

By the way, you're using an ancient version of rdkafka. Any particular reason why? The latest tip of master supports async/await natively, and will be released as 0.23 soon. And there are a bunch of bug fixes in the current stable version (0.22) too. See also the known issues with the non-CMake build system: https://github.com/fede1024/rust-rdkafka/blob/master/rdkafka-sys/README.md#known-issues.

**Comment by nate-onesignal** [comment]
We just haven't had the opportunity to do the upgrade yet. We have a lot of projects that use rdkafka-rust, and we're working on transitioning them to futures-0.3, and tokio-0.2. Maybe we can add the rdkafka-0.23 upgrade to that list too!

**Comment by benesch** [comment]
Sounds good! Just wanted to make sure there wasn’t something particularly painful about the upgrade path.
