### ISSUE TITLE
Should `OwnedHeaders` be Sync?

### ISSUE THREAD

**Issue by sd2k** [fede1024/rust-rdkafka#200]
Similar to #189 - could `OwnedHeaders` be `Sync` as well as `Send`?

The lack of `Sync` on `OwnedHeaders` means that an `OwnedMessage` is also `!Sync`, so it can't be easily used with async/await for the same reasons identified in #189 for `BorrowedMessage`.

**Comment by benesch** [comment]
Yep, thanks!
