### ISSUE TITLE
Dynamic subscribe/unubscribe per topic??

### ISSUE THREAD

**Issue by dawid-nowak** [fede1024/rust-rdkafka#216]
Hello;
I was wondering if my understaning of the API is correct:
1. i can subscribe to topics at any time. I could call consumer.subscribe for topic A,B and then again for topic C. 
2. unsubscribe doesn't take any inputs so I believe my consumer would unsubscribe from all topics? 
3. is there any way to unsubscribe from just one topic ?

Ideally in my case the sequence would be:
1. consumer.subscribe (A)
2. consumer.subscribe (B)
... some events for A and B
3. consumer.unsubscribe(A)
... some events for B only

Best regards

**Comment by benesch** [comment]
`subscribe` doesn't add a list of topics to the set of subscribed topics—it force-sets the set of subscribed topics. So `subscribe(a); subscribe(b)` will result in a subscription only on topic "b." You can query the current subscription set with this method: https://docs.rs/rdkafka/0.23.1/rdkafka/consumer/trait.Consumer.html#method.subscription

So the API that you're looking for already exists: `subscribe([a]); subscribe([a, b]); subscribe([a])`. `unsubscribe` is just shorthand for `subscribe([])`.

Let me know if you have trouble!

**Comment by dawid-nowak** [comment]
hey @benesch 
thanks for your reply, i was sort of looking for something where I could dynamically connect/disconnect to/from a topic without having to re-subscribe all other topics.

so for example 
subscribe(a) 
application gets messages for topic a
subscribe(b) 
application gets messages for topic a and b
unsubscribe(a)
application gets messages only for  b

with you explanation and Kafka documentation I don't think that will work. Indeed the only option seems to be a following sequence :
subscribe(a) -> messages for a
subscribe(a,b) -> messages for a and b
unsubscribe -> no messages
subscriba(A) -> messages for a

**Comment by benesch** [comment]
I believe this should work?

subscribe([a]) -> messages for a
subscribe([a, b]) -> messages for a and b
subscribe([a]) -> messages for a

I.e., the call to unsubscribe is unnecessary as the last call to subscribe([a]) implicitly unsubscribes b.

**Comment by dawid-nowak** [comment]
Cool, I will give it a go. Thanks

**Comment by benesch** [comment]
👍 feel free to file another more specific issue if something goes wrong!
