### ISSUE TITLE
BaseRecord timestamp

### ISSUE THREAD

**Issue by justmike2000** [fede1024/rust-rdkafka#217]
It would be wonderful if both the documentation and src comment mentioned that the BaseRecord timestamp function that takes an i64 parameter mentions that the function parameter expects milliseconds.

**Comment by benesch** [comment]
Sure! Can I talk you into submitting a PR?

**Comment by justmike2000** [comment]
https://github.com/fede1024/rust-rdkafka/pull/218

**Comment by benesch** [comment]
Fixed in #218.
