### ISSUE TITLE
Windowing statistics do not record percentile information

### ISSUE THREAD

**Issue by nate-onesignal** [fede1024/rust-rdkafka#229]
Rdkafka 1.3.0 reports percentile information for window statistics: https://github.com/edenhill/librdkafka/blob/v1.3.0/STATISTICS.md#window-stats

This information should be deserialized in the `Window` struct so that it is available to clients interested in it. https://github.com/fede1024/rust-rdkafka/blob/master/src/statistics.rs#L58

**Comment by benesch** [comment]
Can I interest you in submitting a PR?

**Comment by nate-onesignal** [comment]
Thanks for your patience, but you have succeeded in interesting me in a PR.
