### ISSUE TITLE
FutureProducer should have a working ProducerContext (or none at all)

### ISSUE THREAD

**Issue by thijsc** [fede1024/rust-rdkafka#23]
From @fede1024 in #22:

> The way the FutureProducer allows to specify a ProducerContext is very confusing at the moment, since the only method currently available in the trait is not actually executed (since it is used by the FutureProducer itself). I think we should remove this test, since it is a bit misleading.
>
> I'll update the FutureProducer to use a different trait instead of ProducerContext (or nothing at all).

**Comment by fede1024** [comment]
Fixed in commit c3dbc575ffb050f4.
