### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by nylar** [fede1024/rust-rdkafka#247]
Has been a while since the last release (January).

**Comment by benesch** [comment]
Yep, it's on my radar. Thanks for the ping. We couldn't release with librdkafka 1.4.0 because it broke the Windows build. librdkafka 1.4.2 is in master, but I have a few outstanding PRs to get through first before the release. Hopefully we can get something shipped by this weekend, or mid-next week at the latest.

**Comment by benesch** [comment]
That timeline might slip a few days, actually. I have one outstanding PR (#260) that needs to land first, and then I'd like to let the dust settle for a minute.

If you have the time (or anyone else reading this issue), could you try upgrading to the latest Git master and letting me know if you have any issues? The bug fixes in this upcoming release required more invasive changes than usual and required some breaking changes, and I'd love to get a status report on those breaking changes.

**Comment by redbaron** [comment]
I think there might be a release blocker https://github.com/fede1024/rust-rdkafka/issues/264

**Comment by benesch** [comment]
Sorry about the big delay here. Things are ready to go from my perspective, so I've asked @fede1024 to cut the releases.

**Comment by nylar** [comment]
@benesch With #264 addressed, what's the preferred way of keeping a quiet consumer alive? I've noticed with some stuff I have wrapping this lib and the `asynchronous_processing` example it will exit after 5 minutes after no messages (which makes sense as that's what the max poll interval is set). I suppose setting this to a much higher value is a solution but doesn't sound like the most preferable option.

**Comment by benesch** [comment]
Ah, sorry @nylar, this was my big concern about #264. Quite frankly I'm not sure. Setting `max.poll.interval.ms` to infinity is not a bad option, but it does mean you'll miss out on the wedge detection that it provides. (Personally I don't think this wedge detection is very important, but it's not really my place to have an opinion on that.)

Ugh. Maybe this is just a legitimate bug in the new design of the `StreamConsumer`. Thanks for raising.

**Comment by nylar** [comment]
Are we missing some background thread/future that is meant to be sending heartbeat requests in the case of long gaps between successful calls of `poll_next`?

**Comment by benesch** [comment]
Yeah, exactly. I think #276 will do the trick.

**Comment by nylar** [comment]
Tested your branch and no longer seeing the apps terminate after the max poll interval is reached. :tada:

**Comment by benesch** [comment]
Glad to hear it! Thanks very much for catching that pre-release.

**Comment by benesch** [comment]
0.24 is released! 🎉
