### ISSUE TITLE
Reliable segfault using ProducerContext + BaseProducer + mutexes

### ISSUE THREAD

**Issue by Roguelazer** [fede1024/rust-rdkafka#25]
I'm trying to set up BaseProducer to send delivery reports on a MPSC channel, and I'm getting reliable segfaults. Based on the core dump (which is deep within Rust's `std::sync::Mutex`), it appears that the `ProducerContext` might be being copied without calling `.clone()` and somehow corrupting the mutex inside.

I put a small reproducer up at https://github.com/Roguelazer/rdkafka_mpsc_test/blob/master/src/main.rs if that's helpful.

Any thoughts?

**Comment by thijsc** [comment]
Looks like the same issue I reproduced in #22. So I think this might mean custom contexts are broken for the `BaseProducer` as well. This is also being discussed in #23.

**Comment by Roguelazer** [comment]
*facepalm*

This doesn't appear to break in the current `master` (my checkout was from my fork, whose master was behind). Perhaps 3a414227ae619954e1a07cf84107d9225a63222c fixed it?

**Comment by thijsc** [comment]
That's likely indeed.

**Comment by fede1024** [comment]
Yes i think it's another instance of the same bug, that affected both producers. The context was dropped multiple times leaving the mutex in an inconsistent state. Happy to see that it now works.
