### ISSUE TITLE
Batch processing support?

### ISSUE THREAD

**Issue by Arfey** [fede1024/rust-rdkafka#265]
Hi 🤚
I want to processing messages by batches but didn't find any examples or documentation about that.

I found:

```rust
let message = consumer.poll(None);

// or 

for message in consumer.iter() {

// or

for message in &consumer {
```

but didn't found examples if i want to get 10 or 50 messages if these exists. Could you tell if this is possible with rust-rdkafka? And if yes so give some references with examples, please.

**Comment by benesch** [comment]
Yes, it's possible. Just call `poll` in a loop until you have the desired number of messages, or use `take` on the iterator. Note that the iterator will block forever if unable to supply the number of messages you've requested, so you may prefer manually calling poll.

Here's an example of using `take()`:

https://github.com/fede1024/rust-rdkafka/blob/4ae9541aabd98d9d56d85621b36c356f6d171fed/tests/test_low_consumers.rs#L74-L88

**Comment by Arfey** [comment]
Yes, u are right.

```rust
let message = consumer.poll(Timeout::After(Duration::from_secs(1)));
```
I think that poll will block if don't receive messages but with Timeout parameter all work as I expected.

Thx so much.

**Comment by benesch** [comment]
Yep, exactly!
