### ISSUE TITLE
 librdkafka when to release version 1.4.2

### ISSUE THREAD

**Issue by yorkart** [fede1024/rust-rdkafka#270]
A problem encountered in version 1.3.1，So I want to upgrade and try to solved it.
 
[Error: Disconnected (after XYZms in state UP)]( https://github.com/confluentinc/confluent-kafka-go/issues/436)

**Comment by fanatid** [comment]
Related with #247

**Comment by benesch** [comment]
Yes, sorry, hopefully soon. Closing in favor of #247.
