### ISSUE TITLE
Fatal error?

### ISSUE THREAD

**Issue by Licenser** [fede1024/rust-rdkafka#279]
Hi,
we're seeing a rather odd error in the logs with rust-rdkafka:

```
Message production error: Fatal (Local: Fatal error)
```

And I'm not sure where to start investigating here, any ideas what could cause such an error?

**Comment by benesch** [comment]
Does #280 indicate you figured out what caused this? Or is it still a mystery? I'm afraid I don't have much to offer besides the upstream docs: https://github.com/edenhill/librdkafka/blob/master/INTRODUCTION.md#fatal-errors

Which is to say I believe it's related to use of transactional producers/consumers?

**Comment by Licenser** [comment]
It sadly is still a mystery, #280 allowed to identify if it's a fatal error and then restart the client as the docs suggest. But I'm not exactly sure how to call `rd_kafka_fatal_error` from within rust-rdkafka, perhaps it could be integrated with errors that are fatal? (or is it already and librdkafka only tells is "Local: Fatal error"?)

**Comment by benesch** [comment]
Yeah, I think the easiest solution is to introduce a `fatal_error` method on `Client` that calls `rd_kafka_fatal_error`. If you need something stat, you should be able to make an unsafe call to that function in the rdkafka-sys crate. You can get at the required pointer with [`Client::native_ptr`](https://docs.rs/rdkafka/0.23.1/rdkafka/client/struct.Client.html#method.native_ptr).

**Comment by Licenser** [comment]
Thanks for the pointer! I came up with the following, would that make sense as a function of Client? Happy to submit a PR with the API you prefer :)

```rust
unsafe fn get_fatal_error<C>(
    client: &rdkafka::client::Client<C>,
) -> Option<(rdkafka::types::RDKafkaRespErr, String)>
where
    C: rdkafka::ClientContext,
{
    const LEN: usize = 4096;
    let mut buf: [i8; LEN] = std::mem::MaybeUninit::uninit().assume_init();
    let client_ptr = client.native_ptr();

    let code = rdkafka_sys::bindings::rd_kafka_fatal_error(client_ptr, buf.as_mut_ptr(), LEN);
    if code == rdkafka::types::RDKafkaRespErr::RD_KAFKA_RESP_ERR_NO_ERROR {
        None
    } else {
        Some((code, rdkafka::util::cstr_to_owned(buf.as_ptr())))
    }
}
```

**Comment by benesch** [comment]
Yep, definitely. A 4k buffer looks a little large, and I'd like to avoid `MaybeUninit` if possible since this is unlikely to be a particularly hot function. (This is totally the right use case for `MaybeUninit`, but I find reasoning about its safety to be quite challenging.)

**Comment by benesch** [comment]
I'll try to toss up a PR later tonight.
