### ISSUE TITLE
Documentation of FutureProducer::send is unclear about result type

### ISSUE THREAD

**Issue by jfirebaugh** [fede1024/rust-rdkafka#283]
In the code, the result type of `FutureProducer::send` is declared as `OwnedDeliveryResult`, which has documentation about  the meaning of the members of the `(i32, i64)` tuple:

https://github.com/fede1024/rust-rdkafka/blob/770ac7419f9c2d0b8607a5614efc978dd1c6182b/src/producer/future_producer.rs#L128-L135

However, this type is not showing up in the [generated documentation](https://docs.rs/rdkafka/0.24.0/rdkafka/producer/future_producer/struct.FutureProducer.html#method.send), so it's difficult to figure out how to interpret the result:

![image](https://user-images.githubusercontent.com/98601/88982193-7c375480-d27c-11ea-9011-c9aeddf1a810.png)

**Comment by benesch** [comment]
Thanks very much for the report! Looks like we just need to `pub`-ify that type alias. Should be taken care of in #284.

**Comment by benesch** [comment]
Ok, looks pretty good to me now: https://fede1024.github.io/rust-rdkafka/rdkafka/producer/future_producer/struct.FutureProducer.html#method.send

Let me know if you have any lingering concerns! If not, it'll be on docs.rs with the next release. Thanks again!

**Comment by jfirebaugh** [comment]
Looks great, thank you!
