### ISSUE TITLE
Project needs maintainer

### ISSUE THREAD

**Issue by dead10ck** [fede1024/rust-rdkafka#285]
Unfortunately, I have not had time the last few years to continue maintenance of this project, nor has @xitep or @spicavigo. Please post here if you are interested in becoming a maintainer.

**Comment by benesch** [comment]
Did you mean to post this against https://github.com/spicavigo/kafka-rust? 😄

**Comment by dead10ck** [comment]
Oh my goodness, I'm so sorry, I alt-tabbed to the wrong page 🤦

**Comment by benesch** [comment]
No worries at all! I think kafka-rust is an awesome project, by the way—and I hope someone comes along to pick up the torch eventually! We get a lot of mileage over here by offloading most of the hard work to librdkafka, but given infinite time and money I think reimplementing everything in Rust is the way to go, both for memory safety and a cleaner async/await integration. (The current approach here of glueing async/await futures atop of rust-rdkafka works well enough, but it would be faster and more understandable internally if everything just used the Rust async/await stack.)
