### ISSUE TITLE
Overriding ClientContext::stats()?

### ISSUE THREAD

**Issue by durch** [fede1024/rust-rdkafka#295]
Hi folks, thank you for all the work that went into this crate.

I'm wondering what is the canonical way of overriding the `ClientContext::stats()` callback. I've tried `impl` a new trait with the `stats()` method for `StreamConsumerContext`, as I'm using the `StreamConsumer` but that did not have the same effect. 

My attempt at overriding: 

```rust
trait CustomStats {
    fn stats(&self, statistics: Statistics);
}

impl <T: ConsumerContext> CustomStats for StreamConsumerContext<T> {
    fn stats(&self, statistics: Statistics) {
            info!("Great success!")
    }
}
```

**Comment by benesch** [comment]
Er, you don't want to create a _new_ trait with an unrelated `stats` method. That's not going to work. You want to do something like this, where you implement the `stats` method of `ClientContext`:

https://github.com/fede1024/rust-rdkafka/blob/2901a4b9027c3cce6fcae48c124fe5296397704a/tests/utils.rs#L193-L214

In your case it would be something like:

```
impl<T> ClientContext for StreamConsumerContext<T> {
    fn stats(&self, statistics: Statistics) { /* ... */ }
}
```

though it is tough to be more specific without seeing the definition of `StreamConsumerContext`.

**Comment by durch** [comment]
@benesch thanks for the pointer, will take a stab at it

**Comment by durch** [comment]
The problem with that approach is that I can't `impl` anything to `StreamConsumerContext`: 
```
error[E0117]: only traits defined in the current crate can be implemented for arbitrary types
  --> src/main.rs:30:1
   |
30 | impl<T> ClientContext for StreamConsumerContext<T> {
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^------------------------
   | |                         |
   | |                         `rdkafka::consumer::stream_consumer::StreamConsumerContext` is not defined in the current crate
   | impl doesn't use only types from inside the current crate
   |
   = note: define and implement a trait or new type instead
```

So my only choice is actually implementing `ClientContext` for a new type, which I wanted to avoid :/

**Comment by durch** [comment]
Would you consider taking a PR that would redefine `stats` as taking in a `Fn()`. So that we can pass callbacks in there

**Comment by benesch** [comment]
Oh, I see. I thought `StreamConsumerContext` was a already a newtype in your project. I see now that it refers to the struct exported by this crate. The way rust-rdkafka is designed you are _intended_ to create a new type that implements `ClientContext`. Let me send you an example momentarily.

**Comment by benesch** [comment]
Something like this should work:

```rust
use rdkafka::client::ClientContext;
use rdkafka::config::{ClientConfig};
use rdkafka::consumer::stream_consumer::StreamConsumer;

struct CustomContext;

impl ClientContext for CustomContext {
     fn stats(&self, stats: Statistics) { 
         let stats_str = format!("{:?}", stats); 
         println!("Stats received: {} bytes", stats_str.len()); 
     } 
}

fn main() {
    let consumer: StreamConsumer<CustomContext> = ClientConfig::new().create_with_context(CustomContext);
}
```

You shouldn't need to interact with `StreamConsumerContext` at all yourself. It'll be automatically created on your behalf when you call `create_with_context`.

**Comment by durch** [comment]
Oh, I totally missed that I can just do a `CustomContext`, thank you!

**Comment by benesch** [comment]
You're welcome! It's definitely not the most obvious design, but seems to work well once folks figure it out.
