### ISSUE TITLE
New Release including #287

### ISSUE THREAD

**Issue by mfelsche** [fede1024/rust-rdkafka#299]
We depend on rdkafka in https://github.com/tremor-rs/tremor-runtime and would love to make use of #287 as it makes it possible for us to avoid having another explicit dependency to librdkafka-sys for getting fatal errors.

Unfortunately this change is not yet part of a release, and we would like to avoid pinning our dependency of rdkafka to a git tag.

Is there a release planned in the upcoming weeks? If not, would it make sense for you and not be too much effort to craft one containing #287 (and maybe other changes)?

It would be much appreciated! :)

**Comment by benesch** [comment]
Sorry, my time has been extremely limited lately. I'll do my best!

**Comment by gklijs** [comment]
Maybe a good idea to also update the librdkafka version, if release is almost due, https://github.com/edenhill/librdkafka/releases/tag/v1.5.3

**Comment by binarylogic** [comment]
@benesch we'd be happy to help here. We're blocked on solving a few issues over at https://github.com/timberio/vector due to the old librdkafka version. We could contribute an update to `librdkafka`, but I'm not sure how we could facilitate a release. Any ideas?

**Comment by benesch** [comment]
Sorry for the very long delay! I've finally processed the backlog of PRs necessary to ship a release. I want to validate the changes downstream in Materialize over the next few days, and then I'll ask @fede1024 to cut v0.25.0!

**Comment by benesch** [comment]
Actually, @binarylogic, I'll see about getting you a release of rdkafka-sys v1.5.3 _before_ v0.25.0 of rdkafka itself.

**Comment by gklijs** [comment]
@benesch, what is the current state? A new 1.6.0 version of librdkafka was just released. Not sure if it makes sense to include in the release and / or it needs many changes.

**Comment by benesch** [comment]
@gklijs the bump to librdkafka v1.6.0 is in master as of last night. I use [Materialize](https://github.com/MaterializeInc/materialize) as an integration test for librdkafka, but unfortunately the bump to librdkafka v1.6.0 has caused a test failure there that I haven't tracked down: https://github.com/MaterializeInc/materialize/pull/5478

It's not clear to me whether that's librdkafka's fault, rust-rdkafka's fault, or Materialize's fault. 

Separately, I don't actually have permission to release to crates.io—only @fede1024 does!

**Comment by benesch** [comment]
Seems like a librdkafka bug: https://github.com/edenhill/librdkafka/issues/3231

It's a pretty niche feature, so probably fine to proceed with the release. I'll get in touch with @fede1024.

**Comment by fede1024** [comment]
rdkafka 0.25.0 and librdkafka-sys 3.0.0+1.6.0 (containing librdkafka 1.6.0) have been published to crates.io

**Comment by benesch** [comment]
Thanks very much, @fede1024! And thanks everyone else for your patience. If you encounter any trouble, please send file issue reports!
