### ISSUE TITLE
Integration tests

### ISSUE THREAD

**Issue by fede1024** [fede1024/rust-rdkafka#30]
We currently have very simple integration test suite that cover a small subset of the library functionality.

We should have a Docker container based Kafka cluster, and run a series of integration tests on it. Ideally, all tests should run inside valgrind, to spot any eventual memory issue. All the tests should be executed automatically by Travis.

- [x] Integration tests for StreamConsumer
- [x] Integration tests for FutureProducer
- [x] Integration tests for BaseConsumer
- [x] Integration tests for BaseProducer
- [x] Integration tests for Metadata fetch 
- [x] Integration tests for Subscription
- [x] Run integration tests in Docker container
- [x] Run all tests inside Valgrind and analyze errors automatically
- [x] Run integration tests in travis
- [ ] Run integration tests against multiple Kafka versions

**Comment by xitep** [comment]
Over at [kafka-rust](https://github.com/spicavigo/kafka-rust/blob/master/tests/run-all-tests), @dead10ck managed to fully automate setting up and tearing down a kafka-broker for integration tests using docker and docker-compose. so far it works very well. @dead10ck is also continuing on this to cover a multi broker set-up for the tests. just thought, it might serve at least as an inspiration.

**Comment by fede1024** [comment]
Thanks! I'll definitely give a look. I actually have a basic implementation, based on [kafka-utils](https://github.com/Yelp/kafka-utils) (similar approach - docker compose running a kafka instance). I'm not sure we really need multi broker tests for this crate, given that the core of the protocol is already implemented and tested in librdkafka, and we're just wrapping it. I'll definitely look at the kafka-rust approach and see if it can help with our integration tests as well.
