### ISSUE TITLE
baseproducer with producercontext

### ISSUE THREAD

**Issue by capacman** [fede1024/rust-rdkafka#301]
Hi,
To resend failed messages i will use clientcontext with a vector(push failed ones). But when i look test_low_producers.rs i saw client context declared like:
```rust
#[derive(Clone)]
struct CollectingContext {
    stats: Arc<Mutex<Vec<Statistics>>>,
    results: Arc<Mutex<Vec<TestProducerDeliveryResult>>>,
}
```
In my case i will use baseproducer without any threading. Should i use mutex? Actually delivery method is called by the thread that make polling so i think even arc is not necessary in this case but clientcontext marked as sync and send. Is there any way to use baseproducer without any arc and mutex? I am new to rust so may be i am wrong. Thanks in advance.

**Comment by kuronyago** [comment]
"clientcontext marked as sync and send", so you able to use anything that provides this bound

**Comment by capacman** [comment]
Thank you. So can i use 
```rust
pub struct KafkaProducerContext {
    flags: RefCell<[u8; 2048]>,
}
unsafe impl Sync for KafkaProducerContext{}
```
above context since i will use baseproducer without any threading?

**Comment by kuronyago** [comment]
yeah, https://doc.rust-lang.org/std/cell/struct.RefCell.html#impl-Send

**Comment by capacman** [comment]
Thank you @kuronyago
