### ISSUE TITLE
Stopping Stream Consumer

### ISSUE THREAD

**Issue by deankarn** [fede1024/rust-rdkafka#304]
I was wonder if if there is a way to stop the `StreamConsumer` after calling `consumer.start()` so that the stream can stop by receiving a `None`.

I'm interested in this for graceful shutdown purposes. If anyone has worked out an example of how to do this that would also be great! 

Thanks in advance.

**Comment by scooter-dangle** [comment]
I'm curious to know whether you've tried using [`Consumer::pause`](https://docs.rs/rdkafka/0.24.0/rdkafka/consumer/trait.Consumer.html?search=#method.pause). (I haven't used it myself.)

**Comment by deankarn** [comment]
@scooter-dangle I can't remember of the top of my head, but my understanding is that pause will pause the stream but not return a None in order to shutdown and stop the while loop.

I've managed to get it working by using a `select!` over the while for now but it look a little ugly eg.
```rust
while let Some(message) = tokio::select! {
            msg = message_stream.next().compat() => msg,
            _ = cancel.changed() => {
                None
            },
        } {...}
```

**Comment by benesch** [comment]
Hey @deankarn, thanks for your interest in rust-rdkafka! Using a `select!` like that is actually exactly the right approach. rust-rdkafka doesn't really want to have an opinion on how one stops streams; instead you can use whatever `futures::Stream`-compatible combinators you like. 

I do have some tips, though! I like using `StreamExt::take_until` in conjunction with a oneshot channel to produce a stream that automatically returns `None` when the oneshot closes:

```rust
use futures::stream::StreamExt;
use tokio::sync::oneshot;

let (shutdown_trigger, shutdown_tripwire) = oneshot::channel();
let message_stream = message_stream.take_until(shutdown_tripwire);
while let Some(message) = message_stream.next().await {
    // Handle message.
}

// In another thread, drop `shutdown_trigger` when you're ready to terminate the loop.
```

If that's not flexible enough for your needs, I recommend looking into the [stream-cancel](https://docs.rs/stream-cancel/0.7.0/stream_cancel/) crate, which wraps this pattern up in a purpose-built API.

**Comment by benesch** [comment]
I'm going to close for now, but happy to entertain additional arguments about why this should live in rust-rdkafka instead of downstream!

**Comment by slvrtrn** [comment]
@benesch I am not sure that `take_until` works as intended in this case.
The predicate will be executed only when we encounter the next message in the stream. 
In other words, the application will stop only after receiving the next message, hanging until then.
