### ISSUE TITLE
Instantiating the producer causes latency

### ISSUE THREAD

**Issue by TheGlenn88** [fede1024/rust-rdkafka#305]
Hi,

New to Kafka and also pretty new to Rust, so apologies if the below is normal.

Adding the below lines

```rust
    let producer: &FutureProducer = &ClientConfig::new()
        .set("bootstrap.servers", brokers)
        .set("message.timeout.ms", "5000")
        .create()
        .expect("Producer creation error");
```

adds over 100ms to a page load in actix-web. Removing those lines, brings the page load to 2ms (it's not doing anything else).

The problem isn't the send operation, it's the creating the producer, assuming this is connecting to the Kafka server and what not, is there a way this can be improved?

I'm running Zookeeper, Kafka and this build locally on a 2020 i7 Macbook Pro.

See here.
https://github.com/TheGlenn88/queue-rs/blob/master/src/main.rs#L48

Thanks

**Comment by TheGlenn88** [comment]
After actually reading this out loud, would I be right in saying, if the producer is instantiated once the application is booted, then is passed into the request instead of it being instantiated on every request, that this would remove the latency? Similar to how Redis/Postgres connection pooling works?

**Comment by TheGlenn88** [comment]
I can confirm my last comment, passing the producer in removes virtually all latency. See expend_token function.

```rust
async fn expend_token(_req: HttpRequest, producer: web::Data<FutureProducer>) -> impl Responder {
    // TODO: Parse the token, extract the user, send a completed message to kafka for that user.

    // produce a kafka message
    let topic = "test";

    let delivery_status = producer
        .send(
            FutureRecord::to(topic)
                .payload(&format!("Message {}", "payload"))
                .key(&format!("Key {}", "key"))
                .headers(OwnedHeaders::new().add("header_key", "header_value")),
                Dur::from_secs(0),
        )
        .await;

        info!("Future completed. Result: {:?}", delivery_status);
        HttpResponse::Ok()
            .finish()
}

#[actix_rt::main]
async fn main() -> std::io::Result<()> {
    let mut listenfd = ListenFd::from_env();

    let brokers = "localhost:9092";
    let producer: FutureProducer = ClientConfig::new()
        .set("bootstrap.servers", brokers)
        .set("message.timeout.ms", "5000")
        .create()
        .expect("Producer creation error");
    
    let producer = web::Data::new(producer);

    let mut server = HttpServer::new(move ||
        App::new()
        .route("/", web::get().to(index))
        .route("/check", web::get().to(check))
        .route("/expend", web::get().to(expend_token))
        .app_data(producer.clone())
    );

    server = if let Some(l) = listenfd.take_tcp_listener(0).unwrap() {
        server.listen(l)?
    } else {
        server.bind("127.0.0.1:8002")?
    };

    server.run().await
}
```

**Comment by benesch** [comment]
Yep, creating a new producer on every web request is unlikely to be a successful strategy. Your new approach sounds much better.
