### ISSUE TITLE
Can StreamConsumer retry connecting to kafka?

### ISSUE THREAD

**Issue by melonux** [fede1024/rust-rdkafka#322]
As mentioned in example code.

    consumer.subscribe(topic_list);  // consumer is a StreamConsumer 
    let stream_processor = self.consumer.start().try_for_each(|msg| {...});
    stream_processor.await.expect("stream processing failed");

Suppose the program starts normally and 1 hour later, kafka servers shutdown for 1 hour and then resume. Does StreamConsumer keep retrying connection to kakfa server? If not, how to do so? Thank you in advance.

**Comment by benesch** [comment]
Yes, it should. There are some configuration knobs you might need to tune, though. See https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md for details. Are you seeing something other than the behavior you desire?

**Comment by melonux** [comment]
thanks for the reply. so retry behavior is not defined in rust. it is implemented in librdkafka and controlled by `reconnect.backoff.ms` and `reconnect.backoff.max.ms` parameters. librdkafka will try to reconnect infinite times with backoff time interval. Am I right?

**Comment by benesch** [comment]
Yes, exactly!

**Comment by benesch** [comment]
Going to close this as resolved, but definitely feel free to file issues if you run into specific problems!
