### ISSUE TITLE
cargo build error "unresolved import `rdsys::types::RDKafkaError`"

### ISSUE THREAD

**Issue by sheepmen** [fede1024/rust-rdkafka#329]
unresolved import `rdsys::types::RDKafkaError`
  --> /home/x/.cargo/registry/src/github.com-1ecc6299db9ec823/rdkafka-0.24.0/src/error.rs:9:9
   |
 9 | pub use rdsys::types::RDKafkaError;
   |         ^^^^^^^^^^^^^^------------
   |         |             |
   |         |             help: a similar name exists in the module: `RDKafkaEvent`
   |         no `RDKafkaError` in `types`
 error[E0433]: failed to resolve: use of undeclared type `RDKafkaError`
    --> /home/x/.cargo/registry/src/github.com-1ecc6299db9ec823/rdkafka-0.24.0/src/admin.rs:524:9
     |
 524 |         RDKafkaError::NoError => Ok(()),
     |         ^^^^^^^^^^^^ use of undeclared type `RDKafkaError`
 error[E0433]: failed to resolve: use of undeclared type `RDKafkaError`
    --> /home/x/.cargo/registry/src/github.com-1ecc6299db9ec823/rdkafka-0.24.0/src/admin.rs:525:9

**Comment by mati865** [comment]
The error was caused by including breaking change: https://github.com/fede1024/rust-rdkafka/commit/e8b64b994895d1d8cdb9d076639f3dae6fcd495 in `rdkafka-sys 2.1.1+1.5.3` patch release: https://github.com/fede1024/rust-rdkafka/commit/f28f0fbc975fdf5033050f433c9a93666c2f7c7a

**Comment by bugadani** [comment]
Please don't release breaking changes as patch releases, it breaks stuff :)

**Comment by bugadani** [comment]
* The offending version must be yanked from crates.io.
 * There is a messy workaround: you can clone the repo, and use a cargo patch to point `rdkafka-sys` to an earlier commit, but it's a hassle.

**Comment by sheepmen** [comment]
> * The offending version must be yanked from crates.io.
> * You can use a cargo patch to point to an earlier commit that isn't broken...

thx！ i try to change cargo.toml to earlier commit

**Comment by benesch** [comment]
Ah, sorry about that, folks! This was my error for forgetting about the breaking change in rdkafka-sys. @fede1024 has yanked the version from crates.io, so `cargo update` should no longer break. We'll do a proper semver-major release of rdkafka-sys along with v0.25.0 of rdkafka.

**Comment by benesch** [comment]
Just for posterity, the intent here was to release a patch version of rdkafka-sys with the latest patch version of librdkafka (v1.5.3), _without_ the whole pile of breaking changes that is coming in rdkafka v0.25.0. But that has shaped up to be more trouble than it's worth, I'm afraid.
