### ISSUE TITLE
simple_consumer.rs example error during build

### ISSUE THREAD

**Issue by filippidis** [fede1024/rust-rdkafka#332]
I am a newcomer in rust and i am  trying  to compile the simple_consumer.rs example  as a standalone main code, **not** in the following way:
  cargo run --example <example_name> -- <example_args>

I receive the following error:
-----------------
error[E0599]: **no method named `recv` found for struct `StreamConsumer<CustomContext>**` in the current scope
  --> src/main.rs:61:24
   |
61 |         match consumer.recv().await {
   |                                      ^^^^ method not found in `StreamConsumer<CustomContext>`
--------
it follows my cargo.toml

[dependencies]
rdkafka = { version = "0.24", features = ["cmake-build"] }
futures = "0.3.0"
libc = "0.2.0"
log = "0.4.8"
serde = { version = "1.0.0", features = ["derive"] }
serde_derive = "1.0.0"
serde_json = "1.0.0"
slab = "0.4"
#tokio = { version = "1.0", features = ["rt", "time"], optional = true }
backoff = "0.1.5"
chrono = "0.4.0"
clap = "2.18.0"
env_logger = "0.7.1"
hdrhistogram = "7.0.0"
rand = "0.3.15"
regex = "1.1.6"
smol = "1.2.4"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread", "time"] }

thank you in advance

**Comment by benesch** [comment]
Ah, yes, there are some breaking changes on `master` that have not yet made it into a release. You can either use the [v0.24.0 example](https://github.com/fede1024/rust-rdkafka/blob/v0.24.0/examples/simple_consumer.rs) as a basis instead, or use a git dependency on the latest master:

```
rdkafka = { git = "https://github.com/fede1024/rust-rdkafka.git", features = ["cmake-build"] }
```
