### ISSUE TITLE
Can't compile rust-rdkafka under Windows 10.

### ISSUE THREAD

**Issue by CHCP** [fede1024/rust-rdkafka#336]
Hi there
I compiled rust-rdkafka under windows 10, but there are some errors I can't fix, would some one give me some help?  Thanks a lot.

Environment: Window 10, MSVC 2019 Edition, 
cargo: 1.48.0
rustup: 1.23.1
toolchain: "stable-x86_64-pc-windows-msvc", when I shift to toolchain "stable-x86_64-pc-windows-gnu" after install MinGW, there are the same errors.

I clone the rust-rdkafka source code, and run the example like this:
`
$ cargo run --example simple_consumer
   Compiling rdkafka-sys v2.0.0+1.4.2 (C:\job\5research\rust\rust-rdkafka\rdkafka-sys)
   Compiling toml v0.5.8
   Compiling futures-executor v0.3.9
   Compiling serde_json v1.0.61
   Compiling smol v0.1.18
error: failed to run custom build command for `rdkafka-sys v2.0.0+1.4.2 (C:\job\5research\rust\rust-rdkafka\rdkafka-sys)

Caused by:
  process didn't exit successfully: `C:\job\5research\rust\rust-rdkafka\target\debug\build\rdkafka-sys-ded254a674f25cb1\build-script-build` (exit code: 101)
  --- stdout
  Configuring librdkafka

  --- stderr
  Building and linking librdkafka statically
  Running command: "\\?\C:\job\5research\rust\rust-rdkafka\target\debug\build\rdkafka-sys-4a1680bace11386d\out\configure --disable-ssl --disable-gssapi --disable-zstd --disable-lz4-ext" in dir: C:\job\zerologix\5research\rust\rust-rdkafka\target\debug\build\rdkafka-sys-4a1680bace11386d\out
  thread 'main' panicked at 'Command failed with error: %1 is not a valid Win32 application. (os error 193)', rdkafka-sys\build.rs:36:19
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: build failed

`

It is same can't run command "configure", I don known how to continue.

**Comment by benesch** [comment]
Should work if you enable the `cmake-build` feature! It's not presently possible to build on Windows with the standard mklove build system.

**Comment by CHCP** [comment]
Hi @benesch :
  Thanks for your quick answer.

  I enable the `cmake-build` feature in another rust-rdkafka simple example, there are  another errors:

`
   Compiling rdkafka-sys v2.1.0+1.5.0
error: failed to run custom build command for `rdkafka-sys v2.1.0+1.5.0`

Caused by:
  process didn't exit successfully: `C:\job\zerologix\5research\rust\Kafka-Bombardier\target\debug\build\rdkafka-sys-ca073a3e406154b2\build-script-build` (exit code: 101)
  --- stdout
  Configuring and compiling librdkafka
  running: "cmake" "C:\\Users\\Gordon\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\rdkafka-sys-2.1.0+1.5.0\\librdkafka" "-G" "Visual Studio 16 2019" "-Thost=x64" "-Ax64" "-DRDKAFKA_BUILD_STATIC=1" "-DRDKAFKA_BUILD_TESTS=0" "-DRDKAFKA_BUILD_EXAMPLES=0" "-DCMAKE_INSTALL_LIBDIR=lib" "-DWITH_ZLIB=1" "-DWITH_SSL=0" "-DWITH_SASL=0" "-DWITH_ZSTD=0" "-DENABLE_LZ4_EXT=0" "-DCMAKE_INSTALL_PREFIX=C:\\job\\zerologix\\5research\\rust\\Kafka-Bombardier\\target\\debug\\build\\rdkafka-sys-af6385706f6b54df\\out" "-DCMAKE_C_FLAGS= -nologo -MD -Brepro" "-DCMAKE_C_FLAGS_DEBUG= -nologo -MD -Brepro" "-DCMAKE_CXX_FLAGS= -nologo -MD -Brepro" "-DCMAKE_CXX_FLAGS_DEBUG= -nologo -MD -Brepro" "-DCMAKE_ASM_FLAGS= -nologo -MD -Brepro" "-DCMAKE_ASM_FLAGS_DEBUG= -nologo -MD -Brepro" "-DCMAKE_BUILD_TYPE=Debug"

  --- stderr
  Building and linking librdkafka statically
  thread 'main' panicked at '
  failed to execute command: The system cannot find the file specified. (os error 2)
  is `cmake` not installed?

  build script failed, must exit now', C:\Users\Gordon\.cargo\registry\src\github.com-1ecc6299db9ec823\cmake-0.1.45\src\lib.rs:894:5
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: build failed

`

So rust-rdkafka can't be compiled on Windows10,  just wondering is it correct?

**Comment by benesch** [comment]
> So rust-rdkafka can't be compiled on Windows10, just wondering is it correct?

No, it definitely can. We test that it does in CI. You just need to install `cmake` as the error message suggests: https://cmake.org.

**Comment by CHCP** [comment]
Yes, It is works after I installed `cmake`.  Thanks for your help. @benesch

**Comment by benesch** [comment]
Excellent! Glad to hear it.
