### ISSUE TITLE
tokio 1.0 release

### ISSUE THREAD

**Issue by barkanido** [fede1024/rust-rdkafka#337]
Hey guys, any plans to cut a release with (already merged) support for tokio 1.0 ?

**Comment by kosta** [comment]
I think tokio 1.0 will be part of the next release, see #299

**Comment by benesch** [comment]
Yes, I promise it's coming soon! We're waiting on an upstream release of librdkafka v1.6.0. Our next release will include transactional producer support in addition to the Tokio v1.0 bump, so I want to make sure we pick up the pending transactional producer bugfixes: https://github.com/edenhill/librdkafka/pull/3227. 

I'm sorry it's taken so long to get this release shipped, but my time is extremely limited these days, and I think @fede1024's even more so.

**Comment by CHCP** [comment]
+1

Glad to see the new rdkafka release with Tokio 1.0，waiting...

**Comment by benesch** [comment]
Going to close this in favor of #299 so that there is just one place to track the discussion! But, we're making progress. The bump to librdkafka v1.6.0 has merged. Just need to shake out a bug.
