### ISSUE TITLE
Client destruction hangs when using jemalloc and low statistics.interval.ms settings

### ISSUE THREAD

**Issue by fede1024** [fede1024/rust-rdkafka#34]
Setting `statistics.interval.ms` to a low value (100ms for example) in the integration tests causes the tests to hang during client destruction (`rdkafka::rd_kafka_destroy(self.native.ptr)` in `Client.drop()`).

The bug disappear when tests are configured to use the system allocator instead of jemalloc.

**Comment by fede1024** [comment]
This problem seems to have disappeared after commit 286910b872e6d1327dfd0baaf3efc7bf939e0a36.

**Comment by JimChenWYU** [comment]
hello, how to use jemalloc in rust-rdkafka？
