### ISSUE TITLE
Cooperative Incremental sticky rebalance

### ISSUE THREAD

**Issue by oronsh** [fede1024/rust-rdkafka#363]
Hello!
First of all, thank you for the hard work you're doing on this project!
I'd like to know if there's a way or will be in the future to use the cooperative incremental rebalance.
Thanks a lot!

**Comment by benesch** [comment]
This library is just a wrapper around librdkafka, so any configuration available there works here, too. See https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md. In theory, you can just set the `partition.assignment.strategy` configuration option to `cooperative-sticky` on your consumer at it will all just work out! I haven't tried it, though.

**Comment by oronsh** [comment]
Thank you for your fast reply :)
From what I can see in `librdkafka` examples it has to be done with the `rebalance_cb` as well:
https://github.com/edenhill/librdkafka/blob/master/examples/rdkafka_complex_consumer_example.cpp#L157-L159

Am I just being confused?
Thanks a lot

**Comment by SreeniIO** [comment]
When using this option while creating a consumer
```
.set("partition.assignment.strategy", "cooperative-sticky")
```
Getting the below warning and it never consumes any messages.
```
Apr 12 21:03:59.859  WARN librdkafka: librdkafka: ASSIGN [thrd:main]: Group "io_scheduler_group": 
application *assign() call failed: Changes to the current assignment must be made using 
incremental_assign() or incremental_unassign() when rebalance protocol type is COOPERATIVE 
```

**Comment by benesch** [comment]
Ah, I see. Sounds like code changes here are required then. I don’t have
time to look at this, but I’d be happy to entertain a PR.

**Comment by SreeniIO** [comment]
Just submitted a PR. Please let me know if there is a way to read consumer configs from ConsumerContext. If so, the newly added function `is_incremental_assign` can be avoided.

**Comment by oronsh** [comment]
Yay! thank you @SreeniIO @benesch 🥇

**Comment by SreeniIO** [comment]
Any update on this please?
