### ISSUE TITLE
[Suggestion] Receive option as hashmap

### ISSUE THREAD

**Issue by djKooks** [fede1024/rust-rdkafka#366]
Hello,
While using the module, there are a situation to receive configs as HashMap.
But in the example I could only find setting config one by one using `ClientConfig::new().set().set()...`

Is there some option to put option as hashmap such as
```
let config = HashMap::new();
// ...
let client_config = ClientConfig::new().set_config_map(config);
...
```
?

**Comment by benesch** [comment]
Fixed in #367. Thanks, @djKooks!
