### ISSUE TITLE
Using `store_offset` with `OwnedMessage`

### ISSUE THREAD

**Issue by bruceg** [fede1024/rust-rdkafka#368]
I would like to use the `Consumer::store_offset` interface to update the offset asynchronously after a message has been fully processed. Currently, this interface takes a `BorrowedMessage` parameter, but I have not figured a way to use this type due to needing a static lifetime on the async block. I could detach the borrowed message into an `OwnedMessage` to satisfy the static lifetime requirement, but `store_offset` takes a `BorrowedMessage` parameter and there is no way to produce one from an `OwnedMessage`. Even if this was possible, it is far from ideal, as `store_offset` only actually requires the topic, partition, and offset data, and storing the entire message just to access those is rather inefficient.

Is there another way to achieve this process?

**Comment by bruceg** [comment]
IMO ideally `Consumer::store_offset` would take a generic parameter that is `Into` some intermediate type that stores references to the three pieces of data required. This intermediate type could then be implemented for `BorrowedMessage`, `OwnedMessage`, and hopefully a new type that just stored the topic, partition, and offset. This would make it a different interface, but one that should only break code that implements `trait Consumer`, which I would expect to be rare in consumers of this crate.

**Comment by binarylogic** [comment]
@fede1024 thanks for your work on this library. It looks like @blt, another Vector engineer, filed a similar issue (#89). If you could approve this direction we'd be happy to contribute the change.

**Comment by benesch** [comment]
If you have a minute, #376 should do what you need!
