### ISSUE TITLE
Kafka simple producer slow for 250_000 messages, add example?

### ISSUE THREAD

**Issue by Zarathustra2** [fede1024/rust-rdkafka#369]
Hey there, 

Hope you all are doing fine!

~~As https://github.com/fede1024/kafka-benchmark/issues/10 cannot be built anymore~~ is there any chance that the examples could be extended with an example showing how to produce around 1,000,000 messages per second. 

EDIT: Sorry had a bad configuration locally and assumed based on the issue that it cannot be built anymore, my bad. After executing `./target/debug/kafka-benchmark producer config/base_producer.yaml 1KB_bursts` I am getting `Error KafkaError (Message production error: UnknownPartition (Local: Unknown partition))`, so there is still something going wrong or I am missing something. 

I tried running the simple producer from the examples but stopped it after running it for 1min on my machine. Then I updated it with buffering of futures which resulted in 4814ms for 250_000 messages but that is still far off that 1,000,000 messages per second. 

Would really appreciate an example for producing a lot of messages or fixing the kafka-benchmark so it can be ran locally! 

Best regards,

Dario

Code snippets with the following toml:
```TOML
[dependencies]
rdkafka = { version = "0.26", features = ["cmake-build"] }
tokio = { version = "1", features = ["full"] }
futures = "0.3.15"
```

<details>
<summary>Producer with futures buffering 4814ms for 250_000 messages</summary>
<pre>
use std::time::{Duration, Instant};

use rdkafka::{ClientConfig, producer::{FutureProducer, FutureRecord}, util::get_rdkafka_version};

use futures::{StreamExt, stream::{self}};

#[tokio::main]
async fn main() {

    let (version_n, version_s) = get_rdkafka_version();
    println!("rd_kafka_version: 0x{:08x}, {}", version_n, version_s);

    let producer: &FutureProducer = &ClientConfig::new()
        .set("bootstrap.servers", "localhost:9092")
        .set("message.timeout.ms", "5000")
        .create()
        .expect("Kafka Producer creation error");

    let start = Instant::now();

    let amount =250_000;

    let futures = (0..amount)
        .map(|i| async move {
            let delivery_status = producer
                .send(
                    FutureRecord::to("topic-test")
                        .payload(&format!("Message {}", i))
                        .key(&format!("Key {}", i)),
                    Duration::from_secs(0),
                )
                .await;

            delivery_status
        })
        .collect::<Vec<_>>();

    let mut futures = stream::iter(futures).buffered(500);

    while let Some(future) = futures.next().await {
        future.unwrap();
    }

    println!("Took {}ms to publish {} msg", start.elapsed().as_millis(), amount);

}

----
Running `target/debug/rust_playground`
rd_kafka_version: 0x000001ff, 1.6.1
Took 4814ms to publish 250000 msg
</pre>
</details>

------

<details>
<summary>Producer as in examples ??(stopped after 1minute) for 250_000 messages</summary>
<pre>
use std::time::{Duration, Instant};

use rdkafka::{ClientConfig, producer::{FutureProducer, FutureRecord}, util::get_rdkafka_version};

use futures::{StreamExt, stream::{self}};

#[tokio::main]
async fn main() {

    let (version_n, version_s) = get_rdkafka_version();
    println!("rd_kafka_version: 0x{:08x}, {}", version_n, version_s);

    let producer: &FutureProducer = &ClientConfig::new()
        .set("bootstrap.servers", "localhost:9092")
        .set("message.timeout.ms", "5000")
        .create()
        .expect("Kafka Producer creation error");

    let start = Instant::now();

    let amount =250_000;

    let futures = (0..amount)
        .map(|i| async move {
            let delivery_status = producer
                .send(
                    FutureRecord::to("topic-test")
                        .payload(&format!("Message {}", i))
                        .key(&format!("Key {}", i)),
                    Duration::from_secs(0),
                )
                .await;

            delivery_status
        })
        .collect::<Vec<_>>();

    // This loop will wait until all delivery statuses have been received.
    for future in futures {
        future.await.unwrap();
    }

    println!("Took {}ms to publish {} msg", start.elapsed().as_millis(), amount);

}

-----

</pre>
</details>

**Comment by gklijs** [comment]
How many partitions did the topic had when running the test? I guess that might have been the problem. Also some broker settings can affect performance, and of course the resources the broker has available, and the latency to the broker.

**Comment by Zarathustra2** [comment]
It was only one partition but I ended up using the `ThreadedProducer` instead of `FutureProducer` - see linked PR - which solved my problem in the end! :)

**Comment by gklijs** [comment]
Yes, I saw it a bit later. Made me aware the `ThreadedProducer` existed at all. Probably going to rewire a bit so an example also uses it.

**Comment by benesch** [comment]
Yep, the `ThreadedProducer` is the way to go.

**Comment by arkanmgerges** [comment]
I wish that ThreadedProducer example was there. I've lost a lot of hours searching.
