### ISSUE TITLE
sasl2 dependency fails on build on mac os

### ISSUE THREAD

**Issue by blagovestb2c2** [fede1024/rust-rdkafka#377]
When i run cargo build, i get the following error:

```
error: failed to run custom build command for `sasl2-sys v0.1.14`

Caused by:
  omitted (exit code: 101)
  --- stdout
  cargo:rerun-if-env-changed=SASL2_STATIC
  cargo:rerun-if-env-changed=LIBSASL2_NO_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=LIBSASL2_STATIC
  cargo:rerun-if-env-changed=LIBSASL2_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-apple-darwin
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_apple_darwin
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-apple-darwin
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_apple_darwin
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-apple-darwin
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_apple_darwin
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR

  --- stderr
  thread 'main' panicked at 'Unable to find libsasl2 on your system. Hints:

    * Have you installed the libsasl2 development package for your platform?
      On Debian-based systems, try libsasl2-dev. On RHEL-based systems, try
      cyrus-sasl-devel.

    * Have you incorrectly set the SASL2_STATIC environment variable when your
      system only supports dynamic linking?

    * Are you willing to enable the `vendored` feature to instead build and link
      against a bundled copy of libsasl2?
  ', /omitted/.cargo/registry/src/github.com-1ecc6299db9ec823/sasl2-sys-0.1.14/build.rs:247:5
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
  ```
  
  I did cargo tree --invert and this seems to come from rdkafka
  
  ```
  sasl2-sys v0.1.14
└── rdkafka-sys v4.0.0+1.6.1
    └── rdkafka v0.26.0
  ```

Any advice on how to fix this? Our Linux-based CI build seems to build fine.

**Comment by benesch** [comment]
> Any advice on how to fix this? Our Linux-based CI build seems to build fine.

Yes, I put the hints in the error message: 😄

```Unable to find libsasl2 on your system. Hints:

    * Have you installed the libsasl2 development package for your platform?
      On Debian-based systems, try libsasl2-dev. On RHEL-based systems, try
      cyrus-sasl-devel.

    * Have you incorrectly set the SASL2_STATIC environment variable when your
      system only supports dynamic linking?

    * Are you willing to enable the `vendored` feature to instead build and link
      against a bundled copy of libsasl2?
```

You either need to have libsasl2 installed on your system (`brew install cyrus-sasl`) or you need to enable the `vendored` feature. If you've done one of those two things and it's still not working, tell me which you did and we can debug.

**Comment by blagovestb2c2** [comment]
Sorry, didn't mean to sound extra stupid, I just wasn't sure what to do on Mac (cyrus-sasl as a name is not mentioned). I will try now

**Comment by benesch** [comment]
Please let me know how it goes. If it works I'll merge https://github.com/MaterializeInc/rust-sasl/pull/26.

**Comment by blagovestb2c2** [comment]
Brew installed it and I had to specify SASL2_DIR but now I'm getting 

 CMake Error at /usr/local/Cellar/cmake/3.20.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
    Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
    system variable OPENSSL_ROOT_DIR (missing: OPENSSL_CRYPTO_LIBRARY) (found
    version "1.1.1g")
    
 I'm not sure why this started happening now. For months I was having zero problems. I guess i'll keep trying to fix it now

**Comment by benesch** [comment]
You might find it simpler just to enable the `ssl-vendored` and `gssapi-vendored` features, which will build and link against copies of OpenSSL and libsasl2 that are bundled with the crates, rather than trying to find them on your OS.

**Comment by blagovestb2c2** [comment]
having both features enabled was failing ``` ld: symbol(s) not found for architecture x86_64
  clang: clangerror: : errorlinker command failed with exit code 1 (use -v to see invocation): 
  linker command failed with exit code 1 (use -v to see invocation)```
  
 having only ssl-vendored enabled however made the build succeed

**Comment by benesch** [comment]
Ok, great. I don’t think there is an actual issue here then, so closing, but holler if you’ve got evidence of something being in the right place but not getting picked up by the build script.
