### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by vks** [fede1024/rust-rdkafka#380]
The build script for `rdkafka-sys` uses `cp` for copying files, which does not work on Windows systems. Would it be possible to use `std` instead? I understand that copying directories recursively with `std` is non-trivial.

**Comment by doowonee** [comment]
Did you use `cmake-build` feature? In windows you must install cmake first and then try `rdkafka = { version = "0.26", features = ["cmake-build"] }` on `Cargo.toml`. In works in my windows 10

**Comment by benesch** [comment]
@doowonee is exactly right. The default librdkafka build system does not support Windows, so on Windows you've got to use CMake. Feel free to file an issue if that causes you trouble though!

**Comment by vks** [comment]
@benesch Fair enough. Does it make sense to add this to the known issues in the README?
