### ISSUE TITLE
Inconsistent Offset definition

### ISSUE THREAD

**Issue by bazhenov** [fede1024/rust-rdkafka#383]
Hi. I'm using rdkafka 0.26.0

From [librdkafka documentation](https://docs.confluent.io/2.0.0/clients/librdkafka/classRdKafka_1_1Consumer.html#ad2044e3433f626baff667e1a429d6f33) it follows partition offset can be non-negative number.

> Start consuming messages for topic and partition at offset offset which may either be a **proper offset (0..N)** or one of the the special offsets: OFFSET_BEGINNING or OFFSET_END.

`Offset::Offset` documentation agrees

> Note that while the offset is a signed integer, negative offsets will be rejected when passed to librdkafka.

Also `kafka-console-consumer.sh` able to successfully read first message in a topic using zero offset.

```
$ kafka-console-consumer.sh --topic test_topic --bootstrap-server 127.1:9092 --offset 0 --partition 0
```

Unfortunately, [`Offset::to_raw()`](https://github.com/fede1024/rust-rdkafka/blob/master/src/topic_partition_list.rs#L73) requires strictly positive offset.

```rust
pub fn to_raw(self) -> Option<i64> {
        match self {
            [...]
            Offset::Offset(n) if n > 0 => Some(n),
            [...]
        }
    }
```

**Comment by benesch** [comment]
Ah, that got fixed recently: https://github.com/fede1024/rust-rdkafka/commit/cb7393b4ee9b633deb53e11e2409896b4b1f1920. Probably time for a new release.

**Comment by bazhenov** [comment]
ok, thanks! I guess I can use master build meanwhile.
