### ISSUE TITLE
How to set a specific offset?

### ISSUE THREAD

**Issue by rqzrqh** [fede1024/rust-rdkafka#384]
librdkafka has been used for the program and work well, now i rewrite it in rust. 
kafka(input topic)-->my process-->(many out topics)kafka

this program is a statemachine, it's state was stored in database. when program restarted, it must load from db and  restore to the corrent state. the offset is one of the state. so i want to set offset to kafka and replay from this offset, but i can't find the way in examples.
Is this function not supported now? Or just not in examples?

**Comment by benesch** [comment]
You're probably looking for [`seek`](https://docs.rs/rdkafka/0.26.0/rdkafka/consumer/trait.Consumer.html#tymethod.seek).
