### ISSUE TITLE
DeleteRecords

### ISSUE THREAD

**Issue by crepererum** [fede1024/rust-rdkafka#385]
As per https://github.com/edenhill/librdkafka/issues/1773 `DeleteRecords` was added to rdkafka in 1.6.0. This functionality is not yet mapped to Rust.

**Comment by benesch** [comment]
PRs welcome :)

**Comment by vitorenesduarte** [comment]
Any pointers on how such API could be implemented? Is there a similar API?

**Comment by benesch** [comment]
Well, I guess no one urgently needed this in the last three years. I have a need for it now, though, so I've put up https://github.com/fede1024/rust-rdkafka/pull/714.

> Any pointers on how such API could be implemented? Is there a similar API?

For posterity: yes, basically every admin client method is similar. See src/admin.rs.
