### ISSUE TITLE
[Question] Is FromBytes intended to be implemented to support reading Kafka Messages as say JSON?

### ISSUE THREAD

**Issue by jkratz55** [fede1024/rust-rdkafka#387]
Sorry if this is a silly question or I missed something in the documentation but I was wondering if the FromBytes trait was intended to be used so that users of the crate could use payload_view<T>() to read message payload that is JSON and deserialize it as a struct.

I have a struct like follows and trying to do something along with the following:

```
#[derive(Deserialize, Debug)]
struct CmsEvent {
    #[serde(rename(deserialize = "id"))]
    id: String,

    #[serde(rename(deserialize = "type"))]
    r#type: String,

    #[serde(rename(deserialize = "event"))]
    event: String,

    #[serde(rename(deserialize = "dataSource"))]
    datasource: serde_json::Value,
}

impl FromBytes for CmsEvent {
    type Error = serde_json::Error;

    fn from_bytes(bytes: &[u8]) -> Result<&Self, Self::Error> {
        serde_json::from_slice(bytes)
    }
}
```

And then use it like the following

`msg.payload_view::<CmsEvent>()`

Can FromBytes trait be used in this way, or was it not intended to be used in this manner?

**Comment by benesch** [comment]
Ah, yeah, afraid not. `FromBytes` really just exists to allow you to request the payload as a byte slice _or_ a `str`.  In your case you probably just want something like:

```rust
let cms_event: CmsEvent = serde_json::from_slice(message.payload().unwrap_or(&[]))?;
```

**Comment by jkratz55** [comment]
Thanks for the quick reply!
