### ISSUE TITLE
Make client(&self) in Producer and Consumer public

### ISSUE THREAD

**Issue by alex-novikov-1990** [fede1024/rust-rdkafka#389]
Please, make the client(&self) in Producer and Consumer public. In producers it was public until this commit: https://github.com/fede1024/rust-rdkafka/commit/e123bd4a9911ff2af4ba422bd188bec0b3424e88
Some usecases require obtaining additional info about topics and partitions via `producer_or_consumer.client().fetch_metadata(...)`.

**Comment by alex-novikov-1990** [comment]
May bad, forgot to `use rdkafka::producer::Producer`.

**Comment by bigKoki** [comment]
> May bad, forgot to `use rdkafka::producer::Producer`.

hello, I came to this problem too, could you please describe how to resolve this?
thanks!!!

**Comment by alex-novikov-1990** [comment]
Wow, three years have passed already. I don't quite remember, but I guess that I was able to call `.client().fetch_metadate()` on producer or consumer after I added `use rdkafka::producer::Producer;` line to the code.

**Comment by bigKoki** [comment]
> Wow, three years have passed already. I don't quite remember, but I guess that I was able to call `.client().fetch_metadate()` on producer or consumer after I added `use rdkafka::producer::Producer;` line to the code.

Thansk for your reply! I found this method too.
