### ISSUE TITLE
Proper termination sequence

### ISSUE THREAD

**Issue by thijsc** [fede1024/rust-rdkafka#39]
We don't implement https://github.com/edenhill/librdkafka/wiki/Proper-termination-sequence currently.

**Comment by thijsc** [comment]
I've checked the usage of `rd_kafka_topic_partition_t` and `rd_kafka_topic_partition_list_t`, that should be ok.

**Comment by thijsc** [comment]
I made some changes here: #40

**Comment by thijsc** [comment]
The topic -> client cleanup should be ok for now, because Rust drops struct fields in order currently. This is unspecified behaviour though.

**Comment by fede1024** [comment]
I pushed a new change that completely removes the `ProducerTopic` handle, so we won't have to rely on unspecified behavior. Removing the topic handle also makes the crate easier to use.
