### ISSUE TITLE
Baseproducer is not throwing error evenif the server does not exist 

### ISSUE THREAD

**Issue by davnav** [fede1024/rust-rdkafka#394]
Below code -  Evenif the kafka server 'locast:9092' is not available, the Baseproducer is not panic while running or sending the message. 

```
fn main() {
    let producer: BaseProducer = ClientConfig::new()
        .set("bootstrap.servers", "locast:9092")
        .create()
        .unwrap();

    println!("producer created");
    

    for i in 1..10{

        // println!("sending message");

        let s = producer
        .send(
            BaseRecord::to("quickstart-events")
                .payload( &format!("this is test message : {}",i))
                .key(&format!("this is key:{}",i))
        )
        .unwrap();
        println!("{:?}",s);
        thread::sleep(Duration::from_secs(1));
    }

}
```

**Comment by benesch** [comment]
You need to poll the base producer to actually deliver messages. See the example here: https://docs.rs/rdkafka/0.26.0/rdkafka/producer/struct.BaseProducer.html#example-usage

I recommend that you use either the [`ThreadedProducer`](https://docs.rs/rdkafka/0.26.0/rdkafka/producer/struct.ThreadedProducer.html) or [`FutureProducer`](https://docs.rs/rdkafka/0.26.0/rdkafka/producer/struct.FutureProducer.html) instead, because they handle a lot of this complexity for you. More details in the docs here: https://docs.rs/rdkafka/0.26.0/rdkafka/producer/index.html#rust-rdkafka-producers

**Comment by kpaddy** [comment]
> You need to poll the base producer to actually deliver messages. See the example here: https://docs.rs/rdkafka/0.26.0/rdkafka/producer/struct.BaseProducer.html#example-usage
> 
> I recommend that you use either the [`ThreadedProducer`](https://docs.rs/rdkafka/0.26.0/rdkafka/producer/struct.ThreadedProducer.html) or [`FutureProducer`](https://docs.rs/rdkafka/0.26.0/rdkafka/producer/struct.FutureProducer.html) instead, because they handle a lot of this complexity for you. More details in the docs here: https://docs.rs/rdkafka/0.26.0/rdkafka/producer/index.html#rust-rdkafka-producers

I am having the same issue, where the producer code doesn't throw any errors. Like you suggested, I tired the FutureProducer, however it didn't work. I am running this on a Mac. Here is my Cargo.toml 

[dependencies]
rdkafka = { version = "0.28.0" }
serde = { version = "1.0"  }
serde_json = "1.0"
rand = "0.8.3"
ctrlc = "3.1.8"

**Comment by wensiwei** [comment]
> You need to poll the base producer to actually deliver messages. See the example here: https://docs.rs/rdkafka/0.26.0/rdkafka/producer/struct.BaseProducer.html#example-usage
> 
> I recommend that you use either the [`ThreadedProducer`](https://docs.rs/rdkafka/0.26.0/rdkafka/producer/struct.ThreadedProducer.html) or [`FutureProducer`](https://docs.rs/rdkafka/0.26.0/rdkafka/producer/struct.FutureProducer.html) instead, because they handle a lot of this complexity for you. More details in the docs here: https://docs.rs/rdkafka/0.26.0/rdkafka/producer/index.html#rust-rdkafka-producers

I'm used [`ThreadedProducer`] to send kafka messages. I also hope to get the error information of send when the server does not exist, but I don't know how to catch this error in time . The message can't be lost.

So how do I get the producer result in the example,  thank you!

code
```rust
#[macro_use]
extern crate tracing;

use std::thread;
use std::time::Duration;
use rdkafka::ClientConfig;
use rdkafka::producer::{ThreadedProducer, BaseRecord, DefaultProducerContext};
use tlog::{init_global_log, LogConfig};

#[tokio::main]
async fn main() {
    let new_cfg = LogConfig::default().set_level("debug");
    let (_file_guard, _log_manager) = init_global_log(&new_cfg).unwrap();

    let producer: ThreadedProducer<DefaultProducerContext> = ClientConfig::new()
        .set("bootstrap.servers", "locast:9092")
        .create()
        .unwrap();

    println!("producer created");

    for i in 1..10{
        let message = format!("message {}", i);
        let s = producer
            .send(
                BaseRecord::to("quickstart-events")
                    .payload(&message)
                    .key("")
            );
        //If send fail in there, I want to collect it and try again.
        println!("{:?}", s);
        thread::sleep(Duration::from_secs(1));
    }
}
```

result
```linux
    Finished dev [unoptimized + debuginfo] target(s) in 6.22s
     Running `target/debug/test_thread_producer`
producer created
Ok(())
  2023-01-29T17:06:11.284 ERROR librdkafka: librdkafka: FAIL [thrd:locast:9092/bootstrap]: locast:9092/bootstrap: Failed to resolve 'locast:9092': Name or service not known (after 47ms in state CONNECT)
    at /root/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/rdkafka-0.28.0/src/client.rs:64

  2023-01-29T17:06:11.284 ERROR rdkafka::client: librdkafka: Global error: Resolve (Local: Host resolution failure): locast:9092/bootstrap: Failed to resolve 'locast:9092': Name or service not known (after 47ms in state CONNECT)
    at /root/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/rdkafka-0.28.0/src/client.rs:106

  2023-01-29T17:06:11.284 ERROR rdkafka::client: librdkafka: Global error: AllBrokersDown (Local: All broker connections are down): 1/1 brokers are down
    at /root/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/rdkafka-0.28.0/src/client.rs:106

Ok(())
Ok(())
  2023-01-29T17:06:13.237 ERROR librdkafka: librdkafka: FAIL [thrd:locast:9092/bootstrap]: locast:9092/bootstrap: Failed to resolve 'locast:9092': Name or service not known (after 0ms in state CONNECT, 1 identical error(s) suppressed)
    at /root/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/rdkafka-0.28.0/src/client.rs:64

  2023-01-29T17:06:13.237 ERROR rdkafka::client: librdkafka: Global error: Resolve (Local: Host resolution failure): locast:9092/bootstrap: Failed to resolve 'locast:9092': Name or service not known (after 0ms in state CONNECT, 1 identical error(s) suppressed)
    at /root/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/rdkafka-0.28.0/src/client.rs:106

Ok(())
Ok(())
Ok(())
Ok(())
Ok(())
Ok(())
  2023-01-29T17:06:20.244  WARN librdkafka: librdkafka: TERMINATE [thrd:app]: Producer terminating with 9 messages (81 bytes) still in queue or transit: use flush() to wait for outstanding message delivery
    at /root/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/rdkafka-0.28.0/src/client.rs:67

```
