### ISSUE TITLE
subscribing to multiple topics with some unknowns

### ISSUE THREAD

**Issue by Licenser** [fede1024/rust-rdkafka#396]
If subscribing to (say 5 topics) of which two are unknown `subscribe` will return a error with an unknown topic, how is it possible to determine which of the topics is unknown, and if any are subscribed successfully?

the upstream documentation  reads ([copied for ease of reading](https://docs.confluent.io/platform/current/clients/librdkafka/html/md_INTRODUCTION.html#unknown-or-unauthorized-topics))

```
If a consumer application subscribes to non-existent or unauthorized topics a consumer error will be propagated for each unavailable topic with the error code set to either RD_KAFKA_RESP_ERR_UNKNOWN_TOPIC_OR_PART or a broker-specific error code, such as RD_KAFKA_RESP_ERR_TOPIC_AUTHORIZATION_FAILED.
```

Which suggests to me that we should see two errors of the kind suggested above, but the function only returns a singular error, would it make sense to have `subscribe` return a list of errors? Or is there a way to get more information this I'm not seeing?

**Comment by benesch** [comment]
I think `subscribe` just returns errors directly for things like invalid topic names. Errors about unknown topics are probably surfaced via the global error callback: https://docs.rs/rdkafka/0.26.0/rdkafka/client/trait.ClientContext.html#method.error. Let me know if that turns out not to be the case!

**Comment by Licenser** [comment]
I'm not sure that really works, it errors as long as one topic is not present, but given the documentation (at least if I read it correctly) it should subscribe to the existing ones and give one error for each missing one. The callback comes with the issue that it's not related to the call that was made :(.

**Comment by Licenser** [comment]
@benesch I don't think your suggestion solves the problem, it'd still leave at a state were it's not possible to figure out which topics where subscribed and which failedl
