### ISSUE TITLE
Unknown Topic after Kafka Problems

### ISSUE THREAD

**Issue by scirner22** [fede1024/rust-rdkafka#403]
I'm using this library to connect to a cluster that goes unstable every once in a while and the solution is to restart every broker one at a time. During this most recent occurrence I see the following error a lot:

```
librdkafka: FAIL [thrd:ssl://kafka-3.broker.kafka.svc.cluster.local:9092/3]: ssl://kafka-3.broker.kafka.svc.cluster.local:9092/3: 1 request(s) timed out: disconnect (after 15855ms in state UP, 1 identical error(s) suppressed)
```

This error is expected since the cluster is in a partial rebooting state. After the cluster fully comes up, the following error is received when attempting to produce messages.

```
Kafka(KafkaError (Message production error: UnknownTopic (Local: Unknown topic)))
```

This is the error received by the producer until the process is restarted. During error states do I need to manually refresh the metadata? I"m currently on version `0.24`.

**Comment by benesch** [comment]
For a complete answer I'm afraid you'd have to ask upstream at edenhill/librdkafka. I'm not sure whether that sort of error is meant to be handled automatically. One thing you could look into is the `topic.metadata.refresh.interval.ms` parameter, which defaults to something relatively high (5 minutes). It's possible that librdkafka is working as intended and you just need to wait out the topic metadata refresh interval. If that's the case you could consider using a much shorter metadata refresh interval. But, again, I'm not the right person to speak authoritatively on these things!

**Comment by davidblewett** [comment]
@scirner22 does shortening `topic.metadata.refresh.interval.ms` resolve your issue?

**Comment by scirner22** [comment]
Thanks for the feedback. I didn't fully witness the incident so I'm not sure if it resolved after the `interval.ms` elapsed, but that does sound promising. I wasn't able to reproduce for now to get more information so I'll go ahead and close this. Thank you for the help!
