### ISSUE TITLE
Additional maintainers

### ISSUE THREAD

**Issue by davidblewett** [fede1024/rust-rdkafka#412]
> By the way, I noticed there's a few of you from @datadog that have been contributing lately. First of all, thanks for sending stuff back upstream! It's super appreciated. Second, if it ever makes sense, it might be time to find a more stable maintainership situation for rust-rdkafka. I sort of accidentally fell into maintainership after @fede1024 got busy a few years ago, and I occasionally spend my 20% time @MaterializeInc looking after things, but my time is in increasingly short supply. If you or anyone else at @datadog is ever interested in pitching in with maintainership, please let me know!

_Originally posted by @benesch in https://github.com/fede1024/rust-rdkafka/issues/395#issuecomment-980509230_

We are starting to use this package in several areas, so would be very interested in helping to maintain the project. How would you like to move forward with this? It would probably be good to grant access to a group somehow instead of individuals. I thought it would be best to discuss this openly here. If you would like to contact me directly, my email is david.blewett@datadoghq.com .

**Comment by benesch** [comment]
Let me start an email chain with @fede1024, since I don't think he actively watches this repository any longer!

**Comment by benesch** [comment]
Here are three possible paths forward for discussion:

1. @fede1024 grants access to a few folks from Datadog, but retains ownership of the repository and ultimate authority over the project.
2. We form a GitHub organization with some lightweight structure to allow a council of maintainers to make project-level decisions (like electing new maintainers).
3. We donate the project to the Apache Foundation or some other existing organization that has existing structure/guidance to offer around project management.

@fede1024, what do you think?

**Comment by davidblewett** [comment]
Final decision here was to add four additional maintainers from Datadog: @davidblewett , @duarten , @guillaumebort and @gravaton . Additionally, @davidblewett will be granted release privileges to crates.io.

**Comment by fede1024** [comment]
Thanks David for offering your help in maintaining the library and creating new releases, and thanks also to the new maintainers!

I don't currently have the bandwidth to closely follow the development of this library, therefore I'm very happy to see that there are people willing to step up as maintainers. Nikhil has done an excellent job so far and I'm sure will appreciate some help going forward.
