### ISSUE TITLE
Segfault in `NativeClient::rebalance_protocol`

### ISSUE THREAD

**Issue by bruceg** [fede1024/rust-rdkafka#416]
We are seeing a sporadic segfault when handling rebalance events in our kafka client. I have traced this down to a null pointer being passed to `CStr::from_ptr`. It appears that `rdsys::rd_kafka_rebalance_protocol` can return a null pointer in some circumstances and the Rust library doesn't handle that. I have worked around it by returning `RebalanceProtocol::None` when this happens, but I don't know if there is a better solution or a deeper underlying problem.

**Comment by benesch** [comment]
Oy, yeah, looks like that's how it signals errors. `None` seems about right. The C example that I copied the incremental stuff passes the return value to `strcmp`, which ignores any distinction between `NULL` and `"NONE"`: https://github.com/edenhill/librdkafka/blob/f092c290995ca81b3afb4015fcc3350ba02caa96/examples/rdkafka_complex_consumer_example.c#L218

**Comment by benesch** [comment]
Would you be up for submitting a PR?

**Comment by bruceg** [comment]
Sure, coming right up.
