### ISSUE TITLE
cosumer.committed always return no offsets

### ISSUE THREAD

**Issue by tzachshabtay** [fede1024/rust-rdkafka#437]
Hi, I'm trying to use the `committed` function on the consumer (after setting it to a group which I know has committed offsets to several topics) to get the committed offsets, but the returned offsets list is always empty (tried several different groups, it's always empty).

My code:
```rust
    let group_consumer: BaseConsumer = ClientConfig::new()
        .set("bootstrap.servers", "url")
        .set("group.id", "my_group") // my_group is a consumer group which has committed(+stored) offsets on multiple topics
        .create().unwrap();
    let timeout = Duration::from_secs(10);
    let committed: TopicPartitionList = group_consumer.committed(timeout).unwrap();

    // Both print 0
    eprintln!("num offsets: {}", committed.elements().len());
    eprintln!("num offsets for topic: {}", committed.elements_for_topic("my_topic").len());  // my_topic is one of the topics for which my_group has committed offsets
```  

Please help, thanks in advance.

**Comment by benesch** [comment]
You probably need to call poll, if not subscribe followed by poll, or something. I don’t know off the top of my head. This all falls out of librdkafka. You might have some luck looking at upstream for examples of how to make this work.

**Comment by tzachshabtay** [comment]
Thanks, it works with subscribe followed by poll.

**Comment by svanharmelen** [comment]
So what does 'poll` mean in this context, which method or function should I use for that?

I have the same issue (always getting an empty result). I tried to make the call after the subscription is done, but that dint change anything... And I need the info before I start receiving messages (by looping over `consumer.recv()`).

Any pointer would be appreciated. Thanks!
