### ISSUE TITLE
Consumer does not consume w/ Redpanda.

### ISSUE THREAD

**Issue by goaaron** [fede1024/rust-rdkafka#439]
[](url)I'm trying to replicate the example consumer code. My client connects w/ SASL_SSL. I verify this to be the case.

However when I run `consumer.recv()` OR `consumer.stream().try_for_each( ...` I get no data pulled off the topic (which is populated).

Here's the sole logs I get.  At which point the program just stalls forever.
<img width="1057" alt="Screen Shot 2022-02-01 at 4 48 33 PM" src="https://user-images.githubusercontent.com/8647636/152076002-72d67aa2-dc23-4fae-bcb7-c913d2ad934b.png">

Unsure what to be done here.... 

The project is `rdkafka = { version = "0.25", features =  ["dynamic-linking", "ssl","gssapi"] }`

I am running on an M1. `Librdkafka` was compiled from source.

**Comment by SephVelut** [comment]
Same issue. Running simple-consumer example.
