### ISSUE TITLE
Help understanding "1 request(s) timed out".

### ISSUE THREAD

**Issue by Kyle-Thompson** [fede1024/rust-rdkafka#444]
I've been running into:
```
librdkafka: FAIL [thrd:ssl://<aws-msk-url>]: ssl://<aws-msk-url>: 1 request(s) timed out:           disconnect (after 21040ms in state UP, 2 identical error(s) suppressed)
```

But I'm not clear on where exactly or why it's happening. I'm not even getting this in the form of an error in a result, it seems to be happening entirely internally. Where can I go or what can I do to get more info on this error and how to fix it? To be clear, the URL does work, this seems to be an intermittent issue.

Thanks in advance.

**Comment by scanterog** [comment]
Hello, usually "request(s) timeout" will be logged in librdkafka (the underlying C library wrapped by rust-rdkafka). For example, when a kafka broker is under pressure it might take longer to reply and a producer instance might hit requests timeout. For more details check https://github.com/edenhill/librdkafka/blob/master/INTRODUCTION.md#producer-message-delivery-failure.
