### ISSUE TITLE
Improve documentation of CommitMode::Sync and CommitMode::Async

### ISSUE THREAD

**Issue by aarashy** [fede1024/rust-rdkafka#448]
Hello!

I'm using rust-rdkafka within a Tokio async runtime and I'm not sure why `BaseConsumer::commit_message` doesn't return a future.

Based on my understanding of [1], CommitMode::Sync is a fully blocking call that waits for the Kafka server to persist the committed offset on their filesystem before yielding back to the client.

CommitMode::Async differs only in that it doesn't wait for the server to finish persisting the offset before yielding.

## My fear of using CommitMode::Sync

Unlike `StreamConsumer::recv`, which is a proper Async function which returns a future, the `BaseConsumer::commit_message` function blocks the Tokio executor, does it not?

If so, any async runtime would really need to wrap the function call in a `spawn_blocking` or else other futures undergoing execution can not be polled. Is that correct?

(On the topic of using using `spawn_blocking`, I saw in  https://github.com/fede1024/rust-rdkafka/issues/226 that detaching the borrowed message into an owned message seems required to send the message into the async closure. The extra memory allocation that introduces is undesirable for my use case (up to 1GB bytes in a message) so I wonder if there's any way to avoid that)

## My fear of using CommitMode::Async

I'm afraid of using `CommitMode::Async` because I'm not certain whether it's possible for a race to cause the following behavior:

1. Consumer calls `commit_message` with offset X in `CommitMode::Async`
2. Consumer moves on to the next message and commits offset X+1 in `CommitMode::Async`
3. The Kafka server persists offset X+1
4. The Kafka server finally persists offset X. Now, if the consumer were to rehydrate from the latest committed offset, they would replay X+1 when it was already successfully committed, which is undesirable. 

Is the above actually a possibility or is my understanding wrong somewhere?

In both the `CommitMode::Sync` and `CommitMode::Async` case, we're at least making a network call. So, why not make `commit_message` return a future out of the box, or at least provide a version of it that returns a future?

Either way, I think users may benefit from an elaboration of the documentation here, so that they don't need to consult librdkafka documentation to understand what this CommitMode actually means.

```
/// Specifies whether a commit should be performed synchronously or
/// asynchronously.
#[derive(Clone, Copy, Debug)]
pub enum CommitMode {
    /// Synchronous commit.
    Sync = 0,
    /// Asynchronous commit.
    Async = 1,
}
```

Thanks for implementing this library!

[1]: https://github.com/edenhill/librdkafka/blob/f092c290995ca81b3afb4015fcc3350ba02caa96/src/rdkafka_offset.c#L387

**Comment by benesch** [comment]
> I'm using rust-rdkafka within a Tokio async runtime and I'm not sure why `BaseConsumer::commit_message` doesn't return a future.

Because librdkafka doesn't expose a callback-based interface to this function. It's really too bad. See #358. I opened an issue upstream long ago about this (edenhill/librdkafka#3212), but it's been crickets ever since. We're probably at the point where you'd need to get someone with an enterprise contract with Confluent to start making some noise about the issue.

> Unlike `StreamConsumer::recv`, which is a proper Async function which returns a future, the `BaseConsumer::commit_message` function blocks the Tokio executor, does it not?
> 
> If so, any async runtime would really need to wrap the function call in a `spawn_blocking` or else other futures undergoing execution can not be polled. Is that correct?

Yes.

> (On the topic of using using `spawn_blocking`, I saw in #226 that detaching the borrowed message into an owned message seems required to send the message into the async closure. The extra memory allocation that introduces is undesirable for my use case (up to 1GB bytes in a message) so I wonder if there's any way to avoid that)

The commit API was recently split into `commit` and `commit_message` for exactly this reason. If you use `commit` instead of `commit_message`, you'll only need to copy the `TopicPartitionList` into the async thunk, rather than the entire message.

> I'm afraid of using `CommitMode::Async` because I'm not certain whether it's possible for a race to cause the following behavior:
> 
> 1. Consumer calls `commit_message` with offset X in `CommitMode::Async`
> 2. Consumer moves on to the next message and commits offset X+1 in `CommitMode::Async`
> 3. The Kafka server persists offset X+1
> 4. The Kafka server finally persists offset X. Now, if the consumer were to rehydrate from the latest committed offset, they would replay X+1 when it was already successfully committed, which is undesirable.
> 
> Is the above actually a possibility or is my understanding wrong somewhere?

Sounds plausible enough to me. `CommitMode::Async` sure seems like "lol I don't care about correctness" mode.

> Either way, I think users may benefit from an elaboration of the documentation here, so that they don't need to consult librdkafka documentation to understand what this CommitMode actually means.

We'd be happy to take a PR for that. But yes, in many cases you'll unfortunately need to consult the librdkafka documentation for a fuller specification of behavior.

**Comment by aarashy** [comment]
Thanks for informing me about the situation @benesch, I put up a [small documentation PR](https://github.com/fede1024/rust-rdkafka/pull/449), after which I will close this issue.
