### ISSUE TITLE
Compile a shared lib with rdkafka for aarch64

### ISSUE THREAD

**Issue by uthng** [fede1024/rust-rdkafka#450]
Hi,

I am trying to compile a shared lib (crate-type = dylib) using rdkafka and I got this error:

`= note: /usr/lib/gcc-cross/aarch64-linux-gnu/5/../../../../aarch64-linux-gnu/bin/ld: /target/aarch64-unknown-linux-gnu/release/deps/librdkafka_sys-476925ac521b0859.rlib(rdkafka.o): Relocations in generic ELF (EM: 62)
          /usr/lib/gcc-cross/aarch64-linux-gnu/5/../../../../aarch64-linux-gnu/bin/ld: /target/aarch64-unknown-linux-gnu/release/deps/librdkafka_sys-476925ac521b0859.rlib(rdkafka.o): Relocations in generic ELF (EM: 62)
          /usr/lib/gcc-cross/aarch64-linux-gnu/5/../../../../aarch64-linux-gnu/bin/ld: /target/aarch64-unknown-linux-gnu/release/deps/librdkafka_sys-476925ac521b0859.rlib(rdkafka.o): Relocations in generic ELF (EM: 62)
          /usr/lib/gcc-cross/aarch64-linux-gnu/5/../../../../aarch64-linux-gnu/bin/ld: /target/aarch64-unknown-linux-gnu/release/deps/librdkafka_sys-476925ac521b0859.rlib(rdkafka.o): Relocations in generic ELF (EM: 62)
          /usr/lib/gcc-cross/aarch64-linux-gnu/5/../../../../aarch64-linux-gnu/bin/ld: /target/aarch64-unknown-linux-gnu/release/deps/librdkafka_sys-476925ac521b0859.rlib(rdkafka.o): Relocations in generic ELF (EM: 62)
          /usr/lib/gcc-cross/aarch64-linux-gnu/5/../../../../aarch64-linux-gnu/bin/ld: /target/aarch64-unknown-linux-gnu/release/deps/librdkafka_sys-476925ac521b0859.rlib(rdkafka.o): Relocations in generic ELF (EM: 62)
          /usr/lib/gcc-cross/aarch64-linux-gnu/5/../../../../aarch64-linux-gnu/bin/ld: /target/aarch64-unknown-linux-gnu/release/deps/librdkafka_sys-476925ac521b0859.rlib(rdkafka.o): Relocations in generic ELF (EM: 62)
          /usr/lib/gcc-cross/aarch64-linux-gnu/5/../../../../aarch64-linux-gnu/bin/ld: /target/aarch64-unknown-linux-gnu/release/deps/librdkafka_sys-476925ac521b0859.rlib(rdkafka.o): Relocations in generic ELF (EM: 62)
          /usr/lib/gcc-cross/aarch64-linux-gnu/5/../../../../aarch64-linux-gnu/bin/ld: /target/aarch64-unknown-linux-gnu/release/deps/librdkafka_sys-476925ac521b0859.rlib(rdkafka.o): Relocations in generic ELF (EM: 62)
          /usr/lib/gcc-cross/aarch64-linux-gnu/5/../../../../aarch64-linux-gnu/bin/ld: /target/aarch64-unknown-linux-gnu/release/deps/librdkafka_sys-476925ac521b0859.rlib(rdkafka.o): Relocations in generic ELF (EM: 62)
          /target/aarch64-unknown-linux-gnu/release/deps/librdkafka_sys-476925ac521b0859.rlib(rdkafka.o): error adding symbols: File in wrong format
          collect2: error: ld returned 1 exit status`

For amd64 or x86-64, everything works well.
Anyone has any idea about that ?

Best regards,

NT

**Comment by benesch** [comment]
Sorry, @uthng, but we can't help you debug cross-compilation issues here. There are some suggestions here that might be helpful: https://github.com/fede1024/rust-rdkafka/issues/447#issuecomment-1047425549
