### ISSUE TITLE
Question: Release time for 0.29.0

### ISSUE THREAD

**Issue by vertexclique** [fede1024/rust-rdkafka#478]
As per the title, when do you want to rollout a new minor?

**Comment by duarten** [comment]
I published 0.29.0 here: https://github.com/fede1024/rust-rdkafka/releases/tag/v0.29.0

**Comment by jszwedko** [comment]
@duarten just noticing that this hasn't been published to crates.io. Was that intentional?

**Comment by benesch** [comment]
Oops, that was not intentional! Released to crates.io now. Warning that the tag has been force-pushed, since the originally tagged commit hadn't updated the version in Cargo.toml.
