### ISSUE TITLE
Requesting a new published version of `rdkafka-sys`

### ISSUE THREAD

**Issue by gagbo** [fede1024/rust-rdkafka#493]
Hello,

This [dependabot commit](https://github.com/fede1024/rust-rdkafka/commit/b4e13e71d5ea54028ac31d06a0102257e51c810c) is a pretty important change for our use case and might warrant a new version of the crate with a new tag.

Changing major version here, for a `-sys` crate that has the `links` manifest key means that currently there is no version of `rdkafka-sys` that can coexist with libraries that also want to link to `zstd`, such as [async-compression](https://github.com/Nemo157/async-compression/blob/5530b751fe33fdb8cc366ac9c23369665b354322/Cargo.toml#L48) for example.

Would it be possible to have a new version of `rdkafka-sys` published with this change in the toml file please ?  Currently rdkafka-sys still reports a [1.4 zstd-sys dependency](https://lib.rs/crates/rdkafka-sys)

Thanks for the package, it's been a huge time saver for us :)

**Comment by xin-hao-awx** [comment]
Anyone will work on this?

**Comment by benesch** [comment]
v4.3.0+1.9.2 is released.
