### ISSUE TITLE
Why is CMake preferred?

### ISSUE THREAD

**Issue by colin-grapl** [fede1024/rust-rdkafka#494]
I see in the readme that the CMake build system should be preferred if it's acceptable to depend on CMake. I couldn't find any reason for this statement though - just wondering what the upside is?

**Comment by benesch** [comment]
The default librdkafka build system is a custom build system called [`mklove`](https://github.com/edenhill/mklove) that the librdkafka maintainer wrote. I'm not aware of any other major projects that use it. It doesn't see much real-world testing. It doesn't support out-of-tree builds, so we have some [irritating workarounds](https://github.com/fede1024/rust-rdkafka/blob/fe99e1fb18433debc5ba6ca811de983c535e1804/rdkafka-sys/build.rs#L154-L159) in the rdkafka-sys build script. It doesn't support cross-compilation. And it doesn't support building on Windows.

**Comment by colin-grapl** [comment]
OK got it, thanks!
