### ISSUE TITLE
RedPanda Consuming

### ISSUE THREAD

**Issue by DayOfThePenguin** [fede1024/rust-rdkafka#499]
Like #439, I'm unable to consume anything when connecting to RedPanda.  Admin API & production work fine, but consumption hangs on calls to `consumer.recv()`.  #439 was closed without a solution; I've tried using both `assign()` to manually set partitions + offsets & `subscribe()`.  A subsequent call to `position()` returns all offsets as `Invalid metadata=""`.  Interestingly, the "Invalid metadata" string appears nowhere in the source code of rust-rdkafka or librdkafka.

Example:
`Sep 26 22:25:14.015  INFO test_consumer_recv: redpanda::tests: TPL {test-topic/0: offset=Invalid metadata=""; test-topic/1: offset=Invalid metadata=""}`

Attempts to call `seek()` to reset to `Offset::Beginning` produce the same output TopicPartitionList, with all offsets reading `Invalid metadata=""`

**Comment by DayOfThePenguin** [comment]
RedPanda requires manual specification of API versions. i.e.

 `client_config.set("broker.version.fallback", "0.10.2.0");`

**Comment by oknozor** [comment]
Hey, I am trying to do the same, also using red panda locally. 
```rust
        let _ = consumer
            .seek(topic, 0, Offset::Beginning, Duration::from_secs(1))
            .expect("Failed to seek topic position");
 ```
Unfortunately I am still getting the following error with ` client_config.set("broker.version.fallback", "0.10.2.0");`: 
```
thread 'main' panicked at 'Failed to seek topic position: KafkaError (Seek error: Local: Erroneous state)', src/kafka/mod.rs:60:14
stack backtrace:
   0: rust_begin_unwind
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/core/src/panicking.rs:67:14
```
