### ISSUE TITLE
Cannot cross compile to for macOS

### ISSUE THREAD

**Issue by bodymindarts** [fede1024/rust-rdkafka#501]
I'm trying to compile binaries for Mac in our CI pipeline but running into the following error:
```
  make[2]: mig: No such file or directory
  make[2]: *** [Makefile:755: kcmrpc.h] Error 127
  make[2]: *** Waiting for unfinished jobs....
  make[1]: *** [Makefile:1155: all-recurse] Error 1
  make: *** [Makefile:1005: all-recurse] Error 1
  thread 'main' panicked at 'make failed in lib', /workspace/.cargo/registry/src/github.com-1ecc6299db9ec823/krb5-src-0.3.2+1.19.2/build.rs:138:41
  ```
  
  I am reposting https://github.com/MaterializeInc/rust-krb5-src/issues/23 as I think the error actually comes from the https://github.com/MaterializeInc/rust-krb5-src crate.

**Comment by benesch** [comment]
Yep, that’s a krb5-src issue, closing in favor of the issue you filed there!
