### ISSUE TITLE
Linking error when cargo build

### ISSUE THREAD

**Issue by abdullahskartal** [fede1024/rust-rdkafka#503]
Hey there,

I get an error when I build the project. My system is Apple M1.

Traceback:
```
...
Compiling sqlx v0.5.13
Compiling rdkafka v0.28.0
error: linking with `cc` failed: exit status: 1
  |
  = note: "cc" "-arch" "arm64"

...

= note: ld: warning: -undefined dynamic_lookup may not work with chained fixups
          ld: in /Users/kartal/Desktop/projects/***/backend-service/user-microservice/target/debug/deps/librdkafka_sys-2bcd75fca59e5f74.rlib(rdkafka.o), archive member 'rdkafka.o' with length 154896 is not mach-o or llvm bitcode file '/Users/abdullah/Desktop/projects/***/backend-service/user-microservice/target/debug/deps/librdkafka_sys-2bcd75fca59e5f74.rlib' for architecture arm64
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I guess it's because of the arm architecture. Is there any way I can solve this?

**Comment by uncommoncense** [comment]
Do you have specific features enabled? This is working on my M1 without any additional features.

**Comment by benesch** [comment]
We're not going to be able to investigate this without additional details. Please include the full output of the failed `cargo build` and the set of features you have enabled. Better yet, create a public repository which reproduces the issue, and link us at that.

**Comment by abdullahskartal** [comment]
cross compile worked for me,

```
cargo build --target x86_64-apple-darwin
cargo run --target x86_64-apple-darwin
```

thanks!
