### ISSUE TITLE
How to implement rdkafka::message::FromBytes for user's struct.

### ISSUE THREAD

**Issue by ruimo** [fede1024/rust-rdkafka#504]
Hi, I'm trying to implement FromBytes and in vain. Any suggestions?

    pub struct User<'a> {
        pub user_name: &'a str,
        pub email: &'a str,
    }
    
    impl<'a> FromBytes for User<'a> {
        type Error = bincode::Error;
    
        fn from_bytes<'b>(bytes: &'b [u8]) -> Result<&Self, Self::Error> where 'b: 'a {
            let user: Self = bincode::deserialize(bytes)?;
            Ok(&user)
        }
    }

Compilation error:

    error[E0195]: lifetime parameters or bounds on method `from_bytes` do not match the trait declaration
      --> src/lib.rs:17:18
       |
    17 |     fn from_bytes<'b>(bytes: &'b [u8]) -> Result<&Self, Self::Error> where 'b: 'a {
       |                  ^^^^ lifetimes do not match method in trait

**Comment by benesch** [comment]
Unfortunately I don't think this is possible with the current definition of `FromBytes`. Maybe there's something we can rig up with `GAT`s, but not sure. You'll just need to do this in two steps: first get the data as a byte slice, and then bincode deserialize it.
