### ISSUE TITLE
rdkafka-sys dependency

### ISSUE THREAD

**Issue by ahmedriza** [fede1024/rust-rdkafka#514]
I've been using version 0.28 of `rust-rdkafka`.  Here's the entry in `Cargo.toml`:
```
rdkafka = { version = "0.28", features = ["dynamic_linking", "ssl", "sasl"] }
```
(As can be seen, I'm using the `dynamic_linking` feature to use the specific version of `rdkafka` that's installed on the machine).

I noticed that after doing a `cargo update` to update versions of libraries, `Cargo.lock` now has a newer version of `rdkafka-sys`, i.e:
```
[[package]]
name = "rdkafka-sys"
version = "4.3.0+1.9.2"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "d222a401698c7f2010e3967353eae566d9934dcda49c29910da922414ab4e3f4"
```
`cargo-tree` shows:
```
│   │   ├── rdkafka v0.28.0
│   │   │   ├── futures v0.3.25 (*)
│   │   │   ├── libc v0.2.137
│   │   │   ├── log v0.4.17 (*)
│   │   │   ├── rdkafka-sys v4.3.0+1.9.2
```

I don't quite understand why this should get updated to version `4.3.0` since version `0.28` of `rdkafka` depends on version `4.2.0+1.8.2` of `rdkafka-sys`.  

How can I force that particular version of `rdkafka-sys` (without manually editing `Cargo.lock`)?  I've tried adding an explicit dependency to my `Cargo.toml` such as the following, but that doesn't help:

```
rdkafka-sys = "4.2.0"
```

**Comment by benesch** [comment]
This is just how Cargo works! Recommend reading https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-dependencies-from-cratesio. You need “=X.Y.Z” to constrain to a specific version. But generally you shouldn’t need to do this; v0.28 of rust-rdkafka is compatible with rdkafka-sys v4.x. If we make a breaking change to rdkafka-sys, we’ll release it as v5.
