### ISSUE TITLE
Allow purging (purge API) / don't leak on dropping producer

### ISSUE THREAD

**Issue by Ten0** [fede1024/rust-rdkafka#518]
I'm looking for a way to handle messages that have failed to send upon closing.

Currently, dropping the producer when kafka server is not started gives the following message:
```
[WARN] librdkafka: TERMINATE [thrd:app]: Producer terminating with 2 messages (13 bytes) still in queue or transit: use flush() to wait for outstanding message delivery
```

Flushing beforehand (`ThreadedProducer::flush`) will obviously always timeout because server is not running, and doesn't change the previous message.

Delivery callbacks from `ProducerContext` do not get called for these messages, leading to memory leaks (as Box/Arc/... are not cast back).

librdkafka provides the *purge API* to solve this issue (https://github.com/edenhill/librdkafka/issues/990, https://github.com/edenhill/librdkafka/commit/107af2a5c9c564b71b06266227e76f1f8fad942c#diff-84ac6df9f4f6c13f1f4eecf3b9c0e2cee4d7c4c005feea512ff3f82c000fb84eR2211).

It would be useful to have access to this API for scenarios such as mine or those described at https://github.com/edenhill/librdkafka/issues/990.

As the Rust API also does some nice `IntoOpaque` casting where it may leak if callbacks are not called, I think it would also be best to actually force an instant purge/flush when dropping the `BaseProducer`, both ensuring that the `DeliveryOpaque`s don't get somewhat-silently leaked, and making it more natural for users to handle failure to deliver messages.
(The reason this wasn't done in librdkafka [is that users may already be handling this separately](https://github.com/edenhill/librdkafka/issues/990#issuecomment-300587671), but that could just be released in 0.30.0 which would allow breaking changes - and this is unlikely to break much because such handling would be severely un-idiomatic as people would have to keep track of the set of raw pointers that were sent, removing them from the list as they get a callback, and cast them back using unsafe code to drop them in case they didn't receive the callback, instead of just opening the issue I'm opening right now)

Thanks!

**Comment by benesch** [comment]
Exposing the `purge` API and automatically calling it on drop makes sense to me! If you've got the time, please submit a PR! The maintainers don't have any spare bandwidth these days, I'm afraid.

**Comment by Ten0** [comment]
So I've started implementation, and the fact the `BaseProducer` is Clone ends up being somewhat of a nuisance.
Since it also seemed unnecessary (people could put it behind an `Arc` if needed), I started removing that, but then I found this extra test:

https://github.com/fede1024/rust-rdkafka/blob/527867de37643fbb807ce5fece3bd15b752e1b37/src/producer/base_producer.rs#L687-L701

making *extra sure* that it's really `Clone`, so I'm wondering, any particular reason why this is a requirement?
