### ISSUE TITLE
First time user

### ISSUE THREAD

**Issue by frankmcsherry** [fede1024/rust-rdkafka#56]
Hello! I've recently tried to use `rust-rdkafka`, and thought I would share some experiences. I think there may be some "issues" here, but there could also just be some helpful information about what people (person) stumble over.

First off, thank you! This is in support of a [timely dataflow](https://github.com/frankmcsherry/timely-dataflow) Kafka adapter, which I wouldn't want to try and write without a crate. :)

I wanted to try sending a message through kafka and back, so I wrote what seemed like a pretty simple program, following your examples but using the `Base*` variants of producer and consumer.

```rust
fn round_trip(brokers: &str, topic_name: &str) -> Result<(), rdkafka::error::KafkaError> {

    let mut topic_config = TopicConfig::new();
    topic_config
        .set("produce.offset.report", "true")
        .finalize();

    let mut client_config = ClientConfig::new();
    client_config
        .set("group.id", "example")
        .set("bootstrap.servers", brokers)
        .set_default_topic_config(topic_config);

    let producer: BaseProducer<_> = try!(client_config.create());
    let consumer: BaseConsumer<_> = try!(client_config.create());

    try!(consumer.subscribe(&[topic_name]));

    let text = format!("hi there at {:?}", ::std::time::Instant::now());
    try!(producer.send_copy::<str,()>(topic_name, None, Some(text.as_str()), None,  None, None));

    for _ in 0 .. 100 {

        producer.poll(1);

        if let Some(result) = try!(consumer.poll(1)) {
            println!("{:?}:\t{:?}", ::std::time::Instant::now(), result.payload_view::<str>());
            try!(consumer.commit(None, rdkafka::consumer::CommitMode::Sync));
        }
        else {
            println!("{:?}:\tgot nothing", ::std::time::Instant::now());
        }
    }

    Ok(())
}
```

The behavior was a bit surprising, and it was tricky to find documentation to explain if this was expected.

1. This seems to run to completion just fine, printing `"got nothing"` 100 times and returning `Ok(())` when neither ZK nor Kafka are up and running. Where is the moment in the code it is supposed to complain if they are not installed or up and running? (when they are up and running, it does seem to connect and occasionally round-trip data; mysterious things happen).

2. I'm not a Kafka expert, so I was surprised to see things like "nothing more to read now" surface as an error (`PartitionEOF`) rather than the absence of a message. I imagine that is just what `rdkafka` thinks is best and returns to you, so you want to surface it up?

3. The `BaseProducer` documentation speaks of a `BaseProducerTopic` that I should use, but I couldn't find this. Is it just stale documentation?

4. I was hoping to have a non-blocking `poll`, but I'm not sure if this is what an argument of `0` would mean. Sometimes `0` means "block". Is that something you could clarify in the documentation? It could be that `rdkafka` does what it does and won't let us `fcntl` the socket to non-blocking mode, or something like that, but would be good to know!

Maybe as a meta comment, if `BaseProducer` and `BaseConsumer` are meant to be a very thin layer on top of `rdkafka`, with the caveat that you had best understand the details of `rdkafka` (which I don't yet), you could say that in the documentation (I'm still not sure). I'm sure it is still useful, but would keep me from scratching / banging my head.

I'm going to try out the "higher-level" stuff next, but I'd have preferred to just have a non-blocking polling interface. If that *should* work out, and I just need more Kafka protocol expertise, I can push on it more and come back with comments on that.

Thanks again!

**Comment by frankmcsherry** [comment]
Ah, another "issue": 

1. I occasionally saw a 20s delay between the 100th `"got nothing"` and the method returning (the main program prints something when the method returns). Administrative commands on ZK and Kafka seem to take maybe 10s on my laptop, plausibly because of JVM start-up and such. Is it possible that this is catching the `Drop` implementation?

**Comment by fede1024** [comment]
Thank you for your feedback! The base clients in particular are, as you correctly said, just a thin layer on top of librdkafka, so they inherit most of their behavior from it. Having the feedback from users of the rust crate which are not familiar with the C library is super helpful to identify what makes the library hard to use for newcomers. I'll try to answer to your questions and to come up with longer term solutions to make sure other users won't have the same issues.

1) librdkafka uses background threads for IO so this kind of errors are not reported when the client is used directly. Instead, they result in calls to the `error` method in the `Context` trait. The [default implementation](https://github.com/fede1024/rust-rdkafka/blob/d3a3dda8ce6941cf88350f590dea399674987163/src/client.rs#L45) will just log it, but users can define their own contexts to handle it explicitly. Unfortunately the log line doesn't show up if the logging is not initialized (I'll post a working version later - `env_logger::init()` should do the trick). I'll add it to the documentation and try to have some default initialization.

2) That is the librdkafka default. You can disable it with `.set("auto.partition.eof", "false")` in the client config.

3) Yes! Stale documentation. Topic structs are not needed anymore. I'll fix that, thanks!

4) Looking at the librdkafka documentation, `0` means non-blocking, however it doesn't seem to work properly in my experiments. I suggest using the higher lever consumer, where a background thread will take care of polling and will communicate via a stream.

5) That shouldn't happen. It is likely the some `Drop` are indeed blocking. If it happens regularly, can you try reproducing it with [logging enabled](https://github.com/fede1024/rust-rdkafka#debugging)? If you can find in which drop the code blocks, it would be great. I don't seem to be able to reproduce it with your code (are you using the latest release?). Enabling the rdkafka logging with `RUST_LOG='rdkafka=trace'` should be enough.

Moreover, producing before the consumer is fully initialized can cause some strange behavior (for example some messages might be produced before the consumer find out what the latest offset is, and will be skipped). I suggest calling `consumer.poll()` a bunch of times before the producer starts; in this way it will be able to join the consumer group and get the partitions assigned.

I'll post an improved version of the code and fix the docs. Thanks for your feedback! Let me know if you find other unclear behavior. For quicker support, I suggest the gitter channel.

**Comment by frankmcsherry** [comment]
Thanks very much! I'll keep feeding you information about my experience. In particular, I think I've been hitting an issue that your suggestion about `consumer.poll()` may address (sending one element and expecting to find it, without polling a bit before sending).

I'll check out the docs! I'm guessing there are a few more parameters I should consider sending (e.g. the equivalent of "from beginning"), but due to the magic of the arguments being text strings, they are hard to discover (and me searching for `rdkafka` rather than `librdkafka`; I've found Confluents docs now).

I'll also tweak the methods so they track drop calls. I haven't seen it recently, which may mean it was my fault somewhere. But, if I can reconstruct it happening, I'll report what triggers it.

**Comment by frankmcsherry** [comment]
Hello! I'm back with a status update. 

Things seem to work well enough with a 1s poll for consumer and producer. I'd eventually like to sort out how to always start at the beginning of the stream, which I think has something to do with `"auto.offset.reset"` and `"earliest"`, but I haven't gotten this to work yet.

Instead, I'm trying to get a `BaseProducer` that can tell me when it has delivered messages. I'm reading through the source, and is it correct that Kafka is only willing to acknowledge receipt of data through a per-message callback? There are no sequence number and watermarks, or anything like that? 

I've avoided the `FutureProducer` because I didn't feel I needed another thread pool flopping around, but .. is this the only way to get delivery confirmations (short of writing my own callbacks)?

**Comment by frankmcsherry** [comment]
Btw, if it is helpful for context, this is in support of a timely dataflow adapter, the beginnings of which are here:

https://github.com/frankmcsherry/timely-dataflow/blob/master/kafkaesque/src/lib.rs

with example programs (that work as long as you start the receiver before the sender, due to start-up race / me not knowing how to get a `BaseConsumer` to start at zero offset): 

https://github.com/frankmcsherry/timely-dataflow/blob/master/kafkaesque/src/bin/capture_send.rs
https://github.com/frankmcsherry/timely-dataflow/blob/master/kafkaesque/src/bin/capture_recv.rs

They are much further along because of this crate, tyvm!

**Comment by fede1024** [comment]
For consuming always from the beginning, you need something like:

```rust
let consumer = ClientConfig::new()
        // [...]
        // Do not commit the offset automatically. There will be no offset associated to this
        // consumer.
        .set("enable.auto.commit", "false")
        .set_default_topic_config(TopicConfig::new()
            // This regulates what to do when there is no offset stored for the consumer. With "smallest",
            // start from the smallest offset (the oldest message).
            .set("auto.offset.reset", "smallest")  // Start
            .finalize())
        .create::<BaseConsumer<_>>()
        .expect("Consumer creation failed");
```

The per-message callback can be defined by implementing the `delivery` function in [ProducerContext](https://fede1024.github.io/rust-rdkafka/rdkafka/producer/trait.ProducerContext.html). The function is called every time a message is delivered or failed, and it receives a `DeliveryReport` as argument, which contains the partition and offset number of the message (if succeeded). The `ProducerContext` also allows you to specify a `DeliveryContext`, which is defined when the message is produced and can be used to identify it.

**Comment by frankmcsherry** [comment]
Thank you very much (for the Kafka tutorial, which I should probably have been able to do on my own; I apologize!). 

I have tracked down and implemented a `delivery` that adjusts an `Arc<AtomicIsize>`, which was less painful than I expected (I'm not sure what I expected, but terror was on the menu). It seems to work great now.

I'll give the config example you have a try and see if it works too! 

Right now, I'm moving 100M u64 numbers through a `localhost` Kafka instance in 8KB writes at .. about 5MB/s. I'm guessing it is supposed to be higher than that (if you believe Confluent's literature), though I'm not sure what the limiting factor is. `java` is hogging the CPU, so I'm guessing I'm stressing out Kafka somehow; is it correct that the `rdkafka` code linked against is JVM-free?

I'll keep reporting back, and any time I sound skeptical, read it as "I am deeply appreciative that I can do this at all"; I don't always make that clear. :)

**Comment by fede1024** [comment]
Here is [an example](https://pastebin.com/YA02GWSp) that i was working on, but you figured out most of it already :) 

I'm not sure what you mean by "JVM-free". It is pure Rust+C if this is what you are referring to.

Yes 5MB/s doesn't sound like much. Let me know if you manage to speed it up (there are a lot of parameters for the producer).

Thanks for reporting back! There is definitely a lot to improve in the documentation and in the code, so please keep the feedback coming :) and once your adapter is mature (or when you feel like it), you might add your project as one of the users listed in the rdkafka homepage, as it would help advertise the library.

**Comment by frankmcsherry** [comment]
Sorry, the "JVM-free" question was about many of the Apache tools, which just happily link a JVM in for you, in the interest of simplicity. It sounds like not!

I think the issue is on the consumer side; your suggestions about topic configuration made it so that I could replay streams just fine, and I can now replay an 80MB stream in about 12s (up to 6.66MB/s). I'm guessing the size of the writes shouldn't matter at this point, and `rdkafka` should be able to return multiple written items in one batch, if so inclined. But, the cores are still pegged (there seem to be three threads working here: I have a busy-waiter polling the `BaseConsumer`, there is the `rdkafka` thread, and then another thread in the `java` process).

I can kick at some parameters, but I have to admit being pretty ignorant about Kafka and what to expect. That's not on you to fix, though. :D

**Comment by frankmcsherry** [comment]
Some datas:

Using the project linked up above, which has both a producer to load up some data (`capture_send`) and a consumer to read it out again (`capture_recv`), I can load up 10M u64s in about 4s, and read them back again in about 12s.

The producer side:

```
Echidnatron% time cargo run --release --bin capture_send -- hamburger123456789 10000000
    Finished release [optimized] target(s) in 0.0 secs
     Running `target/release/capture_send hamburger123456789 10000000`
allocating producer for topic "hamburger123456789-0"
cargo run --release --bin capture_send -- hamburger123456789 10000000  0.37s user 0.50s system 20% cpu 4.108 total
Echidnatron%
```

and then afterwards (not overlapping), the consumer side:

```
Echidnatron% time cargo run --release --bin capture_recv -- hamburger123456789 1
    Finished release [optimized] target(s) in 0.0 secs
     Running `target/release/capture_recv hamburger123456789 1`
allocating consumer for topic "hamburger123456789-0"
cargo run --release --bin capture_recv -- hamburger123456789 1  6.41s user 9.01s system 128% cpu 11.986 total
Echidnatron%
```

The `decode` logic on the receive side is super simple (roughly a memcpy). It does seem like Kafka itself is stressed out (based on the `java` process CPU utilization). Are there other consumer options, for example setting/increasing the number of batched reads it does? I've also tried with auto-commit for the consumer, in case having large numbers of uncommitted reads was the source of issue (it didn't improve anything).

I'm not sure if you have much insight into Kafka, but if you see the same sorts of performance I'd be interested to know!

**Comment by frankmcsherry** [comment]
I improved the time on the consume side a little by changing the consumer `poll` from a timeout of zero to one.

```
Echidnatron% time cargo run --release --bin capture_recv -- hamburger1234567890 1
    Finished release [optimized] target(s) in 0.0 secs
     Running `target/release/capture_recv hamburger1234567890 1`
allocating consumer for topic "hamburger1234567890-0"
cargo run --release --bin capture_recv -- hamburger1234567890 1  1.34s user 3.16s system 46% cpu 9.655 total
Echidnatron%
```

This doesn't seem to change the amount of work `java` is doing, but seems to take some load off of the CPU so that there is less competition for cycles. It also cuts out spammy polling, as there should be at most 10k or so calls over the experiment (rather than "unbounded").

The program `capture_recv` still seems to be at about 40% CPU utilization over the 10s, suggesting that it is doing some non-trivial work in the copying of the 80MB. But it seems to be less than `java`.

**Comment by frankmcsherry** [comment]
By comparison, if I use a socket (just as an implementor of `Read` and `Write`) using the timely examples (with numbers changed appropriately, and printing in recv commented out)

https://github.com/frankmcsherry/timely-dataflow/blob/master/examples/capture_send.rs
https://github.com/frankmcsherry/timely-dataflow/blob/master/examples/capture_recv.rs

the elapsed time is about 0.2s, which seems not reasonable for 80MB (it's loopback tcp; not sure what that tops out at).

```
Echidnatron% time cargo run --release --example capture_send
    Finished release [optimized] target(s) in 0.0 secs
     Running `target/release/examples/capture_send`
cargo run --release --example capture_send  0.10s user 0.09s system 85% cpu 0.224 total
Echidnatron%
```

Cranking it up to 100M elements (so roughly 800MB), the time sneaks up to just over a second, which sound a little better.

```
Echidnatron% time cargo run --release --example capture_send
    Finished release [optimized] target(s) in 0.0 secs
     Running `target/release/examples/capture_send`
cargo run --release --example capture_send  0.47s user 0.57s system 91% cpu 1.140 total
Echidnatron%
```

I mention this mostly to try and remove "timely overhead" from the source of concern. It could still totally be that it is badly behaved in some other way, though. :)

**Comment by fede1024** [comment]
The overhead added by rdkafka on the consumer side should be very small (while it's a bit higher on producer side, since at the moment only a "copy" version is implemented). I suggest testing the Java console consumer (or writing a simple Java consumer) and check what the performance is. I did some benchmarks in the past; I'll try to find it and share the results.

**Comment by fede1024** [comment]
It looks like [librdkafka issue 1384](https://github.com/edenhill/librdkafka/issues/1384) might explain the slow consumer. In my tests the latest librdkafka master version is ~10x faster, now that the bug is fixed. You can try it out by cloning rust-rdkafka, going in rdkafka-sys/librdkafka (after initializing the submodule), then checking out the latest librdkafka master.

**Comment by frankmcsherry** [comment]
Oh hey, that does look suspicious, doesn't it. :)

I've tried to build as you described, but I'm afraid I've screwed something up along the way. I wandered into `rdkafka-sys/librdkafka`, ran instructions as in `README.md` (i.e. `git submodule update  --init`, then `bindgen ... src/bindings/macos.rs`).

Having doe that, `cargo build` craps out with 

```
Echidnatron% cargo build
   Compiling rdkafka-sys v0.11.0-0 (file:///Users/mcsherry/Projects/temporary/rust-rdkafka/rdkafka-sys)
error: expected one of `!` or `::`, found `/`
 --> src/bindings/macos.rs:1:11
  |
1 | librdkafka/src/rdkafka.h:44:9: warning: #pragma once in main file [-Wpragma-once-outside-header], err: false
  |           ^ expected one of `!` or `::` here

error: aborting due to previous error

error: Could not compile `rdkafka-sys`.

To learn more, run the command again with --verbose.
Echidnatron%
```

I'm afraid I'm not familiar enough with bindgen, and stuff like that (perhaps I should learn!), but if this is (i) obviously my fault and is fixable, or (ii) obviously not my fault and is fixable, or (iii) this will eventually be fixed in the next release of xyz, or (iv) I'm not sure what the other options are. :)

But thank you for noticing this. It means I don't have to write a snarky blog post about Kafka perf. :D

Frank

**Comment by frankmcsherry** [comment]
Well, I've tried this out. It has not yet resulted in improved performance, but it is possible that I've messed something up along the way. I did regenerate the bindings as suggested, and am now pointed at a local `rust-rdkafka`. Other than the warning, things seemed to go as planned.

Let me walk through what I did, and you tell me if I've missed something obvious to you:

```
> git clone https://github.com/fede1024/rust-rdkafka
> cd rust-rdkafka
> cd rdkafka-sys
> git submodule update --init
> bindgen --builtins --no-doc-comments librdkafka/src/rdkafka.h > src/bindings/macos.rs
> nano src/bindings/macos.rs
```

That last line is to delete the warning that gets printed as the first line of `macos.rs`.

Now, elsewhere (back in the project I'm working on), we patch up a few errors (apparently there is a `Consumer` trait now! good indication that I'm using a new version), and do 

```
> cargo run --release --bin capture_send -- womboozle 10000000
    Finished release [optimized] target(s) in 0.0 secs
     Running `target/release/capture_send womboozle 10000000`
allocating producer for topic "womboozle-0"
>
```

This sends 10M `usize` entries from `0 ..` into a topic `womboozle`. I was running out of names. I didn't time it.

Now we run the receiver (who was actually rebuilt, but I reran afterwards to avoid timing the build), which just reads the 80MB worth of `usize` data:

```
> time cargo run --release --bin capture_recv -- womboozle 1 
    Finished release [optimized] target(s) in 0.0 secs
     Running `target/release/capture_recv womboozle 1`
allocating consumer for topic "womboozle-0"
cargo run --release --bin capture_recv -- womboozle 1  6.13s user 9.00s system 131% cpu 11.512 total
>
```

This ends up around 7MB/s, which is technically more than before, but not 10x or anything.

My best guess is that I don't have the most recent `rdkafka` (based on looking at recent commits to master, and looking for them in the directory), though I'm not clear how to refresh it. My understanding is that `git submodule update --init` was supposed to do this.

**Comment by frankmcsherry** [comment]
Ooo, something changed! I'm not sure exactly what, but (having random wandered around, deleted things, re-pulled things, etc), we are now seeing decent performance!

```
> time cargo run --release --bin capture_send -- womboozle2 100000000
    Finished release [optimized] target(s) in 0.0 secs
     Running `target/release/capture_send womboozle2 100000000`
allocating producer for topic "womboozle2-0"
cargo run --release --bin capture_send -- womboozle2 100000000  2.78s user 4.27s system 31% cpu 22.061 total
> 
```

This is 800MB produced in 22s, which .. is 40MB/s which is much better. So so, but much better. On the read side, though: 

```
> time cargo run --release --bin capture_recv -- womboozle2 1 
    Finished release [optimized] target(s) in 0.0 secs
     Running `target/release/capture_recv womboozle2 1`
allocating consumer for topic "womboozle2-0"
replayed: 100000000
cargo run --release --bin capture_recv -- womboozle2 1  1.00s user 0.50s system 111% cpu 1.347 total
>
```

That's 800MB (I even counted the records to be sure) in a bit over a second, so 600MB/s? Pretty solid there!

**Comment by fede1024** [comment]
You can check the version of librdkafka being used with the `get_rdkafka_version` function. It should look something like "0.11.0-RC1-76-g88db65". I pushed a change to master to use the latest librdkafka version and with updated linux bindings (I'll update macos bindings tomorrow).

600MB/s seems suspiciously fast! :)

**Comment by frankmcsherry** [comment]
Thanks!

The 600MB/s is fast, but it is the same rate I see with loopback tcp using my own communication. Also, the 100M number printed out is .. only arrived at by virtue of reading and counting everything sent; the `capture_recv` process has no other insight into the number of records transmitted. Also, I've been a bit hard on Kafka, so it feels good being wrong about it. ;)

**Comment by frankmcsherry** [comment]
I'm likely to write about this at some point (using Rust + Kafka, in the context of timely dataflow). Let me know when you think it is in a state that if some randoms come by and try to use it, they are likely to get the right bits. I'll double check from scratch before posting anything, but at the moment the experience is pretty pleasant (and I wanted to show that to others).

**Comment by fede1024** [comment]
I'm not planning any big change to the API, however there are few
improvements to the documentation that I'd like to add soon (add an FAQ
page and a common configurations page).
Once that's done and the new version of librdkafka is out, the library
should be easier to use, and having a blogpost mentioning it would be great.

Thank you for all the feedback so far!

**Comment by fede1024** [comment]
I managed to squeeze out some serious performance out of the BaseProducer (see [readme](https://github.com/fede1024/rust-rdkafka#one-million-messages-per-second)). You can also check [the benchmark code](https://github.com/fede1024/kafka-benchmark) (I still have to clean it up a bit).

**Comment by frankmcsherry** [comment]
This is good info, thank you. Did you change `BaseProducer`, or is this just well-written benchmark code around it? I've re-pulled and retried my benchmark code and still get 

    cargo run --release --bin capture_send -- blah2 100000000  2.80s user 4.21s system 37% cpu 18.715 total

about 18s to send 800MB, which is still not up at your speeds. When I check out ActivityMonitor.app, I do see that the application that I've written takes minimal time, and `java` is the main culprit. I'll check out your benchmark and see if there are clear things I can try and fix (e.g. the sender I've written is open loop, and may be overloading Kafka; perhaps if I make sure there is at most one (or few) outstanding writes at a time it could improve).

**Comment by fede1024** [comment]
While writing the benchmark I realized that where you call poll() in the code plays a very important role. I didn't managed to get decent performance until I used the same strategy that is used in the librdkafka performance test.

Are you using the default kafka configuration?

PS i just realized that i forgot to push the cargo file for the benchmark. It's pushed now.

**Comment by frankmcsherry** [comment]
I'm using the "quickstart" kafka instructions, which is just the default

    bin/kafka-server-start.sh config/server.properties

In particular, new topics are created with a partition of size one, which could also be an important difference. I'm going to check out where you've put your `poll`s to see if they are very different than mine. :)

**Comment by frankmcsherry** [comment]
I've just checked out the benchmark and run it. I made sure to create a topic with partition of size three ahead of time, but didn't do anything else (perhaps I should have). The results are much less than you get, which maybe suggests that something about my set-up is suboptimal. I'm guessing one difference is that I'm on OSX and you are on Linux; are there other non-standard Kafka/ZK configuration parameters that you are using?

```
Echidnatron% cargo run --release -- --config producer_benchmark_config.yaml --scenario byte_flow_bursts
    Finished release [optimized] target(s) in 0.0 secs
     Running `target/release/kafka-benchmark --config producer_benchmark_config.yaml --scenario byte_flow_bursts`
Scenario: byte_flow_bursts, repeat 5 times, 10s pause after each
Not enough acknowledgements received. Expected 100000, received 27649
* Produced 27649 messages (263.681 MB) in 11.067 seconds using 1 thread
    2498 messages/s
    23.826 MB/s
Not enough acknowledgements received. Expected 100000, received 28289
* Produced 28289 messages (269.785 MB) in 10.986 seconds using 1 thread
    2575 messages/s
    24.557 MB/s
Not enough acknowledgements received. Expected 100000, received 26952
* Produced 26952 messages (257.034 MB) in 11.182 seconds using 1 thread
    2410 messages/s
    22.986 MB/s
Not enough acknowledgements received. Expected 100000, received 30558
* Produced 30558 messages (291.424 MB) in 11.069 seconds using 1 thread
    2761 messages/s
    26.328 MB/s
Not enough acknowledgements received. Expected 100000, received 28095
* Produced 28095 messages (267.935 MB) in 11.080 seconds using 1 thread
    2536 messages/s
    24.182 MB/s
Average: 2556 messages/s, 24.371 MB/s
Echidnatron% 
```

Here is a fairly typical system usage:

<img width="492" alt="screen shot 2017-09-15 at 07 03 01" src="https://user-images.githubusercontent.com/5741500/30479680-552ff9f6-99e4-11e7-88df-5e969bee940b.png">

suggesting that `java` (or Kafka's use of java) is the real problem here. It is possible that it is just that java on OSX isn't as clever as on Linux?

**Comment by fede1024** [comment]
From the "not enough acks received" it looks like you hit the 10 seconds
flush timeout. You can try incresing the flush to a few minutes. I'll try
on my mac and see if the OS can play such a big role.

**Comment by frankmcsherry** [comment]
I've got more data for you. I'm just going to hit you with all of it (it is a bit of a story), and we can try and pick out the pieces together. 

First, I shut down Kafka and ZK and cleared out `/tmp` of anything of theirs. Then I re-ran your benchmark, and hooray! Good numbers

```
Echidnatron% cargo run --release -- --config producer_benchmark_config.yaml --scenario byte_flow_bursts
    Finished release [optimized] target(s) in 0.0 secs
     Running `target/release/kafka-benchmark --config producer_benchmark_config.yaml --scenario byte_flow_bursts`
Scenario: byte_flow_bursts, repeat 5 times, 10s pause after each
* Produced 100000 messages (953.674 MB) in 3.717 seconds using 1 thread
    26903 messages/s
    256.571 MB/s
* Produced 100000 messages (953.674 MB) in 3.216 seconds using 1 thread
    31095 messages/s
    296.541 MB/s
* Produced 100000 messages (953.674 MB) in 3.244 seconds using 1 thread
    30826 messages/s
    293.981 MB/s
* Produced 100000 messages (953.674 MB) in 4.751 seconds using 1 thread
    21048 messages/s
    200.731 MB/s
* Produced 100000 messages (953.674 MB) in 4.805 seconds using 1 thread
    20812 messages/s
    198.475 MB/s
Average: 25336 messages/s, 241.620 MB/s
```

Then I went over and ran my program, and .. bad numbers.

```
Echidnatron% time cargo run --release --bin capture_send -- blah7 100000000
    Finished release [optimized] target(s) in 0.0 secs
     Running `target/release/capture_send blah7 100000000`
allocating producer for topic "blah7-0"
cargo run --release --bin capture_send -- blah7 100000000  21.99s user 1.08s system 101% cpu 22.626 total
Echidnatron%
```

Then I immediately went and reran your benchmark and, bad numbers

```
Echidnatron% cargo run --release -- --config producer_benchmark_config.yaml --scenario byte_flow_bursts
    Finished release [optimized] target(s) in 0.0 secs
     Running `target/release/kafka-benchmark --config producer_benchmark_config.yaml --scenario byte_flow_bursts`
Scenario: byte_flow_bursts, repeat 5 times, 10s pause after each
Not enough acknowledgements received. Expected 100000, received 30648
* Produced 30648 messages (292.282 MB) in 11.125 seconds using 1 thread
    2755 messages/s
    26.273 MB/s
Not enough acknowledgements received. Expected 100000, received 30271
* Produced 30271 messages (288.687 MB) in 11.031 seconds using 1 thread
    2744 messages/s
    26.170 MB/s
^C
Echidnatron%
```

I restarted Kafka, still bad numbers. I restarted Kafka and ZK, still bad numbers (actually, especially bad numbers: `14.622 MB/s`). I restarted Kafka and ZK having deleted the logs (recreating the benchmark topic, with 3 parts), and **great** numbers. I `^C` your benchmark after three rounds, and run it again, and ... **degrading** numbers. Check it out:

```
Echidnatron% cargo run --release -- --config producer_benchmark_config.yaml --scenario byte_flow_bursts
    Finished release [optimized] target(s) in 0.0 secs
     Running `target/release/kafka-benchmark --config producer_benchmark_config.yaml --scenario byte_flow_bursts`
Scenario: byte_flow_bursts, repeat 5 times, 10s pause after each
* Produced 100000 messages (953.674 MB) in 4.849 seconds using 1 thread
    20623 messages/s
    196.674 MB/s
* Produced 100000 messages (953.674 MB) in 5.987 seconds using 1 thread
    16703 messages/s
    159.291 MB/s
Not enough acknowledgements received. Expected 100000, received 66398
* Produced 66398 messages (633.221 MB) in 11.189 seconds using 1 thread
    5934 messages/s
    56.593 MB/s
Not enough acknowledgements received. Expected 100000, received 30498
* Produced 30498 messages (290.852 MB) in 11.079 seconds using 1 thread
    2753 messages/s
    26.253 MB/s
Not enough acknowledgements received. Expected 100000, received 27666
* Produced 27666 messages (263.844 MB) in 11.085 seconds using 1 thread
    2496 messages/s
    23.802 MB/s
Average: 7345 messages/s, 70.044 MB/s
Echidnatron%
```

Something about Kafka is going to crap the more logs get produced, in a way that seems to reset with the logs being cleared out. I have about 30GB of free space on the SSD, so that doesn't seem to be the hard time it is having.

**Comment by frankmcsherry** [comment]
Final experiment, I upped the number of rounds from five to nine, and get degrading performance within the first run post log cleaning:

```
Echidnatron% cargo run --release -- --config producer_benchmark_config.yaml --scenario byte_flow_bursts
    Finished release [optimized] target(s) in 0.0 secs
     Running `target/release/kafka-benchmark --config producer_benchmark_config.yaml --scenario byte_flow_bursts`
Scenario: byte_flow_bursts, repeat 9 times, 10s pause after each
* Produced 100000 messages (953.674 MB) in 3.598 seconds using 1 thread
    27793 messages/s
    265.057 MB/s
* Produced 100000 messages (953.674 MB) in 3.364 seconds using 1 thread
    29727 messages/s
    283.494 MB/s
* Produced 100000 messages (953.674 MB) in 2.986 seconds using 1 thread
    33490 messages/s
    319.382 MB/s
* Produced 100000 messages (953.674 MB) in 5.347 seconds using 1 thread
    18702 messages/s
    178.357 MB/s
* Produced 100000 messages (953.674 MB) in 5.061 seconds using 1 thread
    19759 messages/s
    188.436 MB/s
Not enough acknowledgements received. Expected 100000, received 71154
* Produced 71154 messages (678.577 MB) in 11.029 seconds using 1 thread
    6452 messages/s
    61.527 MB/s
Not enough acknowledgements received. Expected 100000, received 30697
* Produced 30697 messages (292.749 MB) in 11.114 seconds using 1 thread
    2762 messages/s
    26.341 MB/s
Not enough acknowledgements received. Expected 100000, received 28003
* Produced 28003 messages (267.057 MB) in 11.190 seconds using 1 thread
    2503 messages/s
    23.866 MB/s
Not enough acknowledgements received. Expected 100000, received 28960
* Produced 28960 messages (276.184 MB) in 11.100 seconds using 1 thread
    2609 messages/s
    24.881 MB/s
Average: 10168 messages/s, 96.969 MB/s
Echidnatron% 
```

**Comment by frankmcsherry** [comment]
Ok, good answers now! I think it is a free space issue. At least, having cleaned up 40GB more space (so 70GB free total), it seems like your benchmark immediately returns to good performance (without log cleaning) and my benchmark jumps up too

```
Echidnatron% time cargo run --release --bin capture_send -- blah8 100000000
    Finished release [optimized] target(s) in 0.0 secs
     Running `target/release/capture_send blah8 100000000`
allocating producer for topic "blah8-0"
cargo run --release --bin capture_send -- blah8 100000000  4.16s user 1.15s system 110% cpu 4.812 total
Echidnatron% 
```

This is about 200MB/s for me, which is understandably less than yours (it is also serializing data, allocating, hogging the cpu busy-waiting etc).

I don't know why 30GB free is a scary number, nor why it just throttles writing rather than e.g. failing if it thinks there isn't enough space. Is there a built-in Kafka "backpressure" when it thinks you are about to blow your disks?

**Comment by fede1024** [comment]
I don't know of any such backpressure mechanism in Kafka. I suspect that the operating system will decide to slow down writes when the free space on disk is getting low (even though 30GB is not that low). I wonder why this slow down shows up as CPU usage in Kafka, since I'm pretty sure that the CPU is just waiting

Do you see a similar CPU usage in the latest test?

**Comment by frankmcsherry** [comment]
It's definitely not the OS (at least, I can comfortably write at hundreds of MB/s up until I run out of space; have done so ;)). It might be the JVM?

With more space, `java` remains 100%, but we now see good throughput. So, it is still the bottleneck (200MB/s is about 1/3 what my SSD supports, IIRC), but much less of a painful one than before.

**Comment by frankmcsherry** [comment]
But, it all looks pretty good. Will there need to be a bump to 0.13.0 to pick up the new librdkafka bits, or do they get pulled by lesser versions when librdkafka mints a new release?

**Comment by fede1024** [comment]
Yes I'll make a new 0.13.0 version when the new librdkafka version is released.

**Comment by frankmcsherry** [comment]
Tyvm!

**Comment by frankmcsherry** [comment]
Ooo, I just noticed that 0.13.0 is out! I'm going to try it out from scratch and see if all the good performance sticks around!

**Comment by frankmcsherry** [comment]
Yeah, it looks good. Using just 0.13.0 I see on the write side (producer):

```
Echidnatron% time cargo run --release --bin capture_send wombat4 100000000
    Finished release [optimized] target(s) in 0.0 secs
     Running `target/release/capture_send wombat4 100000000`
allocating producer for topic "wombat4-0"
cargo run --release --bin capture_send wombat4 100000000  1.40s user 1.47s system 58% cpu 4.929 total
Echidnatron%
```

which is 800MB in 5 seconds, about the same as up above (though, with less user time; maybe just bottlenecked elsewhere).

On the read side (consumer), I see

```
Echidnatron% time cargo run --release --bin capture_recv wombat3 1
    Finished release [optimized] target(s) in 0.0 secs
     Running `target/release/capture_recv wombat3 1`
allocating consumer for topic "wombat3-0"
replayed: 100000000
cargo run --release --bin capture_recv wombat3 1  1.05s user 0.55s system 103% cpu 1.550 total
Echidnatron%
```

which is 800MB read back in 1.5s, which is pretty speedy. :D

My next plan is to do a little write-up of how all this works, probably with more attention paid to what I understand on my end and less about how rust-rdkafka works (the surface seems pretty tidy in the code I have; I could be missing lots of important things, though). 

You had asked before about being in a list of folks using rust-rdkafka; happy to participate if you'll have me. ;)

**Comment by fede1024** [comment]
Thank you for trying it out! There are a few additional changes in master that I'd like to release in an upcoming version. If you could try it as well it would be great (there are a few small changes to the API, any feedback would be appreciated).

Sure, I'll add a link to your project, thanks! :)
