### ISSUE TITLE
"/usr/bin/ld:librdkafka.lds:1: syntax error in VERSION script" error.

### ISSUE THREAD

**Issue by jerry-sl** [fede1024/rust-rdkafka#57]
I got compile error "/usr/bin/ld:librdkafka.lds:1: syntax error in VERSION script"  when i use rdkafka.

cargo.toml config:

[dependencies]
rdkafka = "^0.12.0"
rdkafka-sys="0.11.0-0"

Env:
Vagrant +  ubuntu/xenial64 box.

rustc --version
rustc 1.21.0-nightly (1d2a6df38 2017-08-03)

[verbose error output](https://gist.github.com/jerry-sl/9b24ec6e75f767c25ff8ff8631059b13)

Sorry for my poor english, any infomation will help. thx.

**Comment by fede1024** [comment]
Thanks for the report! Can you send me the vargrant configuration so that i can try to replicate the issue?

**Comment by jerry-sl** [comment]
Vagrant.configure("2") do |config|
       config.vm.box = "ubuntu/xenial64"
end

**Comment by fede1024** [comment]
Thanks for the report! It looks like something goes wrong in the build of librdkafka (the C library).

From my tests it seems that the master branch compiles file. Can you give it a try? I tested it by creating an empty project and by adding the git repo as dependency:
```toml
rdkafka = { git = "https://github.com/fede1024/rust-rdkafka.git" }
```

**Comment by jerry-sl** [comment]
Finally I got a solution. 
Replace 
```
rdkafka-sys::RDKafkaTopicPartitionList
```
with 
```
rdkafka::types::RDKafkaTopicPartitionList
```

and delete `rdkafka-sys="0.11.0-0"` dependency.

**Comment by jerry-sl** [comment]
Master branch solved my problem.
```
[dependencies.rdkafka]
git = "https://github.com/fede1024/rust-rdkafka.git"
rev = "84d4062"
```

Change `rdkafka-sys::RDKafkaTopicPartitionList`  to ` rdkafka::types::RDKafkaTopicPartitionList` .

Thanks for your help.
