### ISSUE TITLE
musl-g++ not found when compiling for x86_64-unknown-linux-musl 

### ISSUE THREAD

**Issue by WaterKnight1998** [fede1024/rust-rdkafka#571]
Afternoon,

I tried to compile like follows: `cargo build --release --target=x86_64-unknown-linux-musl `

My toml was like this:

```
rdkafka = { version = "0.29.0", features = ["cmake-build", "ssl-vendored"]}
```

I got the following error:
```
  --- stderr
  Building and linking librdkafka statically
  CMake Error at CMakeLists.txt:6 (project):
    The CMAKE_CXX_COMPILER:

      musl-g++

    is not a full path and was not found in the PATH.

    Tell CMake where to find the compiler by setting either the environment
    variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
    to the compiler, or to the compiler name if it is in the PATH.


  thread 'main' panicked at '
  command did not execute successfully, got: exit status: 1

  build script failed, must exit now', /home/david/.cargo/registry/src/github.com-1ecc6299db9ec823/cmake-0.1.50/src/lib.rs:1098:5
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by benesch** [comment]
Sorry, but this is not the right forum for debugging issues with your cross compiling toolchain. If you have a demonstrable bug, happy to look into it, but it appears that you do not have a C++ cross compiler on your machine, and fixing that is outside the scope of this project.

If you search past issues for "cross compiling", you can surface the setups of some other users who have successfully cross compiled to x86_64-unknown-linux-musl.
