### ISSUE TITLE
Delivery callback should have a reference to the message it is referring to

### ISSUE THREAD

**Issue by fede1024** [fede1024/rust-rdkafka#58]
The delivery callback for both producers doesn't give any information on which message failed, making retrying and error reporting sometimes impossible.

A possible solution is to add a BorrowedMessage parameter to the delivery callback.

**Comment by Kane-Sendgrid** [comment]
If you add BorrowedMessage to the callback it will hold slot in the producing queue? Also, usually you want to maintain order of inserts per partition, will it still possible to guarantee?

**Comment by fede1024** [comment]
It will hold the slot, but only for the duration of the delivery callback in the ProducerContext. Note that this was already the behaviour in librdkafka, but rust-rdkafka wasn't exposing it.

The new feature is now on master. You can have a look at the [docs](https://fede1024.github.io/rust-rdkafka/rdkafka/message/type.DeliveryResult.html) (more to come).
