### ISSUE TITLE
Update examples with default topic config passthrough

### ISSUE THREAD

**Issue by fede1024** [fede1024/rust-rdkafka#63]
From librdkafka 0.11 the default topic configuration can be set using `rd_kafka_conf_set` directly. The document in librdkafka can now be updated and simplified.

Additionally, the `TopicConfig` struct can be made private or removed, as it's not needed anymore (but it might be needed in the future if support on the producer side is added).

**Comment by Roguelazer** [comment]
So how is this done? `CONFIGURATION.md` in librdkafka says that `default_topic_conf` is of type pointer, which doesn't seem quote right.

**Comment by fede1024** [comment]
This was actually implemented in commit e94f3870972854bf15aca2824. `default_topic_conf` is not used by rust-rdkafka and it doesn't exist anymore. All the configurations that were once given to `TopicConfig` can now go directly to the top level configuration (example [here](https://github.com/fede1024/rust-rdkafka/commit/e94f3870972854bf15aca2824c5115462a5b8b13#diff-8929945bdb8f20138f8a40e585355c4dL74).
