### ISSUE TITLE
rust-rdkafka run error in Apple M1 Pro

### ISSUE THREAD

**Issue by bodypumper** [fede1024/rust-rdkafka#631]
# Computer
CPU：Apple M1 Pro
OS：macOS Monterey 12.3

# Information 
rust-rdkafka was used in the project, configured as rdkafka={version="0.36", features=["gssapi", "dynamic linking"]}. An error occurred during service startup. How can I handle it?

# Error Message
<img width="1512" alt="image" src="https://github.com/fede1024/rust-rdkafka/assets/44149782/080a1c02-7a6d-43f6-91c0-f4a7906d2294">

**Comment by scanterog** [comment]
@bodypumper can you provide a self contained example of the code that causes this? Is it only happening on 0.36?

**Comment by bodypumper** [comment]
> @bodypumper can you provide a self contained example of the code that causes this? Is it only happening on 0.36?

It can run in Windows, so may I need to download any plugins  to fix it ?

**Comment by bodypumper** [comment]
> @bodypumper can you provide a self contained example of the code that causes this? Is it only happening on 0.36?

It can run in Windows, so may I need to download any plugins to fix it ?
