### ISSUE TITLE
Support the LZ4 capability of librdkafka by creating a cargo feature that flips on the `--enable-lz4` librdkafka feature flag

### ISSUE THREAD

**Issue by jnicholls** [fede1024/rust-rdkafka#64]
rdkafka-sys depends upon `lz4-sys` but it doesn't appear to be involved in the building of librdkafka at the end of the day.  It would be great if there was a cargo feature for enabling the `--enable-lz4` feature flag of librdkafka so it will be statically linked in accordingly.

**Comment by fede1024** [comment]
From my tests it seems that lz4 support is enabled by default in librdkafka and it can already be used. I'll remove the lz4-sys dependency because librdkafka doesn't actually need it. I'll add a feature flag anyway (default on), since some users might want to disable it.

**Comment by fede1024** [comment]
The feature is now available (see `Cargo.toml`).
