### ISSUE TITLE
rust-rdkafka 0.13 is reporting production errors incorrectly

### ISSUE THREAD

**Issue by Roguelazer** [fede1024/rust-rdkafka#65]
0.13.0 is reporting production errors as `rdkafka::error::KafkaError::MessageConsumption` instead of `rdkafka::error::KafkaError::MessageProduction`. I assume this is because `err_field_to_kafka_error` now always returns `MessageConsumption`.

My code (which is production-only) was working under 0.12 but isn't under 0.13, so it seems like this is a regression?

Example: If I attempt to produce a message which is larger than the Kafka max message size, the Debug representation of the error is

    KafkaError (Message consumption error: MessageSizeTooLarge (Broker: Message size too large))

**Comment by fede1024** [comment]
Yes, there was indeed a bug in the way the error was converted from librdkafka to rust-rdkafka. It should be fixed now in master. Please try it out if you can. I plan to merge a few other minor improvements and release a new version with the fix soon.

**Comment by Roguelazer** [comment]
thanks!
