### ISSUE TITLE
memory appears to leak on consumer

### ISSUE THREAD

**Issue by leshow** [fede1024/rust-rdkafka#650]
I have a simple consumer using `StreamConsumer`:
```
   let consumer = self.config.create::<StreamConsumer>()?;
        consumer.subscribe(&[&self.topic])?;

        let mut stream = consumer.stream();
        loop {
            match stream.next().await.expect("stream never completes") {
                Ok(msg) => {
                    // Process each message
                    debug!(?msg, "got message");
                    tokio::time::sleep(std::time::Duration::from_millis(200)).await;
                }
                Err(err) => {
                    warn!(?err, "Connecting failed to event hub, attempting reconnect");
                    stream = consumer.stream();
                }
            }
        }
```
features:
```
rdkafka = { version = "0.36.2", features = [
    "tracing",
    "gssapi-vendored",
    "ssl-vendored",
] }
```

I'm seeing that when I send events faster than they can be processed, I get memory usage climbing pretty rapidly that never gets released. The logs don't show any errors. I have tried versions 0.34.0 and 0.36.2 and get the same behaviour. I'm using jemalloc. I can try to get a heap dump or something if that's helpful to debug.

edit: tried also with default allocator and noticed no difference. jemalloc is configured to use the "background_threads" feature.

**Comment by davidblewett** [comment]
@leshow can you provide your config settings? Also, how long did you observe the memory usage increase? Did it ever level off?

**Comment by leshow** [comment]
It did not appear to level off, my runs were in a docker container with 100mb of RAM, it appears to grow without bound at least until 100mb when the container would OOM and restart with the code above.

Here's the debug output for the ClientConfig:
```
{"sasl.mechanisms": "PLAIN", 
"security.protocol": "SASL_SSL", 
"enable.auto.commit": "false", 
"statistics.interval.ms": "500000", 
"group.id": "eidp-pipeline-sanity-test", 
"bootstrap.servers": "kafka.localhost:9094", 
"sasl.username": "user", 
"ssl.ca.location": "/etc/ssl/certs/kafka.ca.crt", 
"sasl.password": "password", 
"auto.commit.interval.ms": "0", 
"session.timeout.ms": "6000"}
```

I'm setting up a native run so I can try to get a dump from heaptrack and get more info.

**Comment by leshow** [comment]
If this helps:

[heaptrack.out (2).gz](https://github.com/fede1024/rust-rdkafka/files/14043026/heaptrack.out.2.gz)

a screenshot:
![Screenshot from 2024-01-24 14-56-07](https://github.com/fede1024/rust-rdkafka/assets/1128302/413b6585-5e6a-442a-a143-fd22ff705f0c)

**Comment by jasongoodwin** [comment]
I noticed there are some memory leaks noted in issues in lib rd kafka - may be related.
 https://github.com/confluentinc/librdkafka/issues/4486

**Comment by leshow** [comment]
I think this is due to `queued.max.messages.kbytes` where the default is 65_536 kbytes, in the container I was running, the max memory was being reached which is what caused the process to be killed. This queue is the pre-fetch amount on the consumer.

I'll close this issue.
