### ISSUE TITLE
How to batch insert headers?

### ISSUE THREAD

**Issue by funky-eyes** [fede1024/rust-rdkafka#685]
My scenario involves obtaining a batch of messages through a consumer and converting the headers, key, and value of each message into a new message to be sent to another topic. It can be seen as a Rust version of Kafka MirrorMaker. However, I am facing some issues while converting the headers. Could you please help me with resolving them? Thank you.

```
error[E0382]: use of moved value: `owned_headers`
   --> src/main.rs:82:25
    |
79  |                   let owned_headers = OwnedHeaders::new();
    |                       -------------   ------------------- this reinitialization might get skipped
    |                       |
    |                       move occurs because `owned_headers` has type `OwnedHeaders`, which does not implement the `Copy` trait
80  |                   if let Some(headers) = m.headers() {
81  |                       for header in headers.iter() {
    |                       ---------------------------- inside of this loop
82  |                           owned_headers.insert(Header {
    |  _________________________^^^^^^^^^^^^^_-
83  | |                             key: header.key,
84  | |                             value: header.value,
85  | |                         });
    | |__________________________- `owned_headers` moved due to this method call, in previous iteration of loop
    |

```

```
                let owned_headers = OwnedHeaders::new();
                if let Some(headers) = m.headers() {
                    for header in headers.iter() {
                        owned_headers.insert(Header {
                            key: header.key,
                            value: header.value,
                        });
                    }
                }
                let _  =  producer.send_result(FutureRecord::to(topic.as_str())
                    .key(key_bytes).headers(owned_headers)
                    .payload(payload_bytes)
                    .timestamp(m.timestamp().to_millis().unwrap()));
```

**Comment by Guyzeroth** [comment]
``` 
let mut owned_headers = OwnedHeaders::new();
                if let Some(headers) = m.headers() {
                    for header in headers.iter() {
                        owned_headers = owned_headers.insert(Header {
                            key: header.key,
                            value: header.value,
                        });
                    }
                }
                let _  =  producer.send_result(FutureRecord::to(topic.as_str())
                    .key(key_bytes).headers(owned_headers)
                    .payload(payload_bytes)
                    .timestamp(m.timestamp().to_millis().unwrap()));
```

(owned_headers.insert method takes `self` (not `&self `or `&mut self`)) ).

**Comment by funky-eyes** [comment]
> ```
> let mut owned_headers = OwnedHeaders::new();
>                 if let Some(headers) = m.headers() {
>                     for header in headers.iter() {
>                         owned_headers = owned_headers.insert(Header {
>                             key: header.key,
>                             value: header.value,
>                         });
>                     }
>                 }
>                 let _  =  producer.send_result(FutureRecord::to(topic.as_str())
>                     .key(key_bytes).headers(owned_headers)
>                     .payload(payload_bytes)
>                     .timestamp(m.timestamp().to_millis().unwrap()));
> ```
> 
> (owned_headers.insert method takes `self` (not `&self `or `&mut self`)) ) . a.ka. the method consumes the OwnedHeaders instance when it's called to continue using the object after the method call, you must use the returned OwnedHeaders instance.

I will try your suggestion. Thank you.

**Comment by funky-eyes** [comment]
I confirm that this can compile successfully. Thanks again.
