### ISSUE TITLE
failed build on Ubuntu 16.04

### ISSUE THREAD

**Issue by ongardie-ebay** [fede1024/rust-rdkafka#69]
When I tried cargo building this on Ubuntu 16.04, I encountered some linker errors:
```
Creating shared library librdkafka.so.1
gcc  -shared -Wl,-soname,librdkafka.so.1 -Wl,--version-script=librdkafka.lds rdkafka.o rdkafka_broker.o rdkafka_msg.o rdkafka_topic.o rdkafka_conf.o rdkafka_timer.o rdkafka_offset.o rdkafka_transport.o rdkafka_buf.o rdkafka_queue.o rdkafka_op.o rdkafka_request.o rdkafka_cgrp.o rdkafka_pattern.o rdkafka_partition.o rdkafka_subscription.o rdkafka_assignor.o rdkafka_range_assignor.o rdkafka_roundrobin_assignor.o rdkafka_feature.o rdcrc32.o crc32c.o rdaddr.o rdrand.o rdlist.o tinycthread.o rdlog.o rdstring.o rdkafka_event.o rdkafka_metadata.o rdregex.o rdports.o rdkafka_metadata_cache.o rdavl.o rdkafka_sasl.o rdkafka_sasl_plain.o rdkafka_interceptor.o rdkafka_msgset_writer.o rdkafka_msgset_reader.o rdvarint.o rdbuf.o rdunittest.o rdkafka_sasl_scram.o snappy.o rdgz.o rdkafka_lz4.o xxhash.o rddl.o rdkafka_plugin.o -o librdkafka.so.1 -Wl,-Bstatic -llz4 -Wl,-Bdynamic -lpthread -lz -lcrypto -lssl -lrt -ldl
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/liblz4.a(lz4frame.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/liblz4.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
../mklove/Makefile.base:88: recipe for target 'librdkafka.so.1' failed
make[1]: *** [librdkafka.so.1] Error 1
make[1]: Leaving directory '/home/stack/librdkafka/src'
Makefile:20: recipe for target 'libs' failed
make: *** [libs] Error 2
```

I didn't get to the root cause of this, but these errors can be avoided by not passing `--enable-static` to `./configure`. Without this flag, the rdkafka library appears to build a static library anyway, and it does so successfully.

Can we just remove `--enable-static` from `rdkafka-sys/build.rs`?

**Comment by messense** [comment]
```
liblz4.a(lz4frame.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
```

It seems that the lz4 package in your system isn't compiled with `-fPIC`

**Comment by fede1024** [comment]
Thanks for the report. Can you try compiling once without `--enable-static` and once with `--disable-lz4`?

**Comment by ongardie-ebay** [comment]
Sure. I ran everything in Docker this time so you can try this too.

Here's the Dockerfile I used:
```
FROM ubuntu:16.04
RUN apt-get update
RUN apt-get install -y \
  build-essential \
  git \
  python
RUN git clone https://github.com/edenhill/librdkafka.git
WORKDIR librdkafka
RUN git reset --hard b581d0d
```

From the directory containing that Dockerfile, I ran:
```
docker build -t rdkafka .
docker run rdkafka bash -c './configure && make' >log01.txt 2>&1
docker run rdkafka bash -c './configure --enable-static && make' >log02.txt 2>&1
docker run rdkafka bash -c './configure --enable-static --disable-lz4 && make' >log03.txt 2>&1
docker run rdkafka bash -c 'apt-get install -y liblz4-dev && ./configure && make' >log04.txt 2>&1
docker run rdkafka bash -c 'apt-get install -y liblz4-dev && ./configure --enable-static && make' >log05.txt 2>&1
docker run rdkafka bash -c 'apt-get install -y liblz4-dev && ./configure --enable-static --disable-lz4 && make' >log06.txt 2>&1
```

The log files are attached, but in summary, only `log05.txt` contains an error--the same error as in my original report.

[log01.txt](https://github.com/fede1024/rust-rdkafka/files/1675165/log01.txt)
[log02.txt](https://github.com/fede1024/rust-rdkafka/files/1675166/log02.txt)
[log03.txt](https://github.com/fede1024/rust-rdkafka/files/1675167/log03.txt)
[log04.txt](https://github.com/fede1024/rust-rdkafka/files/1675168/log04.txt)
[log05.txt](https://github.com/fede1024/rust-rdkafka/files/1675169/log05.txt)
[log06.txt](https://github.com/fede1024/rust-rdkafka/files/1675170/log06.txt)

**Comment by ongardie-ebay** [comment]
Thanks @fede1024. I had no idea --disable-lz4 meant "use the internal lz4". I think it makes sense to default to the internal lz4 unless someone explicitly asks for their system lz4.

**Comment by messense** [comment]
@ongardie-ebay Can you try https://github.com/fede1024/rust-rdkafka/pull/71 ?

**Comment by ongardie-ebay** [comment]
@messense seems to work fine with #71.

I tested it with this Dockerfile:
```
FROM ubuntu:16.04
RUN apt-get update
RUN apt-get install -y \
  build-essential \
  cmake \
  curl \
  git \
  python
RUN curl https://sh.rustup.rs -sSf | sh -s -- -y
RUN git clone https://github.com/fede1024/rust-rdkafka
WORKDIR rust-rdkafka
RUN git remote add messense https://github.com/messense/rust-rdkafka
RUN git fetch --all
RUN git reset --hard 70f584a
RUN git submodule update --init --recursive
```

By running the following:
```
docker build -t rust-rdkafka .
docker run rust-rdkafka bash -c 'PATH=$PATH:~/.cargo/bin cargo build --verbose' >log11.txt 2>&1
docker run rust-rdkafka bash -c 'apt-get -y install liblz4-dev && PATH=$PATH:~/.cargo/bin cargo build --verbose' >log12.txt 2>&1
```

Both builds succeeded. Logs:
[log11.txt](https://github.com/fede1024/rust-rdkafka/files/1678921/log11.txt)
[log12.txt](https://github.com/fede1024/rust-rdkafka/files/1678922/log12.txt)

**Comment by fede1024** [comment]
Both my branch (using internal lz4 by default) and #71 have been merged.

**Comment by ongardie-ebay** [comment]
Thanks @fede1024. I've updated to the latest master and the build is succeeding for me.
