### ISSUE TITLE
Enable the development of custom consumers

### ISSUE THREAD

**Issue by manifest** [fede1024/rust-rdkafka#690]
It is currently impossible to develop a custom consumer based on [`BaseConsumer`](https://docs.rs/rdkafka/latest/rdkafka/consumer/struct.BaseConsumer.html) because its [`queue` property](https://github.com/fede1024/rust-rdkafka/blob/d6ec6e15963fe263f3dcefbfbbb0f4214fff3f06/src/consumer/base_consumer.rs#L39), which is necessary to receive notifications about new incoming messages, is private.

We can define `set_nonempty_callback` method on `BaseConsumer` similarly to how it [has already been done for `PartitionQueue`](https://github.com/fede1024/rust-rdkafka/blob/d6ec6e15963fe263f3dcefbfbbb0f4214fff3f06/src/consumer/base_consumer.rs#L809-L836). That will allow setting [`rdkafka_sys::rd_kafka_queue_cb_event_enable` callback](https://github.com/fede1024/rust-rdkafka/blob/d6ec6e15963fe263f3dcefbfbbb0f4214fff3f06/src/consumer/base_consumer.rs#L828C13-L832) from within a custom consumer implementation.

[Here](https://github.com/fede1024/rust-rdkafka/pull/689) is implementation for the proposal.

**Comment by manifest** [comment]
@benesch I'm sorry to bother you, but you seems to be the only active owner of the repo. There are two ([1](https://github.com/fede1024/rust-rdkafka/issues/690) & [2](https://github.com/fede1024/rust-rdkafka/issues/692)) issues that prevent us from using the library. Both have PRs, but they seem to be stuck on review process. Could you please take a look?

**Comment by benesch** [comment]
I’ve largely retired from maintaining this project due to time constraints—so sorry! @davidblewett and some other folks from Datadog have largely taken over maintenance. Hopefully one of them has time to jump in soon.

**Comment by manifest** [comment]
Noted, thank you for responding.

**Comment by manifest** [comment]
@davidblewett Can you please have a look at this?
