### ISSUE TITLE
Config values can contain null characters resulting to panic

### ISSUE THREAD

**Issue by manifest** [fede1024/rust-rdkafka#692]
Config values can contain null characters. They need to be trimmed.

This has already been addressed [here](https://github.com/fede1024/rust-rdkafka/commit/353812ff958b4b65f9e65dd22a60e770ed6ba948), but it wasn't completely resolved.

[Here](https://github.com/fede1024/rust-rdkafka/pull/691) is PR with solution.

**Comment by manifest** [comment]
[Here](https://github.com/fede1024/rust-rdkafka/pull/688) is another PR by KowalczykBartek addressing the issue in the same way.

**Comment by Guyzeroth** [comment]
@davidblewett Would it be possible to get one of these solutions merged? What should be the process here?

**Comment by manifest** [comment]
Fixed
