### ISSUE TITLE
Use cmake to build rdkafka-sys

### ISSUE THREAD

**Issue by messense** [fede1024/rust-rdkafka#70]
Use cmake should make it support Windows I think.

**Comment by Roguelazer** [comment]
If this is done, is there any way to make it optional? I have a lot of systems that can do an autotools build but not a cmake build.

**Comment by fede1024** [comment]
+1 on making this optional and defaulting to make.

**Comment by messense** [comment]
Done.

Although I don't think use cmake by default is a big issue, you can use Docker/VM to build your project now days and definitely don't build your project on production machines.
