### ISSUE TITLE
Several unsound from_ptr methods

### ISSUE THREAD

**Issue by vorner** [fede1024/rust-rdkafka#72]
Hello

Reading through the documentation, I noticed there are some methods that are very likely unsound ‒ they aren'd marked as `unsafe`, but in fact they are, breaking Rusts safety protections. I discovered these:

```
NativeClient::from_ptr
NativeTopic::from_ptr
NativeClientConfig::from_ptr
Metadata::from_ptr
```

If I call them with eg. `NativeClient::from_ptr(1234 as _)`, I haven't used any unsafe code in my code, but the program will still explode with undefined behaviour.

Would it be OK to mark them as unsafe?

**Comment by fede1024** [comment]
They are indeed. I don't think there is any good reason not to mark them unsafe. Thank you for spotting this! Those methods should only be used internally (I should probably make them public at the crate level), but still, they can definitely cause undefined behavior if not used properly, so they should be marked unsafe.

**Comment by fede1024** [comment]
They are all marked as unsafe now. I'm going to close this issue, but if you find any other potentially unsafe method feel free to open again or create a new one. Thanks!
