### ISSUE TITLE
New rust-rdkafka release?

### ISSUE THREAD

**Issue by sebady** [fede1024/rust-rdkafka#739]
Hi,  

We are using this crate today.  Specifically the last crates.io released version 0.36.2.  

We need to pickup [this](https://github.com/fede1024/rust-rdkafka/issues/681) fix to move to later versions of rust.
Are there any plans for a new release?

**Comment by davidblewett** [comment]
Yes, I plan on cutting a release late this week or early next week.

**Comment by sebady** [comment]
@davidblewett Is there any way that I can help with the cutting of a new release?
