### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by hadronzoo** [fede1024/rust-rdkafka#742]
There have been several useful changes committed to master since the last release. Would you consider publishing a new release?

**Comment by bothra90** [comment]
It might also be a good idea to bump the librdkafka version as part of the new release. The current version (`2.3.0`) is now over a year old.

**Comment by davidblewett** [comment]
Version `0.37.0` was pushed out this morning.

**Comment by bothra90** [comment]
> https://github.com/fede1024/rust-rdkafka/issues/742#issuecomment-2475302049

@davidblewett: Any objection to a PR updating librdkafka to `2.6.0`?
