### ISSUE TITLE
Release 0.36.3 is breaking

### ISSUE THREAD

**Issue by quasi-coherent** [fede1024/rust-rdkafka#747]
The signatures of the `pre_rebalance`/`post_rebalance` methods of `ConsumerContext` are different between 0.36.2 and 0.36.3 because of [c811175](https://github.com/fede1024/rust-rdkafka/commit/c811175785c74bb9be4dc6f132dd8834ff57287a) (which is from a year ago):

```
error[E0050]: method `pre_rebalance` has 2 parameters but the declaration in trait `pre_rebalance` has 3
   |
99 |     fn pre_rebalance(&self, rebalance: &Rebalance) {
   |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected 3 parameters, found 2
   |
   = note: `pre_rebalance` from trait: `fn(&Self, &BaseConsumer<Self>, &rdkafka::consumer::Rebalance<'_>)`
```

**Comment by davidblewett** [comment]
I had forgotten about this change. In the morning I will pull this release and bump to 0.37.0.

**Comment by davidblewett** [comment]
Pushed `0.37.0` and yanked `0.36.3`.

**Comment by quasi-coherent** [comment]
@davidblewett Thank you so much!  And thank you for your effort more generally; I'm glad to see this project active.  I would love to help in any way if there's room and/or need in order to keep things going.  It's the best crate out there for Kafka in my opinion, so it's good for the ecosystem that it is exists and has a healthy community.

**Comment by davidblewett** [comment]
Helping triage reported issues would be great! Things like https://github.com/fede1024/rust-rdkafka/issues/741 .
