### ISSUE TITLE
Message headers support?

### ISSUE THREAD

**Issue by hammett** [fede1024/rust-rdkafka#78]
Looks like librdkafka's rd_kafka_msg_t -> rkm_headers is not reflected in the rdkafka's API. I'm sure it's not a trivial thing, but it's something our infrastructure uses to figure out how to deserialize the messages. Is there a plan to expose the headers in the Message trait?

Thanks!

**Comment by fede1024** [comment]
I had a look at the API and it shouldn't take too long to implement. I'll give it a try.

**Comment by fede1024** [comment]
Unfortunately it took much longer than expected to implement. I've just landed initial support on master. Please give it a try and let me know if you have any feedback.

**Comment by hammett** [comment]
Will do. Thank you!!

**Comment by benesch** [comment]
Assuming no news is good news! Please do open new issues if you have any trouble, @hammett.

**Comment by hammett** [comment]
sorry, yes, all good. thanks @benesch
