### ISSUE TITLE
Some of the examples don't compile

### ISSUE THREAD

**Issue by rream-isp** [fede1024/rust-rdkafka#81]
The at_least_once.rs example does not compile due to a dependency on rdkafka::client::ClientContext, which appears to no longer exist and FutureProducer is now parametric, but the usage of FutureProducer in the example code does not provide parameter.

**Comment by fede1024** [comment]
Which version of the library are you using? The example in master should be in sync with the master API.

**Comment by rream-isp** [comment]
That was the problem, I started a project using rust-rdkafka, but didn't reference it on the git master branch.
