### ISSUE TITLE
Upgrade to librdkafka 0.11.4

### ISSUE THREAD

**Issue by thijsc** [fede1024/rust-rdkafka#82]
It just came out: https://github.com/edenhill/librdkafka/releases/tag/v0.11.4

**Comment by fede1024** [comment]
Nice! I'll do the upgrade soon. I'm also working on a branch to add support for message headers. Hopefully that's going to be ready soon as well.

**Comment by fede1024** [comment]
Not much progress here. I have been focusing on the support for message headers (which is already available in the version currently pinned). I've implemented it in the [feature/producer_record](https://github.com/fede1024/rust-rdkafka/tree/feature/producer_record) branch and I suggest checking it out as it also changes the API a bit. I'll try to generate the bindings for the new version today or tomorrow.

**Comment by fede1024** [comment]
Done. Let me know if it works for you.
