### ISSUE TITLE
Need support of tokio library

### ISSUE THREAD

**Issue by surajpayu** [fede1024/rust-rdkafka#86]
https://github.com/tokio-rs/tokio-core is deprecated. It is being replaced by https://github.com/tokio-rs/tokio

When i tried using tokio to run a consumer , i am getting following error
error[E0277]: `std::cell::Cell<std::option::Option<std::thread::JoinHandle<()>>>` cannot be shared between threads safely
    --> src/main.rs:1481:6
     |
1481 |      tokio::run(h);
     |      ^^^^^^^^^^ `std::cell::Cell<std::option::Option<std::thread::JoinHandle<()>>>` cannot be shared between threads safely
     |
     = help: within `rdkafka::consumer::StreamConsumer`, the trait `std::marker::Sync` is not implemented for `std::cell::Cell<std::option::Option<std::thread::JoinHandle<()>>>`
     = note: required because it appears within the type `rdkafka::consumer::StreamConsumer`
     = note: required because of the requirements on the impl of `std::marker::Send` for `&rdkafka::consumer::StreamConsumer`
     = note: required because it appears within the type `rdkafka::consumer::MessageStream<'_, rdkafka::consumer::DefaultConsumerContext>`
     = note: required because it appears within the type `futures::stream::FilterMap<rdkafka::consumer::MessageStream<'_, rdkafka::consumer::DefaultConsumerContext>, [closure@src/main.rs:1444:42: 1452:10]>`
     = note: required because it appears within the type `futures::stream::ForEach<futures::stream::FilterMap<rdkafka::consumer::MessageStream<'_, rdkafka::consumer::DefaultConsumerContext>, [closure@src/main.rs:1444:42: 1452:10]>, [closure@src/main.rs:1452:21: 1474:10], std::result::Result<(), ()>>`
     = note: required by `tokio::run`

**Comment by fede1024** [comment]
Thank you for the bug report. See my [comment](https://github.com/fede1024/rust-rdkafka/issues/85#issuecomment-3978052800) on #85.

**Comment by fede1024** [comment]
I've updated the dependencies and my [comment](https://github.com/fede1024/rust-rdkafka/issues/85#issuecomment-398280136) on #85. I'll close this ticket in favor of #85, since they are very similar.
