### ISSUE TITLE
Add admin client functions

### ISSUE THREAD

**Issue by gklijs** [fede1024/rust-rdkafka#92]
The latest version of librdkafka supports the admin client. I wonder if it's a good idea to add support for it here, or put it in a separate project. Most of the time you will either consume/produce or use the admin client. But it might be useful for checking whether a topic is available and/or changing the configuration of a topic. https://github.com/edenhill/librdkafka/releases/tag/v0.11.5

**Comment by tyranron** [comment]
@fede1024 ping

Is there any plans/chances to support it in this library?

**Comment by thedodd** [comment]
This would be awesome to have.

**Comment by gklijs** [comment]
It seems @fede1024 last activity. I might try a rewrite and/or fork starting January?

**Comment by fede1024** [comment]
Hello! Sorry for being so absent (new job!). I probably won't be able to follow the development of the library very closely, but a rust-enthusiast kafka-savvy friend of mine is going to help releasing new versions, reviewing PRs and keeping the library in overall good health (thanks @flavray!). You should see some updates in the near future.
I think it would be great to support the API as part of this library, to keep parity with the C one.

**Comment by tyranron** [comment]
@fede1024 what do you think about creating dedicated org for this crate or [add Rus Bus](https://users.rust-lang.org/t/bus-factor-1-for-crates/17046), so the community will be able to catch up the crate in future?

**Comment by gklijs** [comment]
Not really part of this issue, sorry for that, but don't really see an issue related to the librdkafka version. Just got word from the Confluent Slack librdkafka v1.0.0 is planned to be released in a few weeks.

**Comment by gklijs** [comment]
librdkafka v1.0.0 is just released. I might give it a try to upgrade to that version in a pr.
