### ISSUE TITLE
Add confluent avro serializer.

### ISSUE THREAD

**Issue by gklijs** [fede1024/rust-rdkafka#93]
In a pet project on a private repo I'm able to both consume and produce massages compatible with the Confuent schema registry. I wonder if it might be a good idea to add. It's also possible to put them as separate functions in a crate, but in a way it's compatible.

**Comment by thijsc** [comment]
I'd say that should be a separate crate that has this one as a dependency. I know a lot of people use Kafka without the schema registry.

**Comment by noderat** [comment]
This would be useful, have you already created a crate for this @gklijs?

**Comment by gklijs** [comment]
I have it working in a project, and a lot of the code is already in a separate module. I will give it a try, making it a separate module. I took some shortcuts. For example there are several ways to configure the schema registry.

**Comment by gklijs** [comment]
It's available now at https://crates.io/crates/schema_registry_converter I think I might add the option to use a Schema directly, but currently it aspects all needed schema to be available in the schema repository. As I'm still pretty new to rust any suggestions for improvements are greatly appreciated.
